/*
Copyright 2022 Cerebras Systems, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	systemv1 "cerebras.com/job-operator/apis/system/v1"
	versioned "cerebras.com/job-operator/client-system/clientset/versioned"
	internalinterfaces "cerebras.com/job-operator/client-system/informers/externalversions/internalinterfaces"
	v1 "cerebras.com/job-operator/client-system/listers/system/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SystemInformer provides access to a shared informer and lister for
// Systems.
type SystemInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.SystemLister
}

type systemInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewSystemInformer constructs a new informer for System type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSystemInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSystemInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredSystemInformer constructs a new informer for System type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSystemInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SystemV1().Systems().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SystemV1().Systems().Watch(context.TODO(), options)
			},
		},
		&systemv1.System{},
		resyncPeriod,
		indexers,
	)
}

func (f *systemInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSystemInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *systemInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&systemv1.System{}, f.defaultInformer)
}

func (f *systemInformer) Lister() v1.SystemLister {
	return v1.NewSystemLister(f.Informer().GetIndexer())
}
