//go:build !ignore_autogenerated

/*
Copyright 2022 Cerebras Systems, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupResourceGrant) DeepCopyInto(out *GroupResourceGrant) {
	*out = *in
	if in.ResourceGrants != nil {
		in, out := &in.ResourceGrants, &out.ResourceGrants
		*out = make([]ResourceGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupResourceGrant.
func (in *GroupResourceGrant) DeepCopy() *GroupResourceGrant {
	if in == nil {
		return nil
	}
	out := new(GroupResourceGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupResourceRequest) DeepCopyInto(out *GroupResourceRequest) {
	*out = *in
	if in.ResourceRequests != nil {
		in, out := &in.ResourceRequests, &out.ResourceRequests
		*out = make([]ResourceRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupResourceRequest.
func (in *GroupResourceRequest) DeepCopy() *GroupResourceRequest {
	if in == nil {
		return nil
	}
	out := new(GroupResourceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupGrant) DeepCopyInto(out *NodeGroupGrant) {
	*out = *in
	if in.NodeGroups != nil {
		in, out := &in.NodeGroups, &out.NodeGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupGrant.
func (in *NodeGroupGrant) DeepCopy() *NodeGroupGrant {
	if in == nil {
		return nil
	}
	out := new(NodeGroupGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupRequest) DeepCopyInto(out *NodeGroupRequest) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupRequest.
func (in *NodeGroupRequest) DeepCopy() *NodeGroupRequest {
	if in == nil {
		return nil
	}
	out := new(NodeGroupRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Range) DeepCopyInto(out *Range) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Range.
func (in *Range) DeepCopy() *Range {
	if in == nil {
		return nil
	}
	out := new(Range)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Res) DeepCopyInto(out *Res) {
	*out = *in
	if in.Subresources != nil {
		in, out := &in.Subresources, &out.Subresources
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SubresourceRanges != nil {
		in, out := &in.SubresourceRanges, &out.SubresourceRanges
		*out = make(map[string][]Range, len(*in))
		for key, val := range *in {
			var outVal []Range
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]Range, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Res.
func (in *Res) DeepCopy() *Res {
	if in == nil {
		return nil
	}
	out := new(Res)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceGrant) DeepCopyInto(out *ResourceGrant) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]Res, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceGrant.
func (in *ResourceGrant) DeepCopy() *ResourceGrant {
	if in == nil {
		return nil
	}
	out := new(ResourceGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceLock) DeepCopyInto(out *ResourceLock) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceLock.
func (in *ResourceLock) DeepCopy() *ResourceLock {
	if in == nil {
		return nil
	}
	out := new(ResourceLock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceLock) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceLockList) DeepCopyInto(out *ResourceLockList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceLock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceLockList.
func (in *ResourceLockList) DeepCopy() *ResourceLockList {
	if in == nil {
		return nil
	}
	out := new(ResourceLockList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceLockList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceLockSpec) DeepCopyInto(out *ResourceLockSpec) {
	*out = *in
	if in.ResourceRequests != nil {
		in, out := &in.ResourceRequests, &out.ResourceRequests
		*out = make([]ResourceRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GroupResourceRequests != nil {
		in, out := &in.GroupResourceRequests, &out.GroupResourceRequests
		*out = make([]GroupResourceRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GroupResourceRequestUpperBounds != nil {
		in, out := &in.GroupResourceRequestUpperBounds, &out.GroupResourceRequestUpperBounds
		*out = make([]ResourceUpperBound, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SystemRequests != nil {
		in, out := &in.SystemRequests, &out.SystemRequests
		*out = make([]SystemRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeGroupRequests != nil {
		in, out := &in.NodeGroupRequests, &out.NodeGroupRequests
		*out = make([]NodeGroupRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceLockSpec.
func (in *ResourceLockSpec) DeepCopy() *ResourceLockSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceLockSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceLockStatus) DeepCopyInto(out *ResourceLockStatus) {
	*out = *in
	if in.ResourceGrants != nil {
		in, out := &in.ResourceGrants, &out.ResourceGrants
		*out = make([]ResourceGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GroupResourceGrants != nil {
		in, out := &in.GroupResourceGrants, &out.GroupResourceGrants
		*out = make([]GroupResourceGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GroupResourceGrantUpperBounds != nil {
		in, out := &in.GroupResourceGrantUpperBounds, &out.GroupResourceGrantUpperBounds
		*out = make([]ResourceUpperBound, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SystemGrants != nil {
		in, out := &in.SystemGrants, &out.SystemGrants
		*out = make([]SystemGrant, len(*in))
		copy(*out, *in)
	}
	if in.NodeGroupGrants != nil {
		in, out := &in.NodeGroupGrants, &out.NodeGroupGrants
		*out = make([]NodeGroupGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceLockStatus.
func (in *ResourceLockStatus) DeepCopy() *ResourceLockStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceLockStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequest) DeepCopyInto(out *ResourceRequest) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Subresources != nil {
		in, out := &in.Subresources, &out.Subresources
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequest.
func (in *ResourceRequest) DeepCopy() *ResourceRequest {
	if in == nil {
		return nil
	}
	out := new(ResourceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceUpperBound) DeepCopyInto(out *ResourceUpperBound) {
	*out = *in
	if in.Subresources != nil {
		in, out := &in.Subresources, &out.Subresources
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceUpperBound.
func (in *ResourceUpperBound) DeepCopy() *ResourceUpperBound {
	if in == nil {
		return nil
	}
	out := new(ResourceUpperBound)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemGrant) DeepCopyInto(out *SystemGrant) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemGrant.
func (in *SystemGrant) DeepCopy() *SystemGrant {
	if in == nil {
		return nil
	}
	out := new(SystemGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemRequest) DeepCopyInto(out *SystemRequest) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemRequest.
func (in *SystemRequest) DeepCopy() *SystemRequest {
	if in == nil {
		return nil
	}
	out := new(SystemRequest)
	in.DeepCopyInto(out)
	return out
}
