{
 "title": "Node Port Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "query_result(node_network_info{device=~\"e.*\"} * on (instance) group_left (node) label_replace(group(kube_node_info{node=\"$node\"}) by (node, internal_ip), \"instance\", \"$1:9100\", \"internal_ip\", \"(.*)\"))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Port Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Carrier status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "sum by (node, device) (node_network_carrier{device=~\"$interface\"} * on (instance) group_left (node) group by (instance, node) (label_replace(group(kube_node_info{node=~\"$node\"}) by (node, internal_ip), \"instance\", \"$1:9100\", \"internal_ip\", \"(.*)\")))",
     "legendFormat": "{{node}}:{{device}}"
    }
   ]
  },
  {
   "title": "Interface speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (node, interface) (\n    node_nic_stats_speed{node=~\"$node\", interface=~\"$interface\"}\n    or # if the device is only available from node exporter\n    (\n        label_replace(node_network_speed_bytes{device=~\"$interface\"}*8/1e6,\n            \"interface\", \"$1\", \"device\", \"(.*)\")\n        * on (instance) group_left (node) group by (instance, node)\n        (label_replace(group(kube_node_info{node=~\"$node\"}) by (node, internal_ip),\n            \"instance\", \"$1:9100\", \"internal_ip\", \"(.*)\")))\n)",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "node-exporter rate",
   "type": "stat",
   "description": "Scrape interval for node-exporter metrics (named node_network_*), average over last 15 minutes",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(15*60)/(count_over_time(node_network_carrier{device=~\"$interface\"}[15m]) * on (instance) group_left (node) group by (instance, node) (label_replace(kube_node_info{node=~\"$node\"}, \"instance\", \"$1:9100\", \"internal_ip\", \"(.*)\")))",
     "legendFormat": "{{node}}:{{device}}"
    }
   ]
  },
  {
   "title": "ethtool-exporter rate",
   "type": "stat",
   "description": "Scrape interval for ethtool-exporter metrics (named node_nic_stats_*), averaged over the last 15 minutes",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(15*60)/count_over_time(node_nic_stats_carrier{interface=~\"$interface\", node=~\"$node\"}[15m])",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "Reachability",
   "type": "state-timeline",
   "description": "Interfaces that aren't responding to pings (using CPingmesh).",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "min by (host, nic) (increase(pingmesh_server_pings_total{host=~\"$node\", nic=~\"$interface\"}[5m]))\nunless on (host, nic)\n(pingmesh_server_healthy < 1)",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  { "title": "Hardware Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "NIC ASIC temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum by (node, interface) (node_nic_stats_temperature{interface=~\"$interface\", node=~\"$node\"})",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "Optics temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum by (node, interface) (node_nic_stats_opt_temperature{interface=~\"$interface\", node=~\"$node\"})",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "RX power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "sum by (node, interface) (node_nic_stats_rx_pwr_1{interface=~\"$interface\", node=~\"$node\"})",
     "legendFormat": "{{node}}:{{interface}} Lane 1"
    },
    {
     "expr": "sum by (node, interface) (node_nic_stats_rx_pwr_2{interface=~\"$interface\", node=~\"$node\"})",
     "legendFormat": "{{node}}:{{interface}} Lane 2"
    },
    {
     "expr": "sum by (node, interface) (node_nic_stats_rx_pwr_3{interface=~\"$interface\", node=~\"$node\"})",
     "legendFormat": "{{node}}:{{interface}} Lane 3"
    },
    {
     "expr": "sum by (node, interface) (node_nic_stats_rx_pwr_4{interface=~\"$interface\", node=~\"$node\"})",
     "legendFormat": "{{node}}:{{interface}} Lane 4"
    }
   ]
  },
  {
   "title": "TX power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "sum by (node, interface) (node_nic_stats_tx_pwr_1{interface=~\"$interface\", node=~\"$node\"})",
     "legendFormat": "{{node}}:{{interface}} Lane 1"
    },
    {
     "expr": "sum by (node, interface) (node_nic_stats_tx_pwr_2{interface=~\"$interface\", node=~\"$node\"})",
     "legendFormat": "{{node}}:{{interface}} Lane 2"
    },
    {
     "expr": "sum by (node, interface) (node_nic_stats_tx_pwr_3{interface=~\"$interface\", node=~\"$node\"})",
     "legendFormat": "{{node}}:{{interface}} Lane 3"
    },
    {
     "expr": "sum by (node, interface) (node_nic_stats_tx_pwr_4{interface=~\"$interface\", node=~\"$node\"})",
     "legendFormat": "{{node}}:{{interface}} Lane 4"
    }
   ]
  },
  {
   "title": "TX Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "sum by (node, interface) (node_nic_stats_tx_curr_1{interface=~\"$interface\", node=~\"$node\"})",
     "legendFormat": "{{node}}:{{interface}} Lane 1"
    },
    {
     "expr": "sum by (node, interface) (node_nic_stats_tx_curr_2{interface=~\"$interface\", node=~\"$node\"})",
     "legendFormat": "{{node}}:{{interface}} Lane 2"
    },
    {
     "expr": "sum by (node, interface) (node_nic_stats_tx_curr_3{interface=~\"$interface\", node=~\"$node\"})",
     "legendFormat": "{{node}}:{{interface}} Lane 3"
    },
    {
     "expr": "sum by (node, interface) (node_nic_stats_tx_curr_4{interface=~\"$interface\", node=~\"$node\"})",
     "legendFormat": "{{node}}:{{interface}} Lane 4"
    }
   ]
  },
  { "title": "Traffic rate counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "RX Rate - kernel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (node, device) (rate(node_network_receive_bytes_total{device=~\"$interface\"}[$__rate_interval]) * on (instance) group_left (node) group by (instance, node) (label_replace(kube_node_info{node=~\"$node\"}, \"instance\", \"$1:9100\", \"internal_ip\", \"(.*)\")))",
     "legendFormat": "{{node}}:{{device}}"
    }
   ]
  },
  {
   "title": "RX Rate - ethtool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (node, interface) (rate(node_nic_stats_rx_bytes{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}} bytes"
    },
    {
     "expr": "sum by (node, interface) (rate(node_nic_stats_rx_bytes_phy{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}} bytes PHY"
    }
   ]
  },
  {
   "title": "TX Rate - kernel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (node, device) (rate(node_network_transmit_bytes_total{device=~\"$interface\"}[$__rate_interval]) * on (instance) group_left (node) group by (instance, node) (label_replace(kube_node_info{node=~\"$node\"}, \"instance\", \"$1:9100\", \"internal_ip\", \"(.*)\")))",
     "legendFormat": "{{node}}:{{device}}"
    }
   ]
  },
  {
   "title": "TX Rate - ethtool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (node, interface) (rate(node_nic_stats_tx_bytes{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}} bytes"
    },
    {
     "expr": "sum by (node, interface) (rate(node_nic_stats_tx_bytes_phy{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}} bytes PHY"
    }
   ]
  },
  { "title": "Port Stats - increases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "RX Bytes - kernel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node, device) (increase(node_network_receive_bytes_total{device=~\"$interface\"}[$__rate_interval]) * on (instance) group_left (node) group by (instance, node) (label_replace(kube_node_info{node=~\"$node\"}, \"instance\", \"$1:9100\", \"internal_ip\", \"(.*)\")))",
     "legendFormat": "{{node}}:{{device}}"
    }
   ]
  },
  {
   "title": "RX Bytes - ethtool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rx_bytes{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}} bytes"
    },
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rx_bytes_phy{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}} bytes PHY"
    }
   ]
  },
  {
   "title": "TX Bytes - kernel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node, device) (increase(node_network_transmit_bytes_total{device=~\"$interface\"}[$__rate_interval]) * on (instance) group_left (node) group by (instance, node) (label_replace(kube_node_info{node=~\"$node\"}, \"instance\", \"$1:9100\", \"internal_ip\", \"(.*)\")))",
     "legendFormat": "{{node}}:{{device}}"
    }
   ]
  },
  {
   "title": "TX Bytes - ethtool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_tx_bytes{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}} bytes"
    },
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_tx_bytes_phy{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}} bytes PHY"
    }
   ]
  },
  {
   "title": "Flaps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by (node, device) (increase(node_network_carrier_changes_total{device=~\"$interface\"}[$__rate_interval]) * on (instance) group_left (node) group by (instance, node) (label_replace(group(kube_node_info{node=~\"$node\"}) by (node, internal_ip), \"instance\", \"$1:9100\", \"internal_ip\", \"(.*)\")))",
     "legendFormat": "{{node}}:{{device}}"
    }
   ]
  },
  {
   "title": "RX CRC Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rx_crc_errors_phy{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "RX PHY Per-Lane Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rx_err_lane_0_phy{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}} Lane 0"
    },
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rx_err_lane_1_phy{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}} Lane 1"
    },
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rx_err_lane_2_phy{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}} Lane 2"
    },
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rx_err_lane_3_phy{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}} Lane 3"
    }
   ]
  },
  {
   "title": "RX PCS Symbol Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rx_pcs_symbol_err_phy{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "RX WQE Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rx_wqe_err{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "FEC Corrected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rx_corrected_bits_phy{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "req CQE error count",
   "type": "timeseries",
   "description": "from sysfs hw_counters, req_cqe_error",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_req_cqe_error{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "packet_seq_error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_packet_seq_err{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "out_of_seq",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_out_of_sequence{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "TX CQE Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_tx_cqe_err{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "local_ack_timeout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_local_ack_timeout_err{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "resp_cqe_error count",
   "type": "timeseries",
   "description": "from sysfs hw_counters, resp_cqe_error",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_resp_cqe_error{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "rnr_nak_retry_err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rnr_nak_retry_err{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "out_of_buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_out_of_buffer{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "local ack timeout error count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_local_ack_timeout_err{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "implied nak seq err count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_implied_nak_seq_err{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "RX PFC duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rx_pfc_duration{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "TX PFC duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_tx_pfc_duration{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "RX PFC count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rx_pfc{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "TX PFC count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_tx_pfc{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "RX discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rx_discards_phy{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "TX discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_tx_discards_phy{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "RX discards (priority 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rx_discards_prio5{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "RP CNP Handled count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rp_cnp_handled{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "NP ECN Marked RoCE Packets count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_np_ecn_marked_roce_packets{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "RP CNP Ignored count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_rp_cnp_ignored{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "NP CNP Sent count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_np_cnp_sent{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "RoCE Slow Restart CNP count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_roce_slow_restart_cnps{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "RoCE Adaptive Retransmit count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_roce_adp_retrans{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "RoCE Adaptive Retransmit Timeout count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 175 },
   "targets": [
    {
     "expr": "sum by (node, interface) (increase(node_nic_stats_roce_adp_retrans_to{interface=~\"$interface\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "Port Stats - raw values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 183 },
   "collapsed": true,
   "panels": [
    {
     "title": "RX Bytes - kernel",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_network_receive_bytes_total{device=~\"$interface\"} * on (instance) group_left (node) group by (instance, node) (label_replace(kube_node_info{node=~\"$node\"}, \"instance\", \"$1:9100\", \"internal_ip\", \"(.*)\"))",
       "legendFormat": "{{node}}:{{device}}"
      }
     ]
    },
    {
     "title": "RX Bytes - ethtool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_rx_bytes{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}} bytes"
      },
      {
       "expr": "sum by (node, interface) (node_nic_stats_rx_bytes_phy{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}} bytes PHY"
      }
     ]
    },
    {
     "title": "TX Bytes - kernel",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_network_transmit_bytes_total{device=~\"$interface\"} * on (instance) group_left (node) group by (instance, node) (label_replace(kube_node_info{node=~\"$node\"}, \"instance\", \"$1:9100\", \"internal_ip\", \"(.*)\"))",
       "legendFormat": "{{node}}:{{device}}"
      }
     ]
    },
    {
     "title": "TX Bytes - ethtool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_tx_bytes{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}} bytes"
      },
      {
       "expr": "sum by (node, interface) (node_nic_stats_tx_bytes_phy{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}} bytes PHY"
      }
     ]
    },
    {
     "title": "Flaps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
     "targets": [
      {
       "expr": "node_network_carrier_changes_total{device=~\"$interface\"} * on (instance) group_left (node) group by (instance, node) (label_replace(group(kube_node_info{node=~\"$node\"}) by (node, internal_ip), \"instance\", \"$1:9100\", \"internal_ip\", \"(.*)\"))",
       "legendFormat": "{{node}}:{{device}}"
      }
     ]
    },
    {
     "title": "RX CRC Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_rx_crc_errors_phy{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "RX PHY Per-Lane Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_rx_err_lane_0_phy{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}} Lane 0"
      },
      {
       "expr": "sum by (node, interface) (node_nic_stats_rx_err_lane_1_phy{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}} Lane 1"
      },
      {
       "expr": "sum by (node, interface) (node_nic_stats_rx_err_lane_2_phy{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}} Lane 2"
      },
      {
       "expr": "sum by (node, interface) (node_nic_stats_rx_err_lane_3_phy{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}} Lane 3"
      }
     ]
    },
    {
     "title": "RX PCS Symbol Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_rx_pcs_symbol_err_phy{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "RX WQE Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_rx_wqe_err{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "FEC Corrected",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_rx_corrected_bits_phy{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "req CQE error count",
     "type": "timeseries",
     "description": "from sysfs hw_counters, req_cqe_error",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_req_cqe_error{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "packet_seq_error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 216 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_packet_seq_err{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "out_of_seq",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 224 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_out_of_sequence{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "TX CQE Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 224 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_tx_cqe_err{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "local_ack_timeout",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 232 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_local_ack_timeout_err{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "resp_cqe_error count",
     "type": "timeseries",
     "description": "from sysfs hw_counters, resp_cqe_error",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 232 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_resp_cqe_error{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "rnr_nak_retry_err",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 240 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_rnr_nak_retry_err{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "out_of_buffer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 240 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_out_of_buffer{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "local ack timeout error count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 248 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_local_ack_timeout_err{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "implied nak seq err count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 248 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_implied_nak_seq_err{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "RX PFC duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 256 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_rx_pfc_duration{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "TX PFC duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 256 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_tx_pfc_duration{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "RX PFC count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 264 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_rx_pfc{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "TX PFC count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 264 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_tx_pfc{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "TX discards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 272 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_tx_discards_phy{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "RP CNP Handled count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 272 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_rp_cnp_handled{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "NP ECN Marked RoCE Packets count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 280 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_np_ecn_marked_roce_packets{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "RP CNP Ignored count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 280 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_rp_cnp_ignored{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "NP CNP Sent count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 288 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_np_cnp_sent{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "RoCE Slow Restart CNP count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 288 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_roce_slow_restart_cnps{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "RoCE Adaptive Retransmit count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 296 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_roce_adp_retrans{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "RoCE Adaptive Retransmit Timeout count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 296 },
     "targets": [
      {
       "expr": "sum by (node, interface) (node_nic_stats_roce_adp_retrans_to{interface=~\"$interface\", node=~\"$node\"})",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    }
   ]
  }
 ]
}