{
 "title": "Node Health Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "query_result(kube_node_info or on (node) label_replace(node_uname_info, \"node\", \"$1\", \"nodename\", \"(.*)\"))"
    }
   },
   {
    "name": "internal_ip",
    "query": {
     "query": "query_result(kube_node_info{node=\"$node\"} or label_replace(node_uname_info{nodename=\"$node\"}, \"internal_ip\", \"$1\", \"instance\", \"(.*):9100\"))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kube_node_status_condition{node=~\"$node\", condition=~\"ClusterMgmt.*|ClusterDeploy.*|Csadm.*\", condition!~\".*NodeNIC.*\", condition!~\".*NodeSwitchPortError\", status=\"true\"} > 0) or on (node) kube_node_spec_taint{job=\"kube-state-metrics\",key=\"node.kubernetes.io/unreachable\",effect=\"NoSchedule\", node=~\"$node\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Node Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interface_watch_list{node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cpu_info{instance=\"$internal_ip:9100\", cpu=\"0\", core=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Physical Core Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (core) (node_cpu_info{instance=\"$internal_ip:9100\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hardware Thread Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_info{instance=\"$internal_ip:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Installed Memory Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_dimm_capacity_bytes{node=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Host OS Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Use %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(1 - rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$internal_ip:9100\"}[5m])) without (cpu, mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Use %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*((node_memory_MemTotal_bytes{instance=\"$internal_ip:9100\"} - node_memory_MemAvailable_bytes{instance=\"$internal_ip:9100\"}) / node_memory_MemTotal_bytes{instance=\"$internal_ip:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Use %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (node_filesystem_free_bytes{device=~\"/dev/.*\", instance=\"$internal_ip:9100\"} / node_filesystem_size_bytes{device=~\"/dev/.*\", instance=\"$internal_ip:9100\"})",
     "legendFormat": "{{device}} on {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Vendor-neutral health, current status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "Overall IPMI Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ipmi_health_status{category=\"Overall\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Processor Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ipmi_health_status{category=\"Processor\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Memory Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ipmi_health_status{category=\"Memory\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Package Throttle Events (Intel only)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(node_cpu_package_throttles_total{instance=\"$internal_ip:9100\"}[$__rate_interval])",
     "legendFormat": "Package {{package}}"
    }
   ]
  },
  {
   "title": "Kubernetes Node Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((kube_node_status_condition{node=\"$node\", condition!~\"Ready|ClusterMgmt.*|Csadm.*\", status=\"true\"} > 0) >=bool 0) or on (node) \n(kube_node_spec_taint{node=\"$node\", job=\"kube-state-metrics\",key=\"node.kubernetes.io/unreachable\",effect=\"NoSchedule\"} == 1)\nor on (node) (kube_node_spec_taint{node=\"$node\", job=\"kube-state-metrics\",key=\"node.kubernetes.io/unreachable\",effect=\"NoSchedule\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "csadm Status",
   "type": "stat",
   "description": "Error if the node has been marked as down by an administrator or by other fault detection.\nCheck the csadm tool for a description of the issue.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kube_node_status_condition{node=~\"$node\", condition=~\"ClusterMgmt.*|ClusterDeploy.*|Csadm.*\", condition!~\".*NodeNIC.*\", condition!~\".*NodeSwitchPortError\", status=\"true\"} > 0) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OEM-specific health, current status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "CPU Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ipmi_health_status{category=\"CPU\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ipmi_health_status{category=\"Fan\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Supply Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ipmi_health_status{category=\"Power supply\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ipmi_health_status{category=\"Storage\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ipmi_health_status{category=\"Temperatures\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Status history", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "IPMI Health Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "node_ipmi_health_status{node=\"$node\"}",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Kube Health",
   "type": "state-timeline",
   "description": "\"Data does not have a time field\" indicates no kubernetes problems",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "(kube_node_status_condition{node=\"$node\", condition!~\"Ready|ClusterMgmt.*|Csadm.*\", status=\"true\"} > 0) >=bool 0",
     "legendFormat": "{{condition}}"
    },
    {
     "expr": "(\n  (kube_node_status_condition{node=\"$node\", condition=\"Ready\", status=\"true\"} == 0)\nunless \n  (kube_node_spec_taint{node=\"$node\", job=\"kube-state-metrics\",key=\"node.kubernetes.io/unreachable\",effect=\"NoSchedule\"} == 1)\n) > 0\n",
     "legendFormat": "NotReady"
    },
    {
     "expr": "kube_node_spec_taint{node=\"$node\", job=\"kube-state-metrics\",key=\"node.kubernetes.io/unreachable\",effect=\"NoSchedule\"} == 1",
     "legendFormat": "NotPingable"
    }
   ]
  },
  {
   "title": "Network Health",
   "type": "state-timeline",
   "description": "Interfaces that are down, flapping, or aren't responding to pings (from CPingmesh).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "min by (host, nic) (increase(pingmesh_server_pings_total{host=~\"$node\"}[5m]) == 0)\nunless on (host, nic)\n(pingmesh_server_healthy < 1)",
     "legendFormat": "{{nic}}"
    },
    {
     "expr": "(min_over_time(interface_watch_list:status{node=~\"$node\"}[$__rate_interval]) == bool 0) > 0",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "(increase(interface_watch_list:status_changes_total{node=~\"$node\"}[$__rate_interval]) >= bool 2) > 0",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Fan and Thermal sensor status (may not be available on all nodes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "Fan Speeds",
   "type": "timeseries",
   "description": "Fan speeds in the range 0-100 are probably a percentage of max speed, while higher values are RPMs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_thermals_fan{node=\"$node\"}",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_thermals_thermometer{node=\"$node\"}",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "(node_hwmon_sensor_label{label=\"Tdie\", instance=\"$internal_ip:9100\"} or node_hwmon_sensor_label{label=~\"Tccd.*\", instance=\"$internal_ip:9100\"} or node_hwmon_sensor_label{label=~\"Package id.*\", instance=\"$internal_ip:9100\"}) * on (instance, chip, sensor) group_right (label) node_hwmon_temp_celsius{instance=\"$internal_ip:9100\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Critical Fan Speeds",
   "type": "state-timeline",
   "description": "Fan speeds below the critical threshold. Speeds in the range 0-100 are probably a percentage of max speed, while higher values are RPMs",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(max_over_time(node_thermals_fan{node=\"$node\"} [$__rate_interval]) < ignoring (type) node_thermals_fan_thresh{node=\"$node\", type=\"error\"}) * on (index, node) group_left (thresh) count_values without() (\"thresh\", node_thermals_fan_thresh{type=\"error\", node=\"$node\"})",
     "legendFormat": "{{description}} < {{thresh}}"
    }
   ]
  },
  {
   "title": "Critical Temperature Sensors",
   "type": "state-timeline",
   "description": "Temperature sensors that exceed the critical threshold.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(max_over_time(node_thermals_thermometer{node=\"$node\"} [$__rate_interval]) > ignoring (type) node_thermals_thermometer_thresh{node=\"$node\", type=\"error\"}) * on (index, node) group_left (thresh) count_values without() (\"thresh\", node_thermals_thermometer_thresh{type=\"error\", node=\"$node\"})",
     "legendFormat": "{{description}} > {{thresh}}"
    }
   ]
  },
  { "title": "CPU Frequency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "CPU core frequency as % of max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_cpu_scaling_frequency_hertz{instance=\"$internal_ip:9100\"} / node_cpu_frequency_max_hertz{instance=\"$internal_ip:9100\"})",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "Average CPU frequency as % of max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (instance) (node_cpu_scaling_frequency_hertz{instance=\"$internal_ip:9100\"}) / sum by (instance) (node_cpu_frequency_max_hertz{instance=\"$internal_ip:9100\"}))",
     "legendFormat": " "
    }
   ]
  }
 ]
}