{
 "title": "Switch Port Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "switch",
    "label": "Switch Name",
    "query": {
     "query": "label_values(linkmon_switch_extra_labels,switch)"
    }
   },
   {
    "name": "port",
    "label": "Port Names",
    "query": {
     "query": "query_result(linkmon_switch_extra_labels{switch=\"$switch\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Port Remote Endpoint",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "interface_watch_list{switch_id=\"$switch\", ifName=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "linkmon_switch_version_info{switch=\"$switch\", vendor=\"Credo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snmp-exporter rate",
   "type": "stat",
   "description": "Scrape interval for snmp-exporter metrics (named if*), averaged over the last 15 minutes",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(15*60)/count_over_time(ifOperStatus{switch_id=\"$switch\", ifName=\"$port\"}[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "linkmon rate",
   "type": "stat",
   "description": "Scrape interval for linkmon metrics (named linkmon_*), averaged over the last 15 minutes",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(15*60)/count_over_time(linkmon_switch_extra_labels{switch=\"$switch\", port=\"$port\"}[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transceiver Details",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "linkmon_switch_extra_labels{switch=\"$switch\", port=~\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(linkmon_switch_extra_labels{switch=\"$switch\", port=~\"$port\", opt_speed=~\"100GBASE-DR\", fec_enabled=\"false\"} * on (switch) group_left (vendor) (linkmon_switch_version_info{switch=\"$switch\", vendor=\"Credo\"})) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SNMP status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "ifOperStatus{switch_id=\"$switch\", ifName=\"$port\"} == 1",
     "legendFormat": "{{switch_id}}:{{port}}"
    }
   ]
  },
  {
   "title": "linkmon (switch CLI) status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "linkmon_switch_oper_status{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "{{switch}}:{{port}}"
    }
   ]
  },
  {
   "title": "RX Bytes (SNMP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ifHCInOctets{switch_id=\"$switch\", ifName=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX Rate (SNMP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{switch_id=\"$switch\", ifName=\"$port\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX Bytes (linkmon)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "linkmon_switch_rx_bytes{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX Rate (from switch command output)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "linkmon_switch_rx_kbps{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flaps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "linkmon_switch_carrier_changes{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TX Rate (from switch command output)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "linkmon_switch_tx_kbps{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRC Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "linkmon_switch_crc_errors{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FEC Uncorrected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "linkmon_switch_fec_uncorrected_codewords{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FEC Corrected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "linkmon_switch_fec_corrected_codewords{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "linkmon_switch_input_errors{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "linkmon_switch_runts{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TX PFC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "linkmon_switch_tx_pfc{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "RX PFC"
    }
   ]
  },
  {
   "title": "Input Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "linkmon_switch_in_discards{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "RX PFC"
    }
   ]
  },
  {
   "title": "RX PFC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "linkmon_switch_rx_pfc{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "RX PFC"
    }
   ]
  },
  {
   "title": "Output Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "linkmon_switch_out_discards{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "RX PFC"
    }
   ]
  },
  {
   "title": "Optics Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "linkmon_switch_opt_temperature{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Discards (Priority 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "linkmon_switch_out_discards_prio5{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "Priority 5 discards"
    }
   ]
  },
  {
   "title": "Optics RX Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "linkmon_switch_opt_rx_power{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "Lane {{lane}}"
    }
   ]
  },
  {
   "title": "Optics TX Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "linkmon_switch_opt_tx_current{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "Lane {{lane}}"
    }
   ]
  },
  {
   "title": "ECN Marked Packets on TC5 count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "linkmon_switch_ecn_marked_packets_tc5{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Optics TX Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "linkmon_switch_opt_tx_power{switch=\"$switch\", port=\"$port\"}",
     "legendFormat": "Lane {{lane}}"
    }
   ]
  }
 ]
}