{
 "title": "Switch Health Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "switch",
    "label": "Switch Name",
    "query": {
     "query": "label_values(linkmon_switch_extra_labels,switch)"
    }
   },
   {
    "name": "num_ports",
    "query": {
     "query": "query_result(count(linkmon_switch_oper_status{switch=~\"$switch\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "group by (firmware_version, model, vendor) (last_over_time(linkmon_switch_version_info{switch=~\"$switch\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "group by (error) (interface_watch_list_errors{switch_id=~\"$switch\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Ports",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (port) (linkmon_switch_extra_labels{switch=~\"$switch\"}))",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "Down Ports",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(linkmon_switch_oper_status{switch=~\"$switch\"} < 1)",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "Last Reboot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Fallback to sysUpTime if linkmon_switch_uptime isn't present for the switch\n$__to - ((linkmon_switch_uptime{switch=~\"$switch\"}*1000) or on () (sysUpTime{switch_id=\"$switch\"}*10))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Fallback to sysUpTime if linkmon_switch_uptime isn't present for the switch\nlinkmon_switch_uptime{switch=~\"$switch\"} or on () (sysUpTime{switch_id=\"$switch\"}/100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg by (switch, port) (increase(linkmon_switch_carrier_changes{switch=~\"$switch\"}[11m])) > 0",
     "legendFormat": "{{switch}}:{{port}} Flapping"
    },
    {
     "expr": "avg by (switch, port) (increase(linkmon_switch_crc_errors[11m])) > 0",
     "legendFormat": "{{switch}}:{{port}} CRC Error"
    },
    {
     "expr": "avg by (switch, port) (increase(linkmon_switch_out_discards{switch=~\"$switch\"}[$__rate_interval])) > 0",
     "legendFormat": "{{switch}}:{{port}} Out Discards"
    },
    {
     "expr": "avg by (switch, port) (increase(linkmon_switch_in_discards{switch=~\"$switch\"}[$__rate_interval])) > 0",
     "legendFormat": "{{switch}}:{{port}} In Discards"
    },
    {
     "expr": "avg by (switch, port) (increase(linkmon_switch_delta_fec_uncorrected_codewords{switch=~\"$switch\"}[$__rate_interval])) > 0",
     "legendFormat": "{{switch}}:{{port}} FEC Uncorrected"
    },
    {
     "expr": "linkmon_switch_fan_health{switch=~\"$switch\"} == 2",
     "legendFormat": "Fan Error: {{desc}}"
    },
    {
     "expr": "linkmon_switch_temperature_health{switch=~\"$switch\"} == 2",
     "legendFormat": "Temperature Error: {{desc}}"
    },
    {
     "expr": "linkmon_switch_psu_health{switch=~\"$switch\"} == 2",
     "legendFormat": "Power Error: {{desc}}"
    }
   ]
  },
  { "title": "Ports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Ports Down",
   "type": "table",
   "description": "In the past five minutes, ports that have not been up at all.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg by (port, desc, node) (max_over_time(linkmon_switch_oper_status{switch=~\"$switch\"}[5m]) < 1) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ports Flapping",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (switch_id, ifName) (( (changes(ifLastChange{switch_id=~\"$switch\"}[$__range])>0) ) or\n        on (switch_id, ifName)(  (label_replace(label_replace(\n            (changes(linkmon_switch_carrier_changes{switch=~\"$switch\"}[$__range]) > 0),\n            \"ifName\", \"$1\", \"port\", \"(.*)\"),\n            \"switch_id\", \"$1\", \"switch\", \"(.*)\"))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port RX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "linkmon_switch_rx_kbps{switch=~\"$switch\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "CRC Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(linkmon_switch_crc_errors{switch=~\"$switch\"}[11m]) > 0",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "FEC Corrected Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(linkmon_switch_fec_corrected_codewords{switch=~\"$switch\"}[$__rate_interval]) > 0",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "FEC Uncorrected Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(linkmon_switch_fec_uncorrected_codewords{switch=~\"$switch\"}[$__rate_interval]) > 0",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Port Out Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (switch, port) (increase(linkmon_switch_out_discards{switch=~\"$switch\"}[11m])) > 0",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Optics over warning threshold temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (switch, port) (linkmon_switch_opt_temperature{switch=~\"$switch\"}) > 70",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "table",
   "description": "Description of the remote endpoints connected to each of the switch's ports.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "group by (port, conn_type, device, node) (label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"port\", \"$1\", \"ifName\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "group by (port, desc) (linkmon_switch_oper_status{switch=~\"$switch\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Power and Thermals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Critical Fan Speeds",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sort_desc(avg by (desc) (linkmon_switch_fan_health{switch=~\"$switch\"})) > 0",
     "legendFormat": "{{desc}}"
    }
   ]
  },
  {
   "title": "Critical Temperature Sensors",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sort_desc(avg by (desc) (linkmon_switch_temperature_health{switch=~\"$switch\"})) > 0",
     "legendFormat": "{{desc}}"
    }
   ]
  },
  {
   "title": "Critical PSUs",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sort_desc(avg by (desc) (linkmon_switch_psu_health{switch=~\"$switch\"})) > 0",
     "legendFormat": "{{desc}}"
    }
   ]
  },
  {
   "title": "Fan Speeds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "linkmon_switch_fan_rpm{switch=~\"$switch\"}",
     "legendFormat": "{{desc}}"
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "linkmon_switch_temperature{switch=~\"$switch\"}",
     "legendFormat": "{{desc}}"
    }
   ]
  }
 ]
}