{
 "title": "System Port Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system",
    "query": {
     "query": "label_values(system_label,system)"
    }
   },
   {
    "name": "port",
    "label": "Port Names",
    "query": {
     "query": "label_values(system_network_health,port)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System network health",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "system_network_health{system=\"$system\", port=\"$port\"}",
     "legendFormat": "{{system}}:{{port}}"
    }
   ]
  },
  {
   "title": "Reachability",
   "type": "state-timeline",
   "description": "Ports that aren't responding to pings (using CPingmesh).",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "min by (host, nic) (increase(pingmesh_server_pings_total{host=~\"$system\", nic=~\"$port\"}[5m]))\nunless on (host, nic)\n(pingmesh_server_healthy < 1)",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "System overall health",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "system_overall_health{system=\"$system\"}",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "system-exporter rate",
   "type": "stat",
   "description": "Scrape interval for system-exporter metrics (named system_network_*), averaged over last 15 minutes",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(15*60)/count_over_time(system_network_rx_bytes{system=\"$system\", port=\"$port\"}[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_network_rx_bytes{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX Rate (calculated by Prometheus)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(system_network_rx_bytes{system=\"$system\", port=\"$port\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX Rate (calculated by system)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "system_network_rx_bytes_per_second{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TX Rate (calculated by system)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "system_network_tx_bytes_per_second{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flaps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "system_network_flap_count{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX Remote Link Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "system_network_rx_remote_link_flt{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX Local Link Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "system_network_rx_local_link_flt{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRC Errors (Bad FCS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "system_network_rx_pkt_bad_fcs{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FEC Corrected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "system_network_rx_fec_corrected_pkts{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FEC Uncorrected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "system_network_rx_fec_uncorrected_pkts{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active QPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "system_network_active_qps{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error QPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "system_network_err_qps{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Squad QPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "system_network_sqd_qps{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX Sequence Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "system_network_rx_sequence_errors{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX Pause",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "system_network_rx_pause{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TX Sequence Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "system_network_tx_sequence_errors{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TX Pause",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "system_network_tx_pause{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ACK Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "system_network_ack_timeouts{system=\"$system\", port=\"$port\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}