{
 "title": "System Health Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system",
    "query": {
     "query": "label_values(system_label,system)"
    }
   },
   { "name": "glitch_thresh", "label": "Glitch Threshold", "query": "1" },
   { "name": "current_thresh", "label": "Current Threshold (A)", "query": "380" },
   { "name": "voltage_thresh", "label": "Voltage Threshold (V)", "query": "0.7" }
  ]
 },
 "panels": [
  { "title": "Health Summary and Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall Health",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by (system) (system_overall_health{system=~\"$system\"})",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "System Config",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "system_wse_config_info{system=~\"$system\"}",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Utilization during time range",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(avg_over_time((sum((group(wsjob_system_grant{system=~\"$system\"}) by (system)) or (sum(0*system_label) by (system))) / count(group(namespace_reserved_system{system=~\"$system\"}) by (system)))[$__range:$__rate_interval]) *100, 100)",
     "legendFormat": "Percentage"
    },
    {
     "expr": "avg_over_time((sum(group(wsjob_system_grant{system=~\"$system\"}) by (system)) or sum(sum(system_label*0) by (system)))[$__range:$__rate_interval]) * (${__to:date:seconds}-${__from:date:seconds})/3600",
     "legendFormat": "Hours"
    }
   ]
  },
  { "title": "Subsystem Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "ACL",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by (system) (system_subsystem_health{subsystem=\"acl\", system=~\"$system\"} != 20)",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Config",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "avg by (system) (system_subsystem_health{subsystem=\"config\", system=~\"$system\"})",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Fans",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by (system) (system_subsystem_health{subsystem=\"fans\", system=~\"$system\"} != 20)",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "avg by (system) (system_subsystem_health{subsystem=\"io\", system=~\"$system\"} != 20)",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Management",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg by (system) (system_subsystem_health{subsystem=\"management\", system=~\"$system\"} != 20)",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Power Supplies",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "avg by (system) (system_subsystem_health{subsystem=\"psus\", system=~\"$system\"} != 20)",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Pumps",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "avg by (system) (system_subsystem_health{subsystem=\"pumps\", system=~\"$system\"} != 20)",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "VRM",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "avg by (system) (system_subsystem_health{subsystem=\"vrm\", system=~\"$system\"} != 20)",
     "legendFormat": "{{system}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Network Health",
   "type": "state-timeline",
   "description": "Ports that are flapping or aren't responding to pings (from CPingmesh).",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "min by (host, nic) (increase(pingmesh_server_pings_total{host=~\"$system\"}[5m]) == 0)\nunless on (host, nic)\n(pingmesh_server_healthy < 1)",
     "legendFormat": "{{nic}} Unreachable"
    },
    {
     "expr": "(increase(system_network_flap_count{system=~\"$system\"}[$__rate_interval]) >= bool 2) > 0",
     "legendFormat": "{{port}} Flapping"
    },
    {
     "expr": "min_over_time(system_network_health{system=~\"$system\"}[$__rate_interval]) == 0",
     "legendFormat": "{{port}} Down"
    }
   ]
  },
  { "title": "Water", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Facility Water Flow Rate",
   "type": "timeseries",
   "description": "INLET_FLOW_RATE",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "expr": "system_dev_stats{system=~\"$system\", category=\"Sensor\",type=\"flow_rate\",component=\"INLET_FLOW_RATE\"}",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Facility Water Input Temperature",
   "type": "timeseries",
   "description": "INLET_FLOW_TEMP",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "system_dev_stats{system=~\"$system\", category=\"Sensor\",type=\"temperature\",component=\"INLET_FLOW_TEMP\"}",
     "legendFormat": "{{system}}"
    }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Heat Exchanger Input Temperature",
   "type": "timeseries",
   "description": "ACL_HEX_IN",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "system_dev_stats{system=~\"$system\", category=\"Sensor\",type=\"temperature\",component=\"ACL_HEX_IN\"}",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Heat Exchanger Exit Temperature",
   "type": "timeseries",
   "description": "ACL_PUMP_OUT",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "system_dev_stats{system=~\"$system\", category=\"Sensor\",type=\"temperature\",component=\"ACL_PUMP_OUT\"}",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Heat Exchanger dT",
   "type": "timeseries",
   "description": "ACL_HEX_IN - ACL_PUMP_OUT",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "system_dev_stats{system=~\"$system\", category=\"Sensor\",type=\"temperature\",component=\"ACL_HEX_IN\"} - on (system) system_dev_stats{system=~\"$system\", category=\"Sensor\",type=\"temperature\",component=\"ACL_PUMP_OUT\"}",
     "legendFormat": "{{system}}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Input Power",
   "type": "timeseries",
   "description": "sum of PSUn_PIN",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "sum by (system) (system_dev_stats{system=~\"$system\", category=\"Sensor\",type=\"power\", component=~\"PSU[0-9]+_PIN\"})",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Counters Exceeding Thresholds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Counters Exceeding Thresholds",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (system) (max_over_time(system_dev_stats{system=~\"$system\", component=~\"^GLTCH_(EXCUR|TRANS).*\"}[$__range]) > $glitch_thresh)",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (system) (max_over_time(system_dev_stats{system=~\"$system\", component=~\"^VDDC.*_IOUT\"}[$__range]) > $current_thresh)",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (system) (max_over_time(system_dev_stats{system=~\"$system\", component=~\"^VDDC_ASIC.*\"}[$__range]) > $voltage_thresh)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (system) (max_over_time(system_dev_stats{system=~\"$system\", component=~\"^GLTCH_(EXCUR|TRANS).*\"}[$__range]) > $glitch_thresh)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (system) (max_over_time(system_dev_stats{system=~\"$system\", component=~\"^VDDC.*_IOUT\"}[$__range]) > $current_thresh)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (system) (max_over_time(system_dev_stats{system=~\"$system\", component=~\"^VDDC_ASIC.*\"}[$__range]) > $voltage_thresh)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Timeline of High Counter Events",
     "type": "state-timeline",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "count by (system) (max_over_time(system_dev_stats{system=~\"$system\", component=~\"^GLTCH_(EXCUR|TRANS).*\"}[$__rate_interval]) > $glitch_thresh)",
       "legendFormat": "{{system}} - Glitch"
      },
      {
       "expr": "count by (system) (max_over_time(system_dev_stats{system=~\"$systems\", component=~\"^VDDC.*_IOUT\"}[$__rate_interval]) > $current_thresh)",
       "legendFormat": "{{system}} - High Current"
      },
      {
       "expr": "count by (system) (max_over_time(system_dev_stats{system=~\"$systems\", component=~\"^VDDC_ASIC.*\"}[$__rate_interval]) > $voltage_thresh)",
       "legendFormat": "{{system}} - High Voltage"
      }
     ]
    },
    {
     "title": "Glitch Counter Timeline",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_dev_stats{system=~\"$system\", component=~\"^GLTCH_(EXCUR|TRANS).*\"} > $glitch_thresh",
       "legendFormat": "{{system}}/{{component}}"
      },
      { "expr": "$glitch_thresh", "legendFormat": "Error Threshold" }
     ]
    },
    {
     "title": "VDDC_IOUT > $current_thresh A",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "Amperes" } },
     "targets": [
      {
       "expr": "system_dev_stats{system=~\"$system\", component=~\"^VDDC.*_IOUT\"} > $current_thresh",
       "legendFormat": "{{system}}/{{component}}"
      },
      { "expr": "$current_thresh", "legendFormat": "Error Threshold" }
     ]
    },
    {
     "title": "VDDC_ASIC > $voltage_thresh V",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "Volts" } },
     "targets": [
      {
       "expr": "system_dev_stats{system=~\"$system\", component=~\"^VDDC_ASIC.*\"} > $voltage_thresh",
       "legendFormat": "{{system}}/{{component}}"
      },
      { "expr": "$voltage_thresh", "legendFormat": "Error Threshold" }
     ]
    }
   ]
  }
 ]
}