raid_name: n0

swapdir: /n0/swapdir
swap_size: 134217728
ext_swap_size: 536870912
management_node: mgmt-node

k8s_scripts:
  - script.sh
  - remove-kube.sh
  - config.yaml
  - swap.sh
  - nic.sh
  - accept-keys.sh
