/*
Copyright 2022 Cerebras Systems, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "cerebras.com/job-operator/apis/system/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SystemLister helps list Systems.
// All objects returned here must be treated as read-only.
type SystemLister interface {
	// List lists all Systems in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.System, err error)
	// Get retrieves the System from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.System, error)
	SystemListerExpansion
}

// systemLister implements the SystemLister interface.
type systemLister struct {
	indexer cache.Indexer
}

// NewSystemLister returns a new SystemLister.
func NewSystemLister(indexer cache.Indexer) SystemLister {
	return &systemLister{indexer: indexer}
}

// List lists all Systems in the indexer.
func (s *systemLister) List(selector labels.Selector) (ret []*v1.System, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.System))
	})
	return ret, err
}

// Get retrieves the System from the index for a given name.
func (s *systemLister) Get(name string) (*v1.System, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("system"), name)
	}
	return obj.(*v1.System), nil
}
