# Fix the deprecated links in /etc/yum.repo.d/kubernetes.repo
# Without the fix, dnf will fail
- name: Check existence of kubernetes.repo file
  ansible.builtin.stat:
    path: /etc/yum.repos.d/kubernetes.repo
  register: k8s_repo

- name: Check existence of deprecated link
  ansible.builtin.shell:
    cmd: grep -c 'packages.cloud.google.com' {{ k8s_repo.stat.path }} || true
  register: has_deprecated_links
  when: k8s_repo.stat.exists

- name: Fix deprecated kubernetes.repo file
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../templates/kubernetes.repo"
    dest: "{{ k8s_repo.stat.path }}"
  when: k8s_repo.stat.exists and has_deprecated_links.stdout != "0"
