# Reboot nodes and wait until k8s node status is ready
- name: Reboot node
  ansible.builtin.reboot:
    msg: "Reboot with ansible..."
    # Sleep between 0 and 10 seconds, then launch 'systemctl reboot' to reboot
    # the node.  After launching the command, wait for 240 seconds, and then
    # check if the ssh connection is back every 15 seconds.  Error out if the
    # ssh connection is not back within 1200 seconds.
    # Note that from experiments, the pre_reboot_delay attribute is ignored if
    # the reboot_command attribute is defined, hence move the sleep time into
    # the reboot_command attribute.
    reboot_command: sleep {{ 10 | random }} ; systemctl reboot
    post_reboot_delay: 240
    connect_timeout: 15
    reboot_timeout: 1200

- name: Wait until nodes are ready
  ansible.builtin.command: kubectl get nodes {{ inventory_hostname }} -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}'
  register: status
  # Wait up to 5 mins
  retries: 10
  delay: 30
  until: status.stdout == 'True'
  delegate_to: "{{ control_plane_node | default(null, True) }}"
  when:
    - k8s_running

