/*
Copyright 2022 Cerebras Systems, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	resourcelockv1 "cerebras.com/job-operator/apis/resourcelock/v1"
	versioned "cerebras.com/job-operator/client-resourcelock/clientset/versioned"
	internalinterfaces "cerebras.com/job-operator/client-resourcelock/informers/externalversions/internalinterfaces"
	v1 "cerebras.com/job-operator/client-resourcelock/listers/resourcelock/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ResourceLockInformer provides access to a shared informer and lister for
// ResourceLocks.
type ResourceLockInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ResourceLockLister
}

type resourceLockInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewResourceLockInformer constructs a new informer for ResourceLock type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewResourceLockInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredResourceLockInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredResourceLockInformer constructs a new informer for ResourceLock type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredResourceLockInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ResourcelockV1().ResourceLocks(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ResourcelockV1().ResourceLocks(namespace).Watch(context.TODO(), options)
			},
		},
		&resourcelockv1.ResourceLock{},
		resyncPeriod,
		indexers,
	)
}

func (f *resourceLockInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredResourceLockInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *resourceLockInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&resourcelockv1.ResourceLock{}, f.defaultInformer)
}

func (f *resourceLockInformer) Lister() v1.ResourceLockLister {
	return v1.NewResourceLockLister(f.Informer().GetIndexer())
}
