# https://github.com/kubernetes/kubeadm/blob/b7cce64b712c209813b90c8c861ff3e4a93e0e35/docs/ha-considerations.md#option-2-run-the-services-as-static-pods
apiVersion: v1
kind: Pod
metadata:
  name: haproxy
  namespace: kube-system
  labels:
    component: haproxy
spec:
  containers:
    - image: registry.local/ecr-public/docker/library/haproxy:2.8
      name: haproxy
      resources:
        requests:
          memory: 500Mi
      livenessProbe:
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 6
        httpGet:
          host: 127.0.0.1
          path: /readyz
          port: 8443
          scheme: HTTPS
      volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          name: haproxyconf
          readOnly: true
  hostNetwork: true
  priorityClassName: system-node-critical
  volumes:
    - hostPath:
        path: /etc/haproxy/haproxy.cfg
      name: haproxyconf
