apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog
          ports:
            - containerPort: 1025  # SMTP port
            - containerPort: 8025  # Web UI
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: prometheus
spec:
  selector:
    app: mailhog
  type: NodePort
  ports:
    - name: smtp
      port: 1025
      nodePort: 31025
    - name: web
      port: 8025
      nodePort: 31080