apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockserver
  namespace: prometheus
  labels:
    app: mockserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockserver
  template:
    metadata:
      labels:
        app: mockserver
    spec:
      containers:
        - name: mockserver
          image: mockserver/mockserver:latest
          ports:
            - containerPort: 3180
          env:
            - name: MOCKSERVER_SERVER_PORT
              value: "3180"
            - name: MOCKSERVER_LOG_LEVEL
              value: "INFO"
            - name: MOCKSERVER_DISABLE_SYSTEM_OUT
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: mockserver
  namespace: prometheus
  labels:
    app: mockserver
spec:
  type: NodePort
  selector:
    app: mockserver
  ports:
    - protocol: TCP
      port: 3180
      nodePort: 31180