# Default values for debugviz-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: job-operator
system_namespace: job-operator

imagePullSecrets:
  - name: regcred

name: debugviz-server
image: ""
replicas: 0
port: 8105
debugVolume: {}
debugMount: {}
nfsWorkdirVolume: {}
nfsWorkdirMount: {}
path: ""
# initial memory and cpu limit for debugviz
# we will tweak the limit when we understand the usage more
resources:
  limits:
    memory: 4Gi
    cpu: 200m

ingress:
  className: nginx
  debugVizHosts:
    - debugviz-server.cerebrassc.local
  tls:
    secretName: debugviz-server-grpc-secret

nodeSelector:
  k8s.cerebras.com/node-role-management: ""

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: debugviz-server
          topologyKey: kubernetes.io/hostname
        weight: 100

tolerations:
  - effect: NoSchedule
    key: "node-role.kubernetes.io/master"
    operator: Equal
    value: ""
  - effect: NoSchedule
    key: "node-role.kubernetes.io/control-plane"
    operator: Equal
    value: ""
