# Used in kind e2e tests after envsubst the kind name.
kind: cluster-configuration
name: ${KIND_CLUSTER_NAME}
properties: {}
systems:
  - name: cs-0
    type: cs2
    managementAddress: 127.0.1.1
    controlAddress: 172.1.1.1:9000
  - name: cs-1
    type: cs2
    managementAddress: 127.0.2.1
    controlAddress: 172.1.2.1:9000
  - name: cs-2
    type: cs2
    managementAddress: 127.0.3.1
    controlAddress: 172.1.3.1:9000
  - name: cs-3
    type: cs2
    managementAddress: 127.0.4.1
    controlAddress: 172.1.4.1:9000
nodes:
  - name: ${KIND_CLUSTER_NAME}-control-plane
    role: "any"
    properties:
      group: nodegroup0
      generateBrNICs: "true"
groups:
  - name: nodegroup0