{{- $isSystemNamespace := eq .Values.namespace .Values.system_namespace -}}
{{- $rbacPrefix := printf "%s-" .Values.namespace -}}

{{- if not $isSystemNamespace }}
---
# Generate Role and RoleBinding for a user namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-server-ns-role
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cluster-server.labels" . | nindent 4 }}
rules:
  {{- include "cluster-server-editor-ns-role.rules" . | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-server-ns-rolebinding
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cluster-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-server-ns-role
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-server.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
---
# Generate ClusterRole and ClusterRoleBinding for a user namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $rbacPrefix }}cluster-server-cluster-role
  labels:
    {{- include "cluster-server.labels" . | nindent 4 }}
rules:
  {{- include "cluster-server-viewer-cluster-role.rules" . | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $rbacPrefix }}cluster-server-cluster-rolebinding
  labels:
    {{- include "cluster-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $rbacPrefix }}cluster-server-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-server.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
---
{{- end }}