{{- $isSystemNamespace := eq .Values.namespace .Values.system_namespace -}}

{{ if and $isSystemNamespace .Values.metrics.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: cluster-server
  name: cluster-server-metrics-monitor
  namespace: prometheus
spec:
  endpoints:
    - path: /metrics
      port: http
      interval: 10s
  selector:
    matchLabels:
      app.kubernetes.io/name: cluster-server
  namespaceSelector:
    any: true
---
{{ end }}