apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-server.fullname" . }}
  labels:
    {{- include "cluster-server.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: grpc
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "cluster-server.selectorLabels" . | nindent 4 }}