{{- $rbacPrefix := printf "%s-" .Values.namespace -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $rbacPrefix }}prometheus-system-secrets-access
  annotations:
  {{- if .Values.systemUpdate }}
    system-update: "true"
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["system-credential"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $rbacPrefix }}prometheus-system-secrets-access-binding
roleRef:
  kind: ClusterRole
  name: {{ $rbacPrefix }}prometheus-system-secrets-access
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: system-client-service-account
    namespace: {{ .Values.namespace }}