apiVersion: v1
kind: ConfigMap
metadata:
  name: whereabouts-config
  namespace: kube-system
  annotations:
    kubernetes.io/description: |
      Configmap containing user customizable cronjob schedule
data:
  cron-expression: "0 */1 * * *"
