apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "whereabouts.fullname" . }}
  {{- include "whereabouts.namespace" . | nindent 2 }}
  labels:
    {{- include "whereabouts.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: whereabouts
      {{- include "whereabouts.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      labels:
        name: whereabouts
        {{- include "whereabouts.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 3
      hostNetwork: true
      priorityClassName: system-node-critical
      serviceAccountName: {{ include "whereabouts.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ "/bin/sh" ]
        args:
        - -c
        - >
          SLEEP=FALSE source /install-cni.sh && /token-watcher.sh
        env:
        - name: WHEREABOUTS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: "100m"
          limits:
            memory: "100Mi"
        volumeMounts:
        - name: host-cnibin
          mountPath: /host/opt/cni/bin
        - name: host-cni-net-dir
          mountPath: /host/etc/cni/net.d
        - name: host-nad-dir
          mountPath: /host/etc/cni/multus/net.d
      volumes:
      - name: host-cnibin
        hostPath:
          path: /opt/cni/bin
      - name: host-cni-net-dir
        hostPath:
          path: /etc/cni/net.d
      - name: host-nad-dir
        hostPath:
          path: /etc/cni/multus/net.d/
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
