apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whereabouts.fullname" . }}-operator
  {{- include "whereabouts.namespace" . | nindent 2 }}
  labels:
    {{- include "whereabouts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      name: whereabouts
      {{- include "whereabouts.operatorSelectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config_map.yaml") . | sha256sum }}
      labels:
        name: whereabouts
        {{- include "whereabouts.operatorSelectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10
      priorityClassName: system-node-critical
      serviceAccountName: {{ include "whereabouts.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ "/bin/sh" ]
        args:
        - -c
        - >
          /ip-control-loop -timeout=900 -log-level=debug
        env:
        - name: WHEREABOUTS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_CLIENT_QPS
          value: "{{ .Values.k8sClientRateLimit.qps }}"
        - name: KUBE_CLIENT_BURST
          value: "{{ .Values.k8sClientRateLimit.burst }}"
        - name: CNI_CONF_DIR
          value: /host/etc/cni/net.d
        - name: WHEREABOUTS_KUBECONFIG_FILE_HOST
          value: /host/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig
        - name: SCHEDULE_TYPE
          value: random
        - name: PROM_METRICS_PORT
          value: "9001"
        ports:
        - containerPort: 9001
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          # TODO: SW-130018
          # leaving limits unset as the whereabouts cron activities can burst mem usage
          # when there's a large amount of orphaned ipreservations
        volumeMounts:
        - name: host-cni-net-dir
          mountPath: /host/etc/cni/net.d
        - name: host-nad-dir
          mountPath: /host/etc/cni/multus/net.d
        - name: var-log
          mountPath: /var/log
        - name: cron-scheduler-configmap
          mountPath: /cron-schedule
      volumes:
      - name: host-cni-net-dir
        hostPath:
          path: /etc/cni/net.d
      - name: host-nad-dir
        hostPath:
          path: /etc/cni/multus/net.d/
      - name: var-log
        hostPath:
          path: /var/log
      - name: cron-scheduler-configmap
        configMap:
          name: "whereabouts-config"
          defaultMode: 0744
          items:
          - key: "cron-expression"
            path: "config"
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
