apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "whereabouts.fullname" . }}
  {{- include "whereabouts.namespace" . | nindent 2 }}
  labels:
    {{- include "whereabouts.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "whereabouts.operatorSelectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
      - {{ include "whereabouts.namespaceName" . | quote }}
