# permissions for end users to edit sessions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacereservation-editor-role
rules:
- apiGroups:
  - jobs.cerebras.com
  resources:
  - namespacereservation
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobs.cerebras.com
  resources:
  - namespacereservation/status
  verbs:
  - get
