# permissions for end users to view sessions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacereservation-viewer-role
rules:
- apiGroups:
  - jobs.cerebras.com
  resources:
  - namespacereservations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jobs.cerebras.com
  resources:
  - namespacereservations/status
  verbs:
  - get
