---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - delete
  - deletecollection
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - jobs.cerebras.com
  resources:
  - namespacereservations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobs.cerebras.com
  resources:
  - namespacereservations/finalizers
  verbs:
  - update
- apiGroups:
  - jobs.cerebras.com
  resources:
  - namespacereservations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jobs.cerebras.com
  resources:
  - resourcelocks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobs.cerebras.com
  resources:
  - resourcelocks/finalizers
  verbs:
  - update
- apiGroups:
  - jobs.cerebras.com
  resources:
  - resourcelocks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jobs.cerebras.com
  resources:
  - systems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobs.cerebras.com
  resources:
  - systems/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jobs.cerebras.com
  resources:
  - wsjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobs.cerebras.com
  resources:
  - wsjobs/finalizers
  verbs:
  - update
- apiGroups:
  - jobs.cerebras.com
  resources:
  - wsjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
