- name: Update k8s cluster configmap
  delegate_to: localhost
  command: >
    bash -c "kubectl create cm cluster -njob-operator --from-file=clusterConfiguration.yaml={{ src_cluster_yaml }} --dry-run=client -o yaml | kubectl replace -f-"
  run_once: true

- name: Update k8s nvme-targets configmap
  delegate_to: localhost
  command: >
    bash -c "kubectl create cm nvme-targets -njob-operator --from-file=targets.yaml={{ src_targets_yaml }} --dry-run=client -o yaml | kubectl replace -f-"
  run_once: true
