apiVersion: v1
kind: Service
metadata:
  name: alert-router
  namespace: prometheus
spec:
  type: ClusterIP 
  ports:
  - port: 8080 
    targetPort: 8080 
    protocol: TCP
    name: http-metrics 
  selector:
    app: alert-router
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-router
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-router
  template:
    metadata:
      labels:
        app: alert-router
    spec:
      containers:
      - name: alert-router
        image: registry.local/alert-router:${ALERT_ROUTER_TAG}
        resources:
          requests:
            cpu: "100m"      # 0.1 CPU core
            memory: "256Mi"  # 256MB memory
          limits:
            memory: "256Mi"  # 256MB memory
        ports:
        - containerPort: 8080 
        env:
        - name: OPERATOR_CONTACTS_PATH
          value: /etc/operator-contact-config/config
        - name: ALERT_RULE_MAPPINGS_PATH
          value: /etc/alert-classification/alert-classification.yaml
        - name: SMTP_HOST
          value: email-smtp.us-west-2.amazonaws.com
        - name: SMTP_PORT
          value: "587"
        # SMTP credentials are read from the smtp-credentials secret
        - name: CLUSTER_NAME
          value: ${CLUSTER_NAME}
        - name: CLUSTER_DOMAIN_NAME
          value: ${CLUSTER_DOMAIN_NAME}
        volumeMounts:
        - name: operator-contact-config
          mountPath: /etc/operator-contact-config
        - name: alert-classification-config
          mountPath: /etc/alert-classification
        - name: logs
          mountPath: /var/log/app
        - name: smtp-credentials
          mountPath: /etc/smtp-credentials
          readOnly: true
      nodeSelector:
        "node-role.kubernetes.io/control-plane": ""
      tolerations:
        - effect: NoSchedule
          key: "node-role.kubernetes.io/master"
          operator: Exists
        - effect: NoSchedule
          key: "node-role.kubernetes.io/control-plane"
          operator: Exists
      volumes:
      - name: operator-contact-config
        secret:
          secretName: cluster-operator-contacts
      - name: alert-classification-config
        configMap:
          name: alert-classification
      - name: logs
        hostPath:
          path: /n0/cluster-mgmt/alert-router
          type: DirectoryOrCreate
      - name: smtp-credentials
        secret:
          secretName: smtp-credentials
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alert-router
  namespace: prometheus
  labels:
    app: alert-router
spec:
  selector:
    matchLabels:
      app: alert-router
  namespaceSelector:
    matchNames:
      - prometheus
  endpoints:
    - port: http-metrics
      interval: 30s