# This ClusterRole defines read-only permissions for wsjobs resources
# in the jobs.cerebras.com API group
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-wsjobs-reader
rules:
- apiGroups: ["jobs.cerebras.com"]
  resources: ["wsjobs"]
  verbs: ["get", "list", "watch"]
---
# This ClusterRoleBinding grants the default service account in the prometheus namespace
# access to the prometheus-wsjobs-reader ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-wsjobs-access
subjects:
- kind: ServiceAccount
  name: default
  namespace: prometheus
roleRef:
  kind: ClusterRole
  name: prometheus-wsjobs-reader
  apiGroup: rbac.authorization.k8s.io