/*
Copyright 2022 Cerebras Systems, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "cerebras.com/job-operator/apis/system/v1"
	scheme "cerebras.com/job-operator/client-system/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SystemsGetter has a method to return a SystemInterface.
// A group's client should implement this interface.
type SystemsGetter interface {
	Systems() SystemInterface
}

// SystemInterface has methods to work with System resources.
type SystemInterface interface {
	Create(ctx context.Context, system *v1.System, opts metav1.CreateOptions) (*v1.System, error)
	Update(ctx context.Context, system *v1.System, opts metav1.UpdateOptions) (*v1.System, error)
	UpdateStatus(ctx context.Context, system *v1.System, opts metav1.UpdateOptions) (*v1.System, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.System, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.SystemList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.System, err error)
	SystemExpansion
}

// systems implements SystemInterface
type systems struct {
	client rest.Interface
}

// newSystems returns a Systems
func newSystems(c *SystemV1Client) *systems {
	return &systems{
		client: c.RESTClient(),
	}
}

// Get takes name of the system, and returns the corresponding system object, and an error if there is any.
func (c *systems) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.System, err error) {
	result = &v1.System{}
	err = c.client.Get().
		Resource("systems").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Systems that match those selectors.
func (c *systems) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SystemList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SystemList{}
	err = c.client.Get().
		Resource("systems").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested systems.
func (c *systems) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("systems").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a system and creates it.  Returns the server's representation of the system, and an error, if there is any.
func (c *systems) Create(ctx context.Context, system *v1.System, opts metav1.CreateOptions) (result *v1.System, err error) {
	result = &v1.System{}
	err = c.client.Post().
		Resource("systems").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(system).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a system and updates it. Returns the server's representation of the system, and an error, if there is any.
func (c *systems) Update(ctx context.Context, system *v1.System, opts metav1.UpdateOptions) (result *v1.System, err error) {
	result = &v1.System{}
	err = c.client.Put().
		Resource("systems").
		Name(system.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(system).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *systems) UpdateStatus(ctx context.Context, system *v1.System, opts metav1.UpdateOptions) (result *v1.System, err error) {
	result = &v1.System{}
	err = c.client.Put().
		Resource("systems").
		Name(system.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(system).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the system and deletes it. Returns an error if one occurs.
func (c *systems) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("systems").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *systems) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("systems").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched system.
func (c *systems) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.System, err error) {
	result = &v1.System{}
	err = c.client.Patch(pt).
		Resource("systems").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
