- name: Validate kea configuration
  ansible.builtin.shell: kea-dhcp4 -T {{ dhcp_config_dir }}/kea-dhcp4.conf

- name: Check if kea-dhcp4 service status
  ansible.builtin.systemd:
    name: kea-dhcp4
  register: kea4_status

- name: Back up existing kea-dhcp4.conf if kea is running and backup does not exist
  ansible.builtin.copy:
    src: /etc/kea/kea-dhcp4.conf
    dest: /etc/kea/kea-dhcp4.conf.backup
    remote_src: yes
  when:
    - kea4_status.status.ActiveState == 'active'

- name: Copy kea configuration
  ansible.builtin.copy:
    src: "{{ dhcp_config_dir }}/kea-dhcp4.conf"
    dest: /etc/kea/
    owner: kea
    group: kea
    mode: '0644'
  register: config_changed

- name: Enable and start kea-dhcp4 service
  ansible.builtin.systemd:
    name: kea-dhcp4
    state: "{{ 'restarted' if config_changed.changed else 'started' }}"
    enabled: yes

# Note: seen instances where even if the configuration check passes, some runtime checks fail. Therefore, check
# the status of the dhcp server after giving it a little time to boot up
- name: Give some time for boot up
  ansible.builtin.pause:
    seconds: 2

- name: Ensure kea-dhcp4 service is running
  ansible.builtin.systemd:
    name: kea-dhcp4
    state: started
    enabled: yes
  register: kea_status

- name: Fail if kea-dhcp4 is not running
  ansible.builtin.fail:
    msg: "kea-dhcp4 service is not running after restart. Old config is at /etc/kea/kea-dhcp4.conf.backup. Check 'journalctl -u kea-dhcp4'."
  when: not kea_status.status.ActiveState == 'active'

- name: Remove kea-dhcp4.conf backup if kea is running
  ansible.builtin.file:
    path: /etc/kea/kea-dhcp4.conf.backup
    state: absent