apiVersion: v1
kind: Service
metadata:
  labels:
    component: haproxy
  name: haproxy
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 8405
      protocol: TCP
      targetPort: 8405
  selector:
    component: haproxy
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: haproxy
  namespace: kube-system
  labels:
    component: haproxy
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      component: haproxy
  endpoints:
    - port: http-metrics
      interval: 30s
