apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-pv
  labels:
    app.kubernetes.io/name: prometheus
spec:
  capacity:
    storage: 50Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # required
  hostPath:
    path: /n0/cluster-mgmt/prom
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    app.kubernetes.io/name: grafana
spec:
  capacity:
    storage: 5Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # required
  hostPath:
    path: "/n0/cluster-mgmt/grafana"
    type: DirectoryOrCreate
