prometheus:
  prometheusSpec:
    remoteWrite:
    - url: PROM_REMOTE_WRITE_DEST
      tlsConfig:
        insecureSkipVerify: true
      writeRelabelConfigs:
      # only send specific metrics with remote-write
      - sourceLabels: ['__name__']
        regex: '(wsjob_system_grant)|(system_label)|(wsjob_annotation)'
        action: 'keep'
      - targetLabel: 'cluster'
        replacement: CLUSTER_NAME
        action: 'replace'
