prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          selector:
            matchLabels:
              app.kubernetes.io/name: prometheus

grafana:
  deploymentStrategy:
    type: Recreate
  persistence:
    type: pvc
    enabled: true
    storageClassName: standard
    selectorLabels:
      app.kubernetes.io/name: grafana
    accessModes:
      - ReadWriteOnce
    size: 5Gi
