# Note nodeSelector does not do anything, since its not used in the deployment template. It's for test compatibilty, to remove as part of CS-675
nodeSelector:
  "k8s.cerebras.com/node-role-management": ""
resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi
serverLogMountPath: /opt/cerebras/log
