- name: Deploy chrony.conf template
  template:
    src: templates/chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Restart chronyd
  service:
    name: chronyd
    state: restarted
