- name: Copy Rocky8 kickstart
  template:
    src: ks.cfg
    dest: "{{ http_dir }}/Rocky8"

- name: Copy httpd config
  template:
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf

- name: Enable and start httpd
  systemd: name=httpd state=restarted enabled=yes

- name: Ensure /var/repo directory exists
  file:
    path: /var/repo
    state: directory
  tags: dnf

- name: Ensure /var/www/html/repo is a symlink to /var/repo to deliver rpm packages
  file:
    src: /var/repo
    dest: /var/www/html/repo
    state: link
  tags: dnf

- name: Check if patch tarball exists
  stat:
    path: /opt/cerebras/packages/Cerebras-patches.tgz
  register: patch_exists
  tags: dnf

- name: Populate local rpm repository
  shell:
    cmd: |
      tar zxf /opt/cerebras/packages/Cerebras-patches.tgz
    chdir: /var/repo
  when: patch_exists.stat.exists
  tags: dnf

- import_tasks: chrony.yml