/*
Copyright 2022 Cerebras Systems, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	namespacev1 "cerebras.com/job-operator/apis/namespace/v1"
	versioned "cerebras.com/job-operator/client-namespace/clientset/versioned"
	internalinterfaces "cerebras.com/job-operator/client-namespace/informers/externalversions/internalinterfaces"
	v1 "cerebras.com/job-operator/client-namespace/listers/namespace/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NamespaceReservationInformer provides access to a shared informer and lister for
// NamespaceReservations.
type NamespaceReservationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.NamespaceReservationLister
}

type namespaceReservationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewNamespaceReservationInformer constructs a new informer for NamespaceReservation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNamespaceReservationInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNamespaceReservationInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredNamespaceReservationInformer constructs a new informer for NamespaceReservation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNamespaceReservationInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NamespaceV1().NamespaceReservations().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NamespaceV1().NamespaceReservations().Watch(context.TODO(), options)
			},
		},
		&namespacev1.NamespaceReservation{},
		resyncPeriod,
		indexers,
	)
}

func (f *namespaceReservationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNamespaceReservationInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *namespaceReservationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&namespacev1.NamespaceReservation{}, f.defaultInformer)
}

func (f *namespaceReservationInformer) Lister() v1.NamespaceReservationLister {
	return v1.NewNamespaceReservationLister(f.Informer().GetIndexer())
}
