apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-claim
  namespace: job-operator
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi