/*
Copyright 2022 Cerebras Systems, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "cerebras.com/job-operator/apis/ws/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWSJobs implements WSJobInterface
type FakeWSJobs struct {
	Fake *FakeWsV1
	ns   string
}

var wsjobsResource = v1.SchemeGroupVersion.WithResource("wsjobs")

var wsjobsKind = v1.SchemeGroupVersion.WithKind("WSJob")

// Get takes name of the wSJob, and returns the corresponding wSJob object, and an error if there is any.
func (c *FakeWSJobs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.WSJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(wsjobsResource, c.ns, name), &v1.WSJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.WSJob), err
}

// List takes label and field selectors, and returns the list of WSJobs that match those selectors.
func (c *FakeWSJobs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.WSJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(wsjobsResource, wsjobsKind, c.ns, opts), &v1.WSJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.WSJobList{ListMeta: obj.(*v1.WSJobList).ListMeta}
	for _, item := range obj.(*v1.WSJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested wSJobs.
func (c *FakeWSJobs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(wsjobsResource, c.ns, opts))

}

// Create takes the representation of a wSJob and creates it.  Returns the server's representation of the wSJob, and an error, if there is any.
func (c *FakeWSJobs) Create(ctx context.Context, wSJob *v1.WSJob, opts metav1.CreateOptions) (result *v1.WSJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(wsjobsResource, c.ns, wSJob), &v1.WSJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.WSJob), err
}

// Update takes the representation of a wSJob and updates it. Returns the server's representation of the wSJob, and an error, if there is any.
func (c *FakeWSJobs) Update(ctx context.Context, wSJob *v1.WSJob, opts metav1.UpdateOptions) (result *v1.WSJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(wsjobsResource, c.ns, wSJob), &v1.WSJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.WSJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWSJobs) UpdateStatus(ctx context.Context, wSJob *v1.WSJob, opts metav1.UpdateOptions) (*v1.WSJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(wsjobsResource, "status", c.ns, wSJob), &v1.WSJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.WSJob), err
}

// Delete takes name of the wSJob and deletes it. Returns an error if one occurs.
func (c *FakeWSJobs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(wsjobsResource, c.ns, name, opts), &v1.WSJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWSJobs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(wsjobsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.WSJobList{})
	return err
}

// Patch applies the patch and returns the patched wSJob.
func (c *FakeWSJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.WSJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(wsjobsResource, c.ns, name, pt, data, subresources...), &v1.WSJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.WSJob), err
}
