{
 "title": "ML User",
 "tags": [ "cluster-mgmt" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(namespace_reservation, namespace)"
   },
   {
    "name": "model",
    "query": "label_values(wsjob_annotation, labels_k8s_cerebras_com_Model)"
   },
   {
    "name": "job_type",
    "query": "label_values(wsjob_annotation, job_type)"
   },
   {
    "name": "wsjob",
    "query": {
     "query": "label_values(wsjob_annotation{labels_k8s_cerebras_com_Model=~\"$model\", job_type=~\"$job_type\", namespace=~\"$namespace\", start!=\"\", end=\"\"},name)"
    }
   },
   {
    "name": "replica_type",
    "query": "label_values(kube_pod_info{created_by_name=\"$wsjob\", pod=~\"$wsjob-.*\", pod_ip!=\"\"}, pod)"
   },
   {
    "name": "replica_id",
    "query": "label_values(kube_pod_info{created_by_name=\"$wsjob\", pod=~\"$wsjob-$replica_type.*\", pod_ip!=\"\"}, pod)"
   },
   {
    "name": "nodegroup",
    "query": {
     "query": "label_values(wsjob_nodegroup_grant{name=\"$wsjob\"},group)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of CS2s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (name, labels_k8s_cerebras_com_Model) (group by (name, system) (wsjob_system_grant{system =~\".*\"})) * on (name) group_left(labels_k8s_cerebras_com_Model) group by(name, labels_k8s_cerebras_com_Model) \n(wsjob_annotation{name=\"$wsjob\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Systems",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "max(wsjob_system_grant{name=\"$wsjob\"}) by (system)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CS2 Hours Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum(group(wsjob_system_grant{name=\"$wsjob\"}) by (system)) or sum(sum(system_label*0) by (system)))[$__range:$__rate_interval]) * (${__to:date:seconds}-${__from:date:seconds})/3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Start (UTC)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wsjob_annotation{name=\"$wsjob\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job End (UTC)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wsjob_annotation{name=\"$wsjob\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (WSS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"$wsjob-.*\", container!=\"\", image!=\"\"}) by (pod, node)",
     "legendFormat": "{{node}}/{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$wsjob-.*\", container=~\".+\"}) by (pod, node)",
     "legendFormat": "{{node}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Egress Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"$wsjob-.*\", interface=~\"e.*|net.*\"}[$__rate_interval])) by (pod, interface)",
     "legendFormat": "{{pod}}/{{interface}}"
    }
   ]
  },
  {
   "title": "Ingress Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"$wsjob-.*\", interface=~\"e.*|net.*\"}[$__rate_interval])) by (pod, interface)",
     "legendFormat": "{{pod}}/{{interface}}"
    }
   ]
  },
  {
   "title": "server summary by replica type, all nodegroups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "description": "The line represents the average CPU load of all nodes of that node type\nThe shaded area indicates the min and max CPU load% of that node type",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container!=\"\", pod=~\"$wsjob-.*-[0-9]+\"}, \"role\", \"$1\", \"pod\", \"wsjob-.+-(.+)-.*\")) by (role)",
     "legendFormat": "{{role}}"
    },
    {
     "expr": "min(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container!=\"\", pod=~\"$wsjob-.*-[0-9]+\"}, \"role\", \"$1\", \"pod\", \"wsjob-.+-(.+)-.*\")) by (role)",
     "legendFormat": "{{role}}_min"
    },
    {
     "expr": "max(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container!=\"\", pod=~\"$wsjob-.*-[0-9]+\"}, \"role\", \"$1\", \"pod\", \"wsjob-.+-(.+)-.*\")) by (role)",
     "legendFormat": "{{role}}_max"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Line represents the average mem usage for all nodes of that node type\nShaded area of that color marks the min and max use% of that node type",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(label_replace(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"$wsjob-.*-[0-9]+\", container!=\"\", image!=\"\"}, \"role\", \"$1\", \"pod\", \"wsjob-.+-(.+)-.*\")) by (role)",
     "legendFormat": "{{role}}"
    },
    {
     "expr": "min(label_replace(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"$wsjob-.*-[0-9]+\", container!=\"\", image!=\"\"}, \"role\", \"$1\", \"pod\", \"wsjob-.+-(.+)-.*\")) by (role)",
     "legendFormat": "{{role}}_min"
    },
    {
     "expr": "max(label_replace(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"$wsjob-.*-[0-9]+\", container!=\"\", image!=\"\"}, \"role\", \"$1\", \"pod\", \"wsjob-.+-(.+)-.*\")) by (role)",
     "legendFormat": "{{role}}_max"
    }
   ]
  },
  {
   "title": "Net BW ingress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(label_replace(irate(container_network_receive_bytes_total{pod=~\"$wsjob-.*-[0-9]+\", interface=~\"e.*|net.*\"}[$__rate_interval]), \"role\", \"$1\", \"pod\", \"wsjob-.+-(.+)-.*\")) by (role)",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Net BW egress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(label_replace(irate(container_network_transmit_bytes_total{pod=~\"$wsjob-.*-[0-9]+\", interface=~\"e.*|net.*\"}[$__rate_interval]), \"role\", \"$1\", \"pod\", \"wsjob-.+-(.+)-.*\")) by (role)",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "server summary by replica type, $nodegroup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "repeat": "nodegroup",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU load",
     "type": "timeseries",
     "description": "The line represents the average CPU load of all nodes of that node type\nThe shaded area indicates the min and max CPU load% of that node type",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "avg(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container!=\"\", pod=~\"$wsjob-.*-[0-9]+\"} * on (node) group_left group by (node) (job_operator_node_role{group=\"$nodegroup\"}), \"role\", \"$1\", \"pod\", \"wsjob-.+-(.+)-.*\")) by (role)",
       "legendFormat": "{{role}}"
      },
      {
       "expr": "min(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container!=\"\", pod=~\"$wsjob-.*-[0-9]+\"} * on (node) group_left group by (node) (job_operator_node_role{group=\"$nodegroup\"}), \"role\", \"$1\", \"pod\", \"wsjob-.+-(.+)-.*\")) by (role)",
       "legendFormat": "{{role}}_min"
      },
      {
       "expr": "max(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container!=\"\", pod=~\"$wsjob-.*-[0-9]+\"} * on (node) group_left group by (node) (job_operator_node_role{group=\"$nodegroup\"}), \"role\", \"$1\", \"pod\", \"wsjob-.+-(.+)-.*\")) by (role)",
       "legendFormat": "{{role}}_max"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "description": "Line represents the average mem usage for all nodes of that node type\nShaded area of that color marks the min and max use% of that node type",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(label_replace(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"$wsjob-.*-[0-9]+\", container!=\"\", image!=\"\"} * on (node) group_left group by (node) (job_operator_node_role{group=\"$nodegroup\"}), \"role\", \"$1\", \"pod\", \"wsjob-.+-(.+)-.*\")) by (role)",
       "legendFormat": "{{role}}"
      },
      {
       "expr": "min(label_replace(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"$wsjob-.*-[0-9]+\", container!=\"\", image!=\"\"} * on (node) group_left group by (node) (job_operator_node_role{group=\"$nodegroup\"}), \"role\", \"$1\", \"pod\", \"wsjob-.+-(.+)-.*\")) by (role)",
       "legendFormat": "{{role}}_min"
      },
      {
       "expr": "max(label_replace(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"$wsjob-.*-[0-9]+\", container!=\"\", image!=\"\"} * on (node) group_left group by (node) (job_operator_node_role{group=\"$nodegroup\"}), \"role\", \"$1\", \"pod\", \"wsjob-.+-(.+)-.*\")) by (role)",
       "legendFormat": "{{role}}_max"
      }
     ]
    },
    {
     "title": "Net BW ingress",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(label_replace(irate(container_network_receive_bytes_total{pod=~\"$wsjob-.*-[0-9]+\", interface=~\"e.*|net.*\"}[$__rate_interval]) * on (node) group_left group by (node) (job_operator_node_role{group=\"$nodegroup\"}), \"role\", \"$1\", \"pod\", \"wsjob-.+-(.+)-.*\")) by (role)",
       "legendFormat": "{{role}}"
      }
     ]
    },
    {
     "title": "Net BW egress",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(label_replace(irate(container_network_transmit_bytes_total{pod=~\"$wsjob-.*-[0-9]+\", interface=~\"e.*|net.*\"}[$__rate_interval]) * on (node) group_left group by (node) (job_operator_node_role{group=\"$nodegroup\"}), \"role\", \"$1\", \"pod\", \"wsjob-.+-(.+)-.*\")) by (role)",
       "legendFormat": "{{role}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$replica_type view",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$replica_type-$replica_id Memory Usage (WSS)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24 },
     "repeat": "replica_id",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"$wsjob-$replica_type-$replica_id\", container!=\"\", image!=\"\"})",
       "legendFormat": "usage"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=~\"$wsjob-$replica_type-$replica_id\", resource=\"memory\"})",
       "legendFormat": "limit"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=~\"$wsjob-$replica_type-$replica_id\", resource=\"memory\"})",
       "legendFormat": "request"
      }
     ]
    },
    {
     "title": "$replica_type-$replica_id CPU Usage (Cores)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24 },
     "repeat": "replica_id",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$wsjob-$replica_type-$replica_id\"})",
       "legendFormat": "usage"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=~\"$wsjob-$replica_type-$replica_id\", resource=\"cpu\"})",
       "legendFormat": "limit"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=~\"$wsjob-$replica_type-$replica_id\", resource=\"cpu\"})",
       "legendFormat": "request"
      }
     ]
    },
    {
     "title": "$replica_type-$replica_id Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24 },
     "repeat": "replica_id",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"$wsjob-$replica_type-$replica_id\", interface=~\"e.*|net.*\"}[$__rate_interval])) by (pod, interface)",
       "legendFormat": "{{interface}} egress"
      },
      {
       "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"$wsjob-$replica_type-$replica_id\", interface=~\"e.*|net.*\"}[$__rate_interval])) by (pod, interface)",
       "legendFormat": "{{interface}} ingress"
      }
     ]
    }
   ]
  },
  {
   "title": "$replica_type assigned nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$replica_type-$replica_id node Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24 },
     "repeat": "replica_id",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(kube_node_status_capacity{resource=\"memory\"} * on (node) group_left group by (node) (kube_pod_info{pod=~\"$wsjob-$replica_type-$replica_id\", pod_ip!=\"\"})) by (node)",
       "legendFormat": "{{node}} total capactiy"
      },
      {
       "expr": "max(label_replace(node_memory_Cached_bytes,\"host_ip\", \"$1\", \"instance\", \"([^:]+):.*\") * on (host_ip) group_left(node) (kube_pod_info{pod=~\"$wsjob-$replica_type-$replica_id\", pod_ip!=\"\"})) by (node)",
       "legendFormat": "{{node}} cache used"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_cache{container!=\"\"} * on (node) group_left group by (node) (kube_pod_info{pod=~\"$wsjob-$replica_type-$replica_id\", pod_ip!=\"\"})) by (node)",
       "legendFormat": "{{node}} total container cache"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{container!=\"\"} * on (node) group_left group by (node) (kube_pod_info{pod=~\"$wsjob-$replica_type-$replica_id\", pod_ip!=\"\"})) by (pod, node)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "$replica_type-$replica_id node CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24 },
     "repeat": "replica_id",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(kube_node_status_capacity{resource=\"cpu\"} * on (node) group_left group by (node) (kube_pod_info{pod=~\"$wsjob-$replica_type-$replica_id\", pod_ip!=\"\"})) by (node)",
       "legendFormat": "{{node}} total capacity"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate * on (node) group_left group by (node) (kube_pod_info{pod=~\"$wsjob-$replica_type-$replica_id\", pod_ip!=\"\"})) by (pod, node)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "$replica_type-$replica_id node Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24 },
     "repeat": "replica_id",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{device=~\"e.*\"}[$__rate_interval]) * on (instance) group_left (node) label_replace(group by (node, host_ip) (kube_pod_info{pod=~\"$wsjob-$replica_type-$replica_id\", pod_ip!=\"\"}), \"instance\", \"$1:9100\", \"host_ip\", \"(.*)\")",
       "legendFormat": "{{node}}/{{device}} egress"
      },
      {
       "expr": "rate(node_network_receive_bytes_total{device=~\"e.*\"}[$__rate_interval]) * on (instance) group_left (node) label_replace(group by (node, host_ip) (kube_pod_info{pod=~\"$wsjob-$replica_type-$replica_id\", pod_ip!=\"\"}), \"instance\", \"$1:9100\", \"host_ip\", \"(.*)\")",
       "legendFormat": "{{node}}/{{device}} ingress"
      }
     ]
    },
    {
     "title": "$replica_type-$replica_id node Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24 },
     "repeat": "replica_id",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(label_replace((((node_filesystem_size_bytes{mountpoint=\"/n0\"}-node_filesystem_avail_bytes{mountpoint=\"/n0\"})/node_filesystem_size_bytes{mountpoint=\"/n0\"})*100), \"host_ip\", \"$1\", \"instance\", \"([^:]+):.*\") * on (host_ip) group_right kube_pod_info{pod=~\"$wsjob-$replica_type-$replica_id\", pod_ip!=\"\"}) by (node)",
       "legendFormat": "{{node}}:/n0"
      },
      {
       "expr": "max(label_replace((((node_filesystem_size_bytes{mountpoint=\"/\"}-node_filesystem_avail_bytes{mountpoint=\"/\"})/node_filesystem_size_bytes{mountpoint=\"/\"})*100), \"host_ip\", \"$1\", \"instance\", \"([^:]+):.*\") * on (host_ip) group_right kube_pod_info{pod=~\"$wsjob-$replica_type-$replica_id\", pod_ip!=\"\"}) by (node)",
       "legendFormat": "{{node}}:/"
      }
     ]
    }
   ]
  },
  {
   "title": "$replica_type iteration performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$replica_type-$replica_id iteration performance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24 },
     "repeat": "replica_id",
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "max(max_over_time({metric=\"rt_iter_perf\", replica_type=\"$replica_type\", replica_id=~\"$replica_id\", wsjob=\"$wsjob\"} |= `` | json | unwrap it [$__interval]))",
       "legendFormat": "iteration time"
      },
      {
       "expr": "max(max_over_time({metric=\"rt_iter_perf\", replica_type=\"$replica_type\", replica_id=~\"$replica_id\", wsjob=\"$wsjob\"} |= `` | json | unwrap ct [$__interval]))",
       "legendFormat": "cross-iteration time"
      },
      {
       "expr": "max(max_over_time({metric=\"rt_iter_perf\", replica_type=\"$replica_type\", replica_id=~\"$replica_id\", wsjob=\"$wsjob\"} |= `` | json | unwrap ft [$__interval]))",
       "legendFormat": "forward iteration time"
      },
      {
       "expr": "max(max_over_time({metric=\"rt_iter_perf\", replica_type=\"$replica_type\", replica_id=~\"$replica_id\", wsjob=\"$wsjob\"} |= `` | json | unwrap bt [$__interval]))",
       "legendFormat": "backward iteration time"
      }
     ]
    },
    {
     "title": "$replica_type-$replica_id input starvation",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24 },
     "repeat": "replica_id",
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "max by(metric) (max_over_time({metric=\"rt_iter_perf\", replica_type=\"$replica_type\", replica_id=~\"$replica_id\", wsjob=\"$wsjob\"} |= `` | json | unwrap is [$__interval]))",
       "legendFormat": "input starvation"
      }
     ]
    }
   ]
  }
 ]
}