{
 "title": "ML Admin",
 "tags": [ "cluster-mgmt" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(namespace_reservation,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CS2 Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CS2 Overall Status",
   "type": "stat",
   "description": "Systems status at the last timestamp of the selected range.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((max(system_overall_health) by (system)) * on (system) group_left group by (system) (system_label{namespace=~\"$namespace\"}) == bool 1) + sum((max(system_overall_health) by (system)) * on (system) group_left group by (system) (system_label{namespace=~\"$namespace\"}) == bool 2)",
     "legendFormat": "Available"
    },
    {
     "expr": "clamp_max(avg_over_time((sum((group(wsjob_system_grant{namespace=~\"$namespace\"}) by (system)) or (sum(0*system_label) by (system))) / count(group(system_label{namespace=~\"$namespace\"}) by (system)))[$__range:$__rate_interval]) *100, 100)",
     "legendFormat": "Utilized Percent"
    },
    {
     "expr": "avg_over_time((sum(group(wsjob_system_grant{namespace=~\"$namespace\"}) by (system)) or sum(sum(system_label*0) by (system)))[$__range:$__rate_interval]) * (${__to:date:seconds}-${__from:date:seconds})/3600",
     "legendFormat": "Utilized Hours"
    }
   ]
  },
  {
   "title": "CS2 Jobs Histogram",
   "type": "timeseries",
   "description": "(Max) Number of systems used by jobs.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (name, labels_k8s_cerebras_com_Model) (group by (name, system) (wsjob_system_grant{namespace=~\"$namespace\"})) * on (name) group_left(labels_k8s_cerebras_com_Model) group by(name, labels_k8s_cerebras_com_Model) (wsjob_annotation{job_type!=\"compile\", namespace=~\"$namespace\"})",
     "legendFormat": "{{labels_k8s_cerebras_com_Model}} / {{name}}"
    }
   ]
  },
  {
   "title": "CS2 Jobs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "wsjob_annotation{namespace=\"$namespace\", end=\"\"} or (wsjob_annotation{namespace=\"$namespace\"} unless (wsjob_annotation{namespace=\"$namespace\"} @ ${__from:date:seconds}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU load",
   "type": "timeseries",
   "description": "The line represents the average CPU load of all nodes of that node type\nThe shaded area indicates the min and max CPU load% of that node type",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "role_by_namespace:container_cpu_usage_seconds:avg{cs_namespace=\"$namespace\"}",
     "legendFormat": "{{role}}"
    },
    {
     "expr": "role_by_namespace:container_cpu_usage_seconds:min{cs_namespace=\"$namespace\"}",
     "legendFormat": "{{role}}_min"
    },
    {
     "expr": "role_by_namespace:container_cpu_usage_seconds:max{cs_namespace=\"$namespace\"}",
     "legendFormat": "{{role}}_max"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Line represents the average mem usage for all nodes of that node type\nShaded area of that color marks the min and max use% of that node type",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "role_by_namespace:node_memory_utilisation:avg_ratio{cs_namespace=\"$namespace\"}",
     "legendFormat": "{{role}}"
    },
    {
     "expr": "role_by_namespace:node_memory_utilisation:min_ratio{cs_namespace=\"$namespace\"}",
     "legendFormat": "{{role}}_min"
    },
    {
     "expr": "role_by_namespace:node_memory_utilisation:max_ratio{cs_namespace=\"$namespace\"}",
     "legendFormat": "{{role}}_max"
    }
   ]
  },
  {
   "title": "Total Network Ingress Rate by Role",
   "type": "timeseries",
   "description": "Total bytes per second ingressed per node by role in the given namespace",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(role_by_namespace:network_receive_bytes:sum{namespace=\"$namespace\"}[$__rate_interval])) by (role)",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Total Network Egress Rate by Role",
   "type": "timeseries",
   "description": "Total bytes per second egressed per node by role in the given namespace",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(role_by_namespace:network_transmit_bytes:sum{namespace=\"$namespace\"}[$__rate_interval])) by (role)",
     "legendFormat": "{{role}}"
    }
   ]
  }
 ]
}