{
 "title": "Cluster Session Browser",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Full Cluster Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Sessions (Sessions with systems)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (namespace) (namespace_reserved_system))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Stamps",
   "type": "stat",
   "description": "(stamps with systems)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (stamp) (stamp_config{system!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Systems - Full Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(system_overall_health) by (system) == bool 1) + sum(max(system_overall_health) by (system) == bool 2)",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(group((system_overall_health != 1) and (system_overall_health != 2) and (system_overall_health != -1)) by (system) or group by (system) (system_overall_health) != bool(1))",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "Nodes - Full Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(stamp_config{node!=\"\"})",
     "legendFormat": "total_nodes"
    },
    {
     "expr": "count(group by (node) ((kube_node_status_condition{node!=\"\", condition=~\"ClusterMgmt.*|ClusterDeploy.*|Csadm.*\", condition!~\".*NodeNIC.*\", condition!~\".*NodeSwitchPortError\", status=\"true\"} > 0) * on(node) group_left (stamp) group by (node,stamp) (stamp_config{node!=\"\"}))) or vector(0)",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "Switch Links - Full Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(interface_watch_list{stamp!=\"\"})",
     "legendFormat": "total_links"
    },
    {
     "expr": "count((group by (ifName, switch_id) (min_over_time(ifOperStatus[5m])!=1) or (group by (ifName, switch_id) (changes(ifLastChange[10m])>0) * 2) or (group by (ifName, switch_id)  (label_replace(label_replace(((min_over_time(linkmon_switch_oper_status[5m]) != 1)) or ((changes(linkmon_switch_carrier_changes[10m]) > 0) * 2) , \"ifName\", \"$1\", \"port\", \"(.*)\"), \"switch_id\", \"$1\", \"switch\", \"(.*)\")))) * on (ifName, switch_id) group_left (conn_type, node, device) (interface_watch_list{stamp!=\"\"} unless on (node) (kube_node_status_condition{condition=\"Ready\",status=\"true\"} == 0 or on (node) kube_node_spec_taint{job=\"kube-state-metrics\",key=\"node.kubernetes.io/unreachable\",effect=\"NoSchedule\"} == 1 or on (node) (label_replace((system_overall_health != 1 and system_overall_health != 2), \"node\", \"$1\", \"system\", \"(.*)\"))))) or vector(0)",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "Systems Assigned per Session, by Stamp",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (namespace, stamp) (namespace_reserved_system * on (system) group_left (stamp) stamp_config{system!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilization per session, by stamp",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_max(avg_over_time((sum by (namespace, stamp) (((group(wsjob_system_grant) by (system, namespace)) or (sum(0*system_label) by (system, namespace))) * on (system) group_left (stamp) stamp_config{system!=\"\"}) / count by (namespace, stamp) (group(namespace_reserved_system) by (system, namespace)  * on (system) group_left (stamp) stamp_config{system!=\"\"}))[$__range:$__rate_interval]) *100, 100) or label_replace(clamp_max(avg_over_time((sum by (namespace) (((group(wsjob_system_grant) by (system, namespace)) or (sum(0*system_label) by (system, namespace))) * on (system) group_left (stamp) stamp_config{system!=\"\"}) / count by (namespace) (group(namespace_reserved_system) by (system, namespace)  * on (system) group_left (stamp) stamp_config{system!=\"\"}))[$__range:$__rate_interval]) *100, 100), \"stamp\", \" Total\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Session view (across all stamps)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "System count and status by session",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (max(system_overall_health * on (system) group_left (namespace) namespace_reserved_system) by (system, namespace) == bool 2) + sum by (namespace) (max(system_overall_health * on (system) group_left (namespace) namespace_reserved_system) by (system, namespace) == bool 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace) (((group((system_overall_health != 1) and (system_overall_health != 2) and (system_overall_health != -1)) by (system)) or (group by (system) (system_overall_health) != bool(1))) * on (system) group_left (namespace) namespace_reserved_system)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilization by session",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_max(avg_over_time((sum by (namespace) ((group(wsjob_system_grant) by (system, namespace)) or (sum(0*system_label) by (system, namespace))) / count by (namespace) (group(namespace_reserved_system) by (system, namespace)))[$__range:$__rate_interval]) *100, 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}