{
 "title": "Job Logs",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "replica_type",
    "label": "replica_types",
    "query": {}
   },
   {
    "name": "replica_id",
    "label": "replica_id",
    "query": {}
   },
   {
    "name": "stream",
    "label": "stream",
    "query": {}
   },
   {
    "name": "wsjob",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Job Type",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (job_type) (last_over_time(wsjob_annotation{name=\"$wsjob\", start!=\"\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Start",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (start) (last_over_time(wsjob_annotation{name=\"$wsjob\", start!=\"\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job End",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (end) (last_over_time(wsjob_annotation{name=\"$wsjob\", end!=\"\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Training Status",
   "type": "state-timeline",
   "description": "Stall detection status from coordinator logs. Possible states: UNKNOWN, CKPT_IN_PROGRESS, IDLE, INPUT_STARVATION, STALLED, COMPLETED, TERMINATED, PROGRESSING.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{wsjob=\"$wsjob\", metric=\"stall_detect\"} | json status",
     "legendFormat": "state"
    }
   ]
  },
  {
   "title": "$replica_type logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "repeat": "replica_type",
   "targets": [
    {
     "expr": "{wsjob=\"$wsjob\", replica_type=~\"$replica_type\", stream=\"$stream\", replica_id=\"$replica_id\"} | json | line_format `id={{.replica_id}} type={{.replica_type}} stream={{.stream}} | {{.message}}`"
    }
   ]
  }
 ]
}