{
 "title": "Job Debug",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(namespace_reservation, namespace)"
   },
   {
    "name": "model",
    "query": "label_values(wsjob_annotation, labels_k8s_cerebras_com_Model)"
   },
   {
    "name": "job_type",
    "query": "label_values(wsjob_annotation, job_type)"
   },
   {
    "name": "wsjob",
    "query": {
     "query": "wsjob_annotation{labels_k8s_cerebras_com_Model=~\"$model\", job_type=~\"$job_type\", namespace=~\"$namespace\", start!=\"\", end=\"\"}"
    }
   },
   {
    "name": "replica_type",
    "query": "label_values(kube_pod_info{created_by_name=\"$wsjob\", pod=~\"$wsjob-.*\", pod_ip!=\"\"}, pod)"
   },
   {
    "name": "replica_id",
    "query": "label_values(kube_pod_info{created_by_name=\"$wsjob\", pod=~\"$wsjob-$replica_type.*\", pod_ip!=\"\"}, pod)"
   },
   {
    "name": "system",
    "query": "label_values(wsjob_system_grant{name=\"$wsjob\"}, system)"
   },
   {
    "name": "leaf_switch",
    "query": {
     "query": "label_values(job:leaf_switch_port_info{job_name=~\"$wsjob\"},switch)"
    }
   },
   {
    "name": "spine_switch",
    "query": {
     "query": "query_result(group by (switch) (rate(job:leaf_switch_port_info{job_name=~\"$wsjob\"}[24h])) * on (switch) group_right label_replace((avg by (switch_id, node) (interface_watch_list)), \"switch\", \"$1\", \"node\", \"(.*)\"))"
    }
   },
   { "name": "glitch_thresh", "query": "1" },
   { "name": "current_thresh", "query": "380" },
   { "name": "voltage_thresh", "query": "0.7" }
  ]
 },
 "panels": [
  {
   "title": "Job Type",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (job_type) (last_over_time(wsjob_annotation{name=\"$wsjob\", start!=\"\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Start",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (start) (last_over_time(wsjob_annotation{name=\"$wsjob\", start!=\"\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job End",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (end) (last_over_time(wsjob_annotation{name=\"$wsjob\", end!=\"\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Training Status",
   "type": "state-timeline",
   "description": "Stall detection status from coordinator logs. Possible states: UNKNOWN, CKPT_IN_PROGRESS, IDLE, INPUT_STARVATION, STALLED, COMPLETED, TERMINATED, PROGRESSING.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{wsjob=\"$wsjob\", metric=\"stall_detect\"} | json status",
     "legendFormat": "state"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "state-timeline",
   "description": "These errors are likely fatal",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "group by (node, interface) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (node, interface) group_left label_replace((increase(interface_watch_list:status_changes_total[$__rate_interval]) >= bool 2), \"interface\", \"$1\", \"device\", \"(.*)\") > 0",
     "legendFormat": "{{node}}:{{interface}} flapping"
    },
    {
     "expr": "group by (switch, port) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (switch, port) group_left avg((increase(linkmon_switch_carrier_changes[11m]) > 0)) by (switch, port)",
     "legendFormat": "{{switch}}:{{port}} flapping"
    },
    {
     "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$leaf_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_left avg((increase(linkmon_switch_carrier_changes{switch=~\"$spine_switch\"}[11m]) > 0)) by (switch, port)",
     "legendFormat": "{{switch}}:{{port}} flapping"
    },
    {
     "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_left avg((increase(linkmon_switch_carrier_changes{switch=~\"$leaf_switch\"}[11m]) > 0)) by (switch, port)",
     "legendFormat": "{{switch}}:{{port}} flapping"
    },
    {
     "expr": "sum by (pod, reason)\n(\n  kube_pod_container_status_terminated_reason{pod=~\"$wsjob-.*\", reason!=\"Completed\"} offset -5m\n) > 0",
     "legendFormat": "{{pod}} Pod {{reason}}"
    },
    {
     "expr": "(max_over_time(kube_node_status_condition{condition=~\"ClusterMgmt.*|ClusterDeploy.*|Csadm.*\", status=\"true\"}[$__rate_interval]) > 0) * on (node) group_left group by(node) (kube_pod_info{pod=~\"$wsjob-.*\", pod_ip!=\"\"})",
     "legendFormat": "{{node}} {{condition}}"
    },
    {
     "expr": "((min_over_time(node_health_overall[$__rate_interval]) == bool 0) > 0) * on (node) group_left group by(node) (kube_pod_info{pod=~\"$wsjob-.*\", pod_ip!=\"\"})",
     "legendFormat": "{{node}} IPMIUnhealthy"
    },
    {
     "expr": "group by (node, interface) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (node, interface) (label_replace((min_over_time(interface_watch_list:status[$__rate_interval]) == bool 0), \"interface\", \"$1\", \"device\", \"(.*)\") > 0)",
     "legendFormat": "{{node}}:{{interface}} down"
    },
    {
     "expr": "group by (node, interface) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (node, interface) (increase(node_nic_stats_resp_cqe_error[$__rate_interval]) > 0)",
     "legendFormat": "{{node}}:{{interface}} RX CQE Error"
    },
    {
     "expr": "group by (node, interface) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (node, interface) (increase(node_nic_stats_req_cqe_error[$__rate_interval]) > 0)",
     "legendFormat": "{{node}}:{{interface}} TX CQE Error"
    },
    {
     "expr": "max((max_over_time(system_overall_health[$__rate_interval]) != 1) != 2) by (system) * on (system) group_left group(wsjob_system_grant{name=\"$wsjob\", system=~\"$system\"}) by (name, system) # anything except OK or DEGRADED",
     "legendFormat": "{{system}} health error"
    },
    {
     "expr": "group by (system) (system_events{component=\"CM_CM_DAEMON\", severity=\"WARN\", type=\"EventHealthDegraded\"})\n* on (system) group_right group(wsjob_system_grant{name=\"$wsjob\", system=~\"$system\"}) by (name, system)",
     "legendFormat": "{{system}} Conn Mgr restarted"
    },
    {
     "expr": "max((increase(system_network_flap_count[$__rate_interval]) >= bool 2) != 0) by (system) * on (system) group_left group(wsjob_system_grant{name=\"$wsjob\", system=~\"$system\"}) by (name, system)",
     "legendFormat": "{{system}}:{{port}} port flapping"
    },
    {
     "expr": "(min_over_time(system_network_health[$__rate_interval]) == 0) * on (system) group_left group(wsjob_system_grant{name=\"$wsjob\", system=~\"$system\"}) by (name, system)",
     "legendFormat": "{{system}}:{{port}} network error"
    },
    {
     "expr": "(increase(system_network_err_qps[$__rate_interval]) > 0) * on (system) group_left group(wsjob_system_grant{name=~\"$wsjob\", system=~\"$system\"}) by (name, system)",
     "legendFormat": "{{system}}:{{port}} QP error"
    },
    {
     "expr": "ALERTS{alertname=\"MlJobFailed\", alertstate=\"firing\", name=\"$wsjob\"}",
     "legendFormat": "{{alertname}} Alert"
    },
    {
     "expr": "group by (node, interface) (job:leaf_switch_port_info{job_name=~\"$wsjob\"})\n* on (node, interface) group_right\nlabel_replace(label_replace(\n        pingmesh:unreachable5m,\n        \"node\", \"$1\", \"host\", \"(.*)\"),\n        \"interface\", \"$1\", \"nic\", \"(.*)\"\n)",
     "legendFormat": "{{host}}/{{nic}} Unreachable"
    },
    {
     "expr": "group by (system) (wsjob_system_grant{name=~\"wsjob.*\"})\n* on (system) group_right\nlabel_replace(\n        pingmesh:unreachable5m,\n        \"system\", \"$1\", \"host\", \"(.*)\"\n)",
     "legendFormat": "{{host}}/{{nic}} Unreachable"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "state-timeline",
   "description": "These warnings may not necessarily cause a job to crash. They may impact performance",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "((min_over_time(node_health_overall[$__rate_interval]) == bool 0) > 0) * on (node) group_left group by(node) (kube_pod_info{pod=~\"$wsjob-.*\", pod_ip!=\"\"})",
     "legendFormat": "{{node}} IPMI Unhealthy"
    },
    {
     "expr": "group by (node, interface) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (node, interface) group_left increase(node_nic_stats_local_ack_timeout_err[$__rate_interval]) > 0",
     "legendFormat": "{{node}}:{{interface}} Local ACK Timeout"
    },
    {
     "expr": "max(max_over_time(system_overall_health[$__rate_interval]) == 2) by (system) * on (system) group_left group(wsjob_system_grant{name=\"$wsjob\", system=~\"$system\"}) by (name, system)",
     "legendFormat": "{{system}} Degraded"
    },
    {
     "expr": "(group by (system, severity, type, component) (system_events{severity=~\"CRITICAL|ERROR|WARN\"})) * on (system) group_left group(wsjob_system_grant{name=\"$wsjob\", system=~\"$system\"}) by (name, system)",
     "legendFormat": "{{system}}/{{severity}}/{{type}}/{{component}}"
    },
    {
     "expr": "(increase(system_network_rx_pkt_bad_fcs[$__rate_interval]) > 0) * on (system) group_left group(wsjob_system_grant{name=~\"$wsjob\", system=~\"$system\"}) by (name, system)",
     "legendFormat": "{{system}}:{{port}} CRC Errors"
    },
    {
     "expr": "(increase(system_network_ack_timeouts[$__rate_interval]) > 0) * on (system) group_left group(wsjob_system_grant{name=~\"$wsjob\", system=~\"$system\"}) by (name, system)",
     "legendFormat": "{{system}}:{{port}} ACK Timeouts"
    },
    {
     "expr": "(increase(system_network_rx_fec_uncorrected_pkts[$__rate_interval]) > 0) * on (system) group_left group(wsjob_system_grant{name=~\"$wsjob\", system=~\"$system\"}) by (name, system)",
     "legendFormat": "{{system}}:{{port}} FEC Uncorrected Errors"
    },
    {
     "expr": "(increase(system_network_rx_sequence_errors[$__rate_interval]) > 0) * on (system) group_left group(wsjob_system_grant{name=~\"$wsjob\", system=~\"$system\"}) by (name, system)",
     "legendFormat": "{{system}}:{{port}} RX Seq Errors"
    },
    {
     "expr": "(increase(system_network_tx_sequence_errors[$__rate_interval]) > 0) * on (system) group_left group(wsjob_system_grant{name=~\"$wsjob\", system=~\"$system\"}) by (name, system)",
     "legendFormat": "{{system}}:{{port}} TX Seq Errors"
    },
    {
     "expr": "(increase(system_network_rx_pkt_bad_fcs[$__rate_interval]) > 0) * on (system) group_left group(wsjob_system_grant{name=~\"$wsjob\", system=~\"$system\"}) by (name, system)",
     "legendFormat": "{{system}}:{{port}} Bad FCS pkt"
    },
    {
     "expr": "count by (system) (max_over_time(system_dev_stats{system=~\"$system\", component=~\"^GLTCH_(EXCUR|TRANS).*\"}[$__rate_interval]) > $glitch_thresh) * on (system) group_left group(wsjob_system_grant{name=\"$wsjob\", system=~\"$system\"}) by (name, system)",
     "legendFormat": "{{system}} High Glitches"
    },
    {
     "expr": "count by (system) (max_over_time(system_dev_stats{system=~\"$system\", component=~\"^VDDC.*_IOUT\"}[$__rate_interval]) > $current_thresh) * on (system) group_left group(wsjob_system_grant{name=\"$wsjob\", system=~\"$system\"}) by (name, system)",
     "legendFormat": "{{system}} High Current"
    },
    {
     "expr": "count by (system) (max_over_time(system_dev_stats{system=~\"$system\", component=~\"^VDDC_ASIC.*\"}[$__rate_interval]) > $voltage_thresh) * on (system) group_left group(wsjob_system_grant{name=\"$wsjob\", system=~\"$system\"}) by (name, system)",
     "legendFormat": "{{system}} High Voltage"
    },
    {
     "expr": "group by (switch, port) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (switch, port) group_left avg((increase(linkmon_switch_crc_errors[11m]) > 0)) by (switch, port)",
     "legendFormat": "{{switch}}:{{port}} CRC Errors"
    },
    {
     "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$leaf_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_left avg((increase(linkmon_switch_crc_errors{switch=~\"$spine_switch\"}[$__rate_interval]) > 0)) by (switch, port)",
     "legendFormat": "{{switch}}:{{port}} CRC Errors"
    },
    {
     "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_left avg((increase(linkmon_switch_crc_errors{switch=~\"$leaf_switch\"}[$__rate_interval]) > 0)) by (switch, port)",
     "legendFormat": "{{switch}}:{{port}} CRC Errors"
    },
    {
     "expr": "group by (switch, port) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (switch, port) group_left avg((increase(linkmon_switch_out_discards[$__rate_interval]) > 0)) by (switch, port)",
     "legendFormat": "{{switch}}:{{port}} Out Discards"
    },
    {
     "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$leaf_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_left avg((increase(linkmon_switch_out_discards{switch=~\"$spine_switch\"}[$__rate_interval]) > 0)) by (switch, port)",
     "legendFormat": "{{switch}}:{{port}} Out Discards"
    },
    {
     "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_left avg((increase(linkmon_switch_out_discards{switch=~\"$leaf_switch\"}[$__rate_interval]) > 0)) by (switch, port)",
     "legendFormat": "{{switch}}:{{port}} Out Discards"
    },
    {
     "expr": "group by (switch, port) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (switch, port) group_left avg((increase(linkmon_switch_in_discards[$__rate_interval]) > 0)) by (switch, port)",
     "legendFormat": "{{switch}}:{{port}} In Discards"
    },
    {
     "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$leaf_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_left avg((increase(linkmon_switch_in_discards{switch=~\"$spine_switch\"}[$__rate_interval]) > 0)) by (switch, port)",
     "legendFormat": "{{switch}}:{{port}} In Discards"
    },
    {
     "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_left avg((increase(linkmon_switch_in_discards{switch=~\"$leaf_switch\"}[$__rate_interval]) > 0)) by (switch, port)",
     "legendFormat": "{{switch}}:{{port}} In Discards"
    },
    {
     "expr": "group by (switch, port) (job:leaf_switch_port_info{job_name=~\"$wsjob\"})* on (switch, port) group_left avg((increase(linkmon_switch_delta_fec_uncorrected_codewords[$__rate_interval]) > 0)) by (switch, port)",
     "legendFormat": "{{switch}}:{{port}} FEC Uncorrected"
    },
    {
     "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$leaf_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_left avg((increase(linkmon_switch_delta_fec_uncorrected_codewords{switch=~\"$spine_switch\"}[$__rate_interval]) > 0)) by (switch, port)",
     "legendFormat": "{{switch}}:{{port}} FEC Uncorrected"
    },
    {
     "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_left avg((increase(linkmon_switch_delta_fec_uncorrected_codewords{switch=~\"$leaf_switch\"}[$__rate_interval]) > 0)) by (switch, port)",
     "legendFormat": "{{switch}}:{{port}} FEC Uncorrected"
    },
    {
     "expr": "ALERTS{alertname=\"WsjobStuckAtTerminating\", pod=~\"$wsjob.*\"}",
     "legendFormat": "{{alertname}} Alert: {{pod}}"
    },
    {
     "expr": "job_operator_spine_load{job_name=~\"$wsjob\"} > 0",
     "legendFormat": "Spine load: {{load_type}}"
    },
    {
     "expr": "group by (job_name) (pod_port_affinity{job_name=~\"$wsjob\", is_one_hop=\"0\", pod_id!~\"chief-.*|coordinator-.*\"}) > 0",
     "legendFormat": "Sub-Optimal Job Pod Placement"
    },
    {
     "expr": "100 * sum(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) without (cpu, mode)\n* on (instance) group_left(node)\nlabel_replace(node_uname_info, \"node\", \"$1\", \"nodename\", \"(.*)\")\n* on (node) group_left\ngroup by (node) (user_node_process_cpu_used_percent{job_id=~\"$wsjob\"})\n> 80",
     "legendFormat": "Usernode CPU Oversubscribed: {{node}}"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))\n* on (instance) group_left(node)\nlabel_replace(node_uname_info, \"node\", \"$1\", \"nodename\", \"(.*)\")\n* on (node) group_left\ngroup by (node) (user_node_process_cpu_used_percent{job_id=~\"$wsjob\"})\n> 80",
     "legendFormat": "Usernode Mem Oversubscribed: {{node}}"
    }
   ]
  },
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "ML FLOPS Utilization",
     "type": "xychart",
     "description": "ML FLOPS Utilization (%) after each iteration.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "{metric=\"ml_flops\", wsjob=~\"$wsjob\"} | json"
      }
     ]
    },
    {
     "title": "Deadlock Status",
     "type": "table",
     "description": "Summary of a deadlock, if detected.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "{wsjob=~\"$wsjob\", metric=\"deadlock\"}"
      },
      {
       "expr": "{wsjob=~\"$wsjob\", metric=\"debugviz\"}"
      }
     ]
    },
    {
     "title": "Assigned Systems - Events",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_events{system=~\"$system\", severity!~\"CRITICAL|ERROR|WARN\"} ",
       "legendFormat": "{{system}}/{{severity}}/{{type}}/{{component}}"
      }
     ]
    },
    {
     "title": "Assigned Systems - Glitch Counter Errors On Selected Die",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_dev_stats{system=~\"$system\", component=~\"^GLTCH_(EXCUR|TRANS).*\"} * on (system) group_left wsjob_system_grant{name=\"$wsjob\"} > 0",
       "legendFormat": "{{system}}/{{component}}"
      },
      { "expr": "$glitch_thresh", "legendFormat": "Error Threshold" }
     ]
    },
    {
     "title": "Assigned Systems - VDDC_IOUT On Selected Die",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "Amperes" } },
     "targets": [
      {
       "expr": "system_dev_stats{system=~\"$system\", component=~\"^VDDC.*_IOUT\"} * on (system) group_left wsjob_system_grant{name=\"$wsjob\"}",
       "legendFormat": "{{system}}/{{component}}"
      },
      { "expr": "$current_thresh", "legendFormat": "Error Threshold" }
     ]
    },
    {
     "title": "Assigned Systems - VDDC_ASIC On Selected Die",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "Volts" } },
     "targets": [
      {
       "expr": "system_dev_stats{system=~\"$system\", component=~\"^VDDC_ASIC.*\"} * on (system) group_left wsjob_system_grant{name=\"$wsjob\"}",
       "legendFormat": "{{system}}/{{component}}"
      },
      { "expr": "$voltage_thresh", "legendFormat": "Error Threshold" }
     ]
    },
    {
     "title": "Node Debug Warnings",
     "type": "state-timeline",
     "description": "These warnings may not necessarily cause a job to crash. They may impact performance",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "group by (node, interface) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (node, interface) group_left increase(node_nic_stats_rx_crc_errors_phy[$__rate_interval]) > 0",
       "legendFormat": "{{node}}:{{interface}} CRC Errors"
      },
      {
       "expr": "group by (node, interface) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (node, interface) group_left increase(node_nic_stats_rx_pcs_symbol_err_phy[$__rate_interval]) > 0",
       "legendFormat": "{{node}}:{{interface}} FEC Uncorrected"
      },
      {
       "expr": "group by (node, interface) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (node, interface) group_left increase(node_nic_stats_roce_adp_retrans[$__rate_interval]) > 0",
       "legendFormat": "{{node}}:{{interface}} ADP Retransmit"
      },
      {
       "expr": "group by (node, interface) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (node, interface) group_left increase(node_nic_stats_packet_seq_err[$__rate_interval]) > 0",
       "legendFormat": "{{node}}:{{interface}} RX NAKs"
      },
      {
       "expr": "group by (node, interface) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (node, interface) group_left increase(node_nic_stats_out_of_sequence[$__rate_interval]) > 0",
       "legendFormat": "{{node}}:{{interface}} TX NAKs"
      },
      {
       "expr": "group by (node, interface) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (node, interface) group_left increase(node_nic_stats_tx_discards_phy[$__rate_interval]) > 0",
       "legendFormat": "{{node}}:{{interface}} TX Discards"
      },
      {
       "expr": "group by (node, interface) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (node, interface) group_left increase(node_nic_stats_out_of_buffer[$__rate_interval]) > 0",
       "legendFormat": "{{node}}:{{interface}} OOB Drops"
      },
      {
       "expr": "group by (node, interface) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (node, interface) group_left increase(node_nic_stats_rnr_nak_retry_err[$__rate_interval]) > 0",
       "legendFormat": "{{node}}:{{interface}} RNR NAKs"
      },
      {
       "expr": "group by (node, interface) (job:leaf_switch_port_info{job_name=~\"$wsjob\"}) * on (node, interface) (avg_over_time(node_nic_stats_temperature[11m]) > 80)",
       "legendFormat": "{{node}}:{{interface}} NIC Temperature"
      }
     ]
    },
    {
     "title": "Assigned Nodes - Network PFC Pause Duration Increase",
     "type": "timeseries",
     "description": "Network congestion. If the job succeeded, no action is needed for these.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "(increase(node_nic_stats_rx_pfc_duration[$__rate_interval]) > 0) * on (node) group_left group by(node) (kube_pod_info{pod=~\"$wsjob-.*\", pod_ip!=\"\"})",
       "legendFormat": "{{node}}/{{interface}} PFC Pause Duration increase"
      }
     ]
    },
    {
     "title": "AX Memory Usage",
     "type": "bargauge",
     "description": "The memory allocated to all the KVSS + ACT + Chief pods should be less than the total AX memory available.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_over_time(job_ax_memory_limit{job_name=~\"$wsjob\"}[$__range]) * 1024 * 1024",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(kube_pod_container_resource_requests{resource=\"memory\", pod=~\"$wsjob-kvstorageserver.*\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(kube_pod_container_resource_requests{resource=\"memory\", pod=~\"$wsjob-activation.*\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(last_over_time(kube_pod_container_resource_requests{resource=\"memory\", pod=~\"$wsjob-chief.*\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": " ",
     "type": "gauge",
     "description": "The AX memory utilization is the percent of available AX memory used by all AX pods: `(KVSS + ACT + Chief pods) / total AX memory available`",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n    scalar(sum(last_over_time(kube_pod_container_resource_requests{resource=\"memory\", pod=~\"$wsjob-kvstorageserver.*\"}[$__range])))\n    + scalar(sum(last_over_time(kube_pod_container_resource_requests{resource=\"memory\", pod=~\"$wsjob-activation.*\"}[$__range])))\n    + scalar(sum(last_over_time(kube_pod_container_resource_requests{resource=\"memory\", pod=~\"$wsjob-chief.*\"}[$__range])))\n)\n/\n(last_over_time(job_ax_memory_limit{job_name=~\"$wsjob\"}[$__range]) * 1024 * 1024)",
       "legendFormat": "Util"
      }
     ]
    },
    {
     "title": "KVStorageServer NICs",
     "type": "table",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count by (node_name, nic_names) (present_over_time(pod_port_affinity{pod_id=~\"kvstorageserver-.*\", job_name=~\"$wsjob\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CRD Log Errors",
     "type": "logs",
     "description": "Highlighted common errors from coordinator logs.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "{replica_type=\"coordinator\", wsjob=\"$wsjob\"} | json | line_format \"{{.stream}} {{.message}}\" |~ \"due to error detected in ACT|Couldn't receive tensor|wafer progress counters miscorrelation with core state|UNAVAILABLE Failed to shutdown ACT server due to error: failed to connect to all addresses|Error has been detected in UnaryMonitorError|Chief service was interrupted with fatal signal 6 (Aborted)|Error detected in CHF|INTERNAL Failed to load artifacts to CHF|UnaryNotifyCrash failed. Error code = 14, Error desc = UNAVAILABLE, Error message: failed to connect to all addresses|UnaryDone failed. Error code = 14, Error desc = UNAVAILABLE, Error message: Socket closed, Error details|Error detected in ACT|INTERNAL Failed to load artifacts to WGT servers due to error: Resource temporarily unavailable|UnaryNotifyCrash failed. Error code = 14, Error desc = UNAVAILABLE, Error message: Connection reset by peer, Error details|UnaryNotifyCrash failed. Error code = 14, Error desc = UNAVAILABLE, Error message: Transport closed, Error details|Error detected in WGT|failed to compile image files|ModuleNotFoundError: No module named 'cerebras.modelzoo'|INTERNAL Failed to intialize runtime for WRK server due to error|ClockSync request failed. Error code = 4, Error desc = DEADLINE_EXCEEDED, Error message: Deadline Exceeded, Error details|INTERNAL Failed to initialize WRK servers due to error|ERROR:\""
      }
     ]
    }
   ]
  }
 ]
}