{
 "title": "Job Network Debug",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "wsjob",
    "label": "WsJob",
    "query": {
     "query": "query_result(group by (job_name) (present_over_time(job:leaf_switch_port_info{job_namespace=~\"$namespace\"}[$__range])))"
    }
   },
   { "name": "pod_regex", "label": "Pod Regex", "query": ".*" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(job:leaf_switch_port_info{job_name=~\"$wsjob\", pod_name=~\"$pod_regex\"},pod_name)"
    }
   },
   { "name": "node_regex", "label": "Node Regex", "query": ".*" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(job:leaf_switch_port_info{job_name=~\"$wsjob\", node=~\"$node_regex\"},node)"
    }
   },
   {
    "name": "node_port",
    "label": "Pod NIC",
    "query": {
     "query": "label_values(job:leaf_switch_port_info{job_name=~\"$wsjob\", node=~\"$node\"},interface)"
    }
   },
   { "name": "switch_regex", "label": "Leaf Switch Regex", "query": ".*" },
   {
    "name": "switch",
    "label": "Leaf Switch",
    "query": {
     "query": "label_values(job:leaf_switch_port_info{job_name=~\"$wsjob\", switch=~\"$switch_regex\", interface=~\"$node_port\", node=~\"$node\"},switch)"
    }
   },
   {
    "name": "switch_port",
    "label": "Leaf->Node Port",
    "query": {
     "query": "label_values(job:leaf_switch_port_info{job_name=~\"$wsjob\", switch=~\"$switch\", interface=~\"$node_port\", node=~\"$node\"},port)"
    }
   },
   {
    "name": "spine_switch",
    "label": "Spine Switch",
    "query": {
     "query": "query_result(group by (switch) (rate(job:leaf_switch_port_info{job_name=~\"$wsjob\", interface=~\"$node_port\", node=~\"$node\"}[$__range])) * on (switch) group_right label_replace((avg by (switch_id, node) (interface_watch_list)), \"switch\", \"$1\", \"node\", \"(.*)\"))"
    }
   },
   {
    "name": "system",
    "label": "System",
    "query": {
     "query": "label_values(wsjob_system_grant{name=~\"$wsjob\"},system)"
    }
   },
   {
    "name": "system_port",
    "label": "System Port",
    "query": {
     "query": "query_result(system_network_rx_bytes{system=~\"$system\"})"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(namespace_reservation,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Jobs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "group by (name, job_type, system_count, start) (last_over_time(wsjob_annotation{name=~\"$wsjob\", start!=\"\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "group by (name, job_type, system_count, end) (last_over_time(wsjob_annotation{name=~\"$wsjob\", end!=\"\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum by (job_name) (group by (job_name, node) (last_over_time(job:leaf_switch_port_info{job_name=~\"$wsjob\", node=~\"$node\", device=~\"$node_port\", pod_name=~\"$pod\", port=~\"$switch_port\", switch=~\"$switch\"}[$__range]))), \"name\", \"$1\", \"job_name\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Training Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{wsjob=~\"$wsjob\", metric=\"stall_detect\"} | json status"
    }
   ]
  },
  {
   "title": "Links: Node - Leaf ",
   "type": "table",
   "description": "<h3>Definitions</h3>\n<ul>\n<li>System: a server that hosts the Cerebras wafer.</li>\n<li>Node: a commodity server supporting the job (coordinator, activation, etc.). </li>\n<li>NIC: network interface on a node. Multiple pods on the same node may share the same NIC.</i>\n<li>Leaf switch: a network switch to which nodes and system are directly connected.</li>\n<li>Spine switch: a switch connecting multiple leaf switches, enabling nodes/systems connected to different leaf switches to communicate with each other.</li>\n</ul>",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (job_name,pod_name,node,device,device_ip,port,switch) (count_over_time(job:leaf_switch_port_info{job_name=~\"$wsjob\", node=~\"$node\", device=~\"$node_port\", pod_name=~\"$pod\", port=~\"$switch_port\", switch=~\"$switch\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "group by (node, device) (present_over_time(job:leaf_switch_port_info{job_name=~\"$wsjob\", node=~\"$node\", device=~\"$node_port\", pod_name=~\"$pod\", port=~\"$switch_port\", switch=~\"$switch\"}[$__range])) * on (node, device) group_left increase(interface_watch_list:status_changes_total[$__range]) >= 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Links: Leaf - Spine ",
   "type": "table",
   "description": "Spine switches may appear here, even if a job isn't using them. This shows all spine switches reachable from leaf switches connected to the job's nodes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "group by (node, device, ifName, switch_id) (interface_watch_list{node=~\"$switch\", switch_id=~\"$spine_switch\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "group by (node, device) (interface_watch_list{node=~\"$switch\", switch_id=~\"$spine_switch\"}) * on(node, device) group by (node, device) (label_replace(label_replace(increase(linkmon_switch_carrier_changes[$__range]) >= 2, \"device\", \"$1\", \"port\", \"(.*)\"), \"node\", \"$1\", \"switch\", \"(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Links: System - Leaf",
   "type": "table",
   "description": "Connections between systems and leaf switches.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "present_over_time(interface_watch_list{node=~\"$system\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(irate(node_nic_stats_rx_bytes_phy{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface)",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "Node Flaps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(present_over_time(job:leaf_switch_port_info{job_name=~\"$wsjob\"}[$__range]) * on (node, interface) group_left avg(increase(node_nic_stats_carrier_changes{node=~\"$node\", interface=~\"$node_port\"}[11m])) by (node, interface)) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "Unreachable Ports",
     "type": "state-timeline",
     "description": "Interfaces that aren't responding to pings (using CPingmesh).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "pingmesh:unreachable5m{host=~\"$node\", nic=~\"$node_port\"}",
       "legendFormat": "{{host}}/{{nic}}"
      }
     ]
    },
    {
     "title": "Node Rx PFC Duration (per second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(irate(node_nic_stats_rx_pfc_duration{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "Node Rx PFC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(irate(node_nic_stats_rx_pfc{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "Node Tx PFC Duration (per second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(irate(node_nic_stats_tx_pfc_duration{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "Node Tx PFC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(irate(node_nic_stats_tx_pfc{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "Node Rx Stream Sequence Errors (Tx NAKs)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(increase(node_nic_stats_out_of_sequence{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface)) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "Node Tx Stream Sequence Errors (Rx NAKs)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(increase(node_nic_stats_packet_seq_err{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface)) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "Node OOB Drops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(irate(node_nic_stats_out_of_buffer{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "Node xmit Discards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(increase(node_nic_stats_tx_discards_phy{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface)) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "Node CQ Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(increase(node_nic_stats_resp_cqe_error{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface)) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      },
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(increase(node_nic_stats_req_cqe_error{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface)) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "Node RNR NAKs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(irate(node_nic_stats_rnr_nak_retry_err{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "Node CRC Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(increase(node_nic_stats_rx_crc_errors_phy{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface)) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "Node Local ACK Timeouts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(increase(node_nic_stats_local_ack_timeout_err{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface)) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "NIC Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(node_nic_stats_temperature{node=~\"$node\", interface=~\"$node_port\"}) by (node, interface)",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "Optics Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(node_nic_stats_opt_temperature{node=~\"$node\", interface=~\"$node_port\"}) by (node, interface)",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "NP ECN Marked Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(increase(node_nic_stats_np_ecn_marked_roce_packets{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface)) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "Node PCS Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(increase(node_nic_stats_rx_pcs_symbol_err_phy{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface)) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "RP CNP Ignored",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(increase(node_nic_stats_rp_cnp_ignored{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface)) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "NP CNP Sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(increase(node_nic_stats_np_cnp_sent{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface)) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "RP CNP Handled",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(increase(node_nic_stats_rp_cnp_handled{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface)) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    },
    {
     "title": "RoCE Slow Start CNPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (node, interface) group_left avg(increase(node_nic_stats_roce_slow_restart_cnps{node=~\"$node\", interface=~\"$node_port\"}[$__rate_interval])) by (node, interface)) > 0",
       "legendFormat": "{{node}}:{{interface}} -> {{switch}}:{{port}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Leaf -> Node ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Switch Rx kbps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 334 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(linkmon_switch_rx_kbps{switch=~\"$switch\", port=~\"$switch_port\"}) by (switch, port)",
       "legendFormat": "{{switch}}:{{port}} -> {{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "Switch Tx kbps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 334 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(linkmon_switch_tx_kbps{switch=~\"$switch\", port=~\"$switch_port\"}) by (switch, port)",
       "legendFormat": "{{switch}}:{{port}} -> {{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "Switch Rx PFC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 342 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(irate(linkmon_switch_rx_pfc{switch=~\"$switch\", port=~\"$switch_port\"}[$__rate_interval])) by (switch, port) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "Switch Tx PFC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(irate(linkmon_switch_tx_pfc{switch=~\"$switch\", port=~\"$switch_port\"}[$__rate_interval])) by (switch, port) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "Switch CRC Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(increase(linkmon_switch_crc_errors{switch=~\"$switch\", port=~\"$switch_port\"}[11m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "Switch Flaps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(present_over_time(job:leaf_switch_port_info{job_name=~\"$wsjob\"}[$__range]) * on (switch, port) group_left avg(increase(linkmon_switch_carrier_changes{switch=~\"$switch\", port=~\"$switch_port\"}[$__rate_interval])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "Switch FEC Corrected",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(irate(linkmon_switch_delta_fec_corrected_codewords{switch=~\"$switch\", port=~\"$switch_port\"}[$__rate_interval])) by (switch, port) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "Switch FEC Uncorrected",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(increase(linkmon_switch_delta_fec_uncorrected_codewords{switch=~\"$switch\", port=~\"$switch_port\"}[11m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "Switch Out Discards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(increase(linkmon_switch_out_discards{switch=~\"$switch\", port=~\"$switch_port\"}[11m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "Switch In Discards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(increase(linkmon_switch_in_discards{switch=~\"$switch\", port=~\"$switch_port\"}[11m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "Switch ECN Marked Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(increase(linkmon_switch_ecn_marked_packets_tc5{switch=~\"$switch\", port=~\"$switch_port\"}[11m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "Optics Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(linkmon_switch_opt_temperature{switch=\"$switch\", port=\"$switch_port\"}) by (switch, port))",
       "legendFormat": "{{switch}}:{{port}} -> {{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "Optics TX Current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "mamp" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(linkmon_switch_opt_tx_current_lane1{switch=\"$switch\", port=\"$switch_port\"}) by (switch, port))",
       "legendFormat": "Lane 1 {{switch}}:{{port}} -> {{node}}:{{interface}}"
      },
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(linkmon_switch_opt_tx_current_lane2{switch=\"$switch\", port=\"$switch_port\"}) by (switch, port))",
       "legendFormat": "Lane 2 {{switch}}:{{port}} -> {{node}}:{{interface}}"
      },
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(linkmon_switch_opt_tx_current_lane3{switch=\"$switch\", port=\"$switch_port\"}) by (switch, port))",
       "legendFormat": "Lane 3 {{switch}}:{{port}} -> {{node}}:{{interface}}"
      },
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(linkmon_switch_opt_tx_current_lane4{switch=\"$switch\", port=\"$switch_port\"}) by (switch, port))",
       "legendFormat": "Lane 4 {{switch}}:{{port}} -> {{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "Optics RX Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(linkmon_switch_opt_rx_power_lane1{switch=\"$switch\", port=\"$switch_port\"}) by (switch, port))",
       "legendFormat": "Lane 1 {{switch}}:{{port}} -> {{node}}:{{interface}}"
      },
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(linkmon_switch_opt_rx_power_lane2{switch=\"$switch\", port=\"$switch_port\"}) by (switch, port))",
       "legendFormat": "Lane 2 {{switch}}:{{port}} -> {{node}}:{{interface}}"
      },
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(linkmon_switch_opt_rx_power_lane3{switch=\"$switch\", port=\"$switch_port\"}) by (switch, port))",
       "legendFormat": "Lane 3 {{switch}}:{{port}} -> {{node}}:{{interface}}"
      },
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(linkmon_switch_opt_rx_power_lane4{switch=\"$switch\", port=\"$switch_port\"}) by (switch, port))",
       "legendFormat": "Lane 4 {{switch}}:{{port}} -> {{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "Optics TX Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(linkmon_switch_opt_tx_power_lane1{switch=\"$switch\", port=\"$switch_port\"}) by (switch, port))",
       "legendFormat": "Lane 1 {{switch}}:{{port}} -> {{node}}:{{interface}}"
      },
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(linkmon_switch_opt_tx_power_lane2{switch=\"$switch\", port=\"$switch_port\"}) by (switch, port))",
       "legendFormat": "Lane 2 {{switch}}:{{port}} -> {{node}}:{{interface}}"
      },
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(linkmon_switch_opt_tx_power_lane3{switch=\"$switch\", port=\"$switch_port\"}) by (switch, port))",
       "legendFormat": "Lane 3 {{switch}}:{{port}} -> {{node}}:{{interface}}"
      },
      {
       "expr": "(job:leaf_switch_port_info{job_name=~\"$wsjob\"} * on (switch, port) group_left avg(linkmon_switch_opt_tx_power_lane4{switch=\"$switch\", port=\"$switch_port\"}) by (switch, port))",
       "legendFormat": "Lane 4 {{switch}}:{{port}} -> {{node}}:{{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Leaf <-> Spine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Switch Rx kbps",
     "type": "timeseries",
     "description": "The graph line color indicates the direction:\n<ul>\n<li style=\"color: rgb(192 216 255)\" >Light blue: spine -> leaf</li>\n<li style=\"color: rgb(31 96 196)\">Dark blue : leaf -> spine</li>\n</ul>",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_rx_kbps{switch=~\"$spine_switch\"}) by (switch, port)",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_rx_kbps{switch=~\"$switch\"}) by (switch, port)",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      }
     ]
    },
    {
     "title": "Switch Tx kbps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_tx_kbps{switch=~\"$spine_switch\"}) by (switch, port)",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_tx_kbps{switch=~\"$switch\"}) by (switch, port)",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      }
     ]
    },
    {
     "title": "Switch Rx PFC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(irate(linkmon_switch_rx_pfc{switch=~\"$spine_switch\"}[$__rate_interval])) by (switch, port) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(irate(linkmon_switch_rx_pfc{switch=~\"$switch\"}[$__rate_interval])) by (switch, port) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      }
     ]
    },
    {
     "title": "Switch Tx PFC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(irate(linkmon_switch_tx_pfc{switch=~\"$spine_switch\"}[$__rate_interval])) by (switch, port) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(irate(linkmon_switch_tx_pfc{switch=~\"$switch\"}[$__rate_interval])) by (switch, port) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      }
     ]
    },
    {
     "title": "Switch CRC Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(increase(linkmon_switch_crc_errors{switch=~\"$spine_switch\"}[11m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "(label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(increase(linkmon_switch_crc_errors{switch=~\"$switch\"}[11m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      }
     ]
    },
    {
     "title": "Switch Flaps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(increase(linkmon_switch_carrier_changes{switch=~\"$spine_switch\"}[10m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "(label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(increase(linkmon_switch_carrier_changes{switch=~\"$switch\"}[10m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      }
     ]
    },
    {
     "title": "Switch FEC Corrected",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(irate(linkmon_switch_delta_fec_corrected_codewords{switch=~\"$spine_switch\"}[$__rate_interval])) by (switch, port) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(irate(linkmon_switch_delta_fec_corrected_codewords{switch=~\"$switch\"}[$__rate_interval])) by (switch, port) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      }
     ]
    },
    {
     "title": "Switch FEC Uncorrected",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(increase(linkmon_switch_delta_fec_uncorrected_codewords{switch=~\"$spine_switch\"}[11m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "(label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(increase(linkmon_switch_delta_fec_uncorrected_codewords{switch=~\"$switch\"}[11m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      }
     ]
    },
    {
     "title": "Switch Out Discards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(increase(linkmon_switch_out_discards{switch=~\"$spine_switch\"}[11m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "(label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(increase(linkmon_switch_out_discards{switch=~\"$switch\"}[11m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      }
     ]
    },
    {
     "title": "Switch In Discards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(increase(linkmon_switch_in_discards{switch=~\"$spine_switch\"}[11m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "(label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(increase(linkmon_switch_in_discards{switch=~\"$switch\"}[11m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      }
     ]
    },
    {
     "title": "Switch ECN Marked Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(increase(linkmon_switch_ecn_marked_packets_tc5{switch=~\"$spine_switch\"}[11m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "(label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(increase(linkmon_switch_ecn_marked_packets_tc5{switch=~\"$switch\"}[11m])) by (switch, port)) > 0",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      }
     ]
    },
    {
     "title": "Optics Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_temperature{switch=~\"$spine_switch\"}) by (switch, port)",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_temperature{switch=~\"$switch\"}) by (switch, port)",
       "legendFormat": "{{switch}}:{{port}} -> {{switch_id}}"
      }
     ]
    },
    {
     "title": "Optics TX Current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "mamp" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_tx_current_lane1{switch=~\"$spine_switch\"}) by (switch, port)",
       "legendFormat": "Lane 1 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_tx_current_lane2{switch=~\"$spine_switch\"}) by (switch, port)",
       "legendFormat": "Lane 2 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_tx_current_lane3{switch=~\"$spine_switch\"}) by (switch, port)",
       "legendFormat": "Lane 3 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_tx_current_lane4{switch=~\"$spine_switch\"}) by (switch, port)",
       "legendFormat": "Lane 4 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_tx_current_lane1{switch=~\"$switch\"}) by (switch, port)",
       "legendFormat": "Lane 1 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_tx_current_lane2{switch=~\"$switch\"}) by (switch, port)",
       "legendFormat": "Lane 2 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_tx_current_lane3{switch=~\"$switch\"}) by (switch, port)",
       "legendFormat": "Lane 3 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_tx_current_lane4{switch=~\"$switch\"}) by (switch, port)",
       "legendFormat": "Lane 4 {{switch}}:{{port}} -> {{switch_id}}"
      }
     ]
    },
    {
     "title": "Optics RX Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_rx_power_lane1{switch=~\"$spine_switch\"}) by (switch, port)",
       "legendFormat": "Lane 1 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_rx_power_lane2{switch=~\"$spine_switch\"}) by (switch, port)",
       "legendFormat": "Lane 2 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_rx_power_lane3{switch=~\"$spine_switch\"}) by (switch, port)",
       "legendFormat": "Lane 3 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_rx_power_lane4{switch=~\"$spine_switch\"}) by (switch, port)",
       "legendFormat": "Lane 4 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_rx_power_lane1{switch=~\"$switch\"}) by (switch, port)",
       "legendFormat": "Lane 1 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_rx_power_lane2{switch=~\"$switch\"}) by (switch, port)",
       "legendFormat": "Lane 2 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_rx_power_lane3{switch=~\"$switch\"}) by (switch, port)",
       "legendFormat": "Lane 3 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_rx_power_lane4{switch=~\"$switch\"}) by (switch, port)",
       "legendFormat": "Lane 4 {{switch}}:{{port}} -> {{switch_id}}"
      }
     ]
    },
    {
     "title": "Optics TX Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_tx_power_lane1{switch=~\"$spine_switch\"}) by (switch, port)",
       "legendFormat": "Lane 1 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_tx_power_lane2{switch=~\"$spine_switch\"}) by (switch, port)",
       "legendFormat": "Lane 2 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_tx_power_lane3{switch=~\"$spine_switch\"}) by (switch, port)",
       "legendFormat": "Lane 3 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_tx_power_lane4{switch=~\"$spine_switch\"}) by (switch, port)",
       "legendFormat": "Lane 4 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_tx_power_lane1{switch=~\"$switch\"}) by (switch, port)",
       "legendFormat": "Lane 1 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_tx_power_lane2{switch=~\"$switch\"}) by (switch, port)",
       "legendFormat": "Lane 2 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_tx_power_lane3{switch=~\"$switch\"}) by (switch, port)",
       "legendFormat": "Lane 3 {{switch}}:{{port}} -> {{switch_id}}"
      },
      {
       "expr": "label_replace(label_replace(interface_watch_list{switch_id=~\"$spine_switch\"}, \"switch\", \"$1\", \"node\", \"(.*)\"), \"port\", \"$1\", \"device\", \"(.*)\") * on (switch, port) group_right(switch_id) avg(linkmon_switch_opt_tx_power_lane4{switch=~\"$switch\"}) by (switch, port)",
       "legendFormat": "Lane 4 {{switch}}:{{port}} -> {{switch_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Systems",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Rx Bytes/Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 264 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "system_network_rx_bytes_per_second{system=~\"$system\", port=~\"$system_port\"}",
       "legendFormat": "{{system}}, {{port}}"
      }
     ]
    },
    {
     "title": "System Tx Bytes/Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 264 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "system_network_tx_bytes_per_second{system=~\"$system\", port=~\"$system_port\"}",
       "legendFormat": "{{system}}, {{port}}"
      }
     ]
    },
    {
     "title": "System Tx PFC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 272 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "irate(system_network_tx_pause{system=~\"$system\", port=~\"$system_port\"}[$__rate_interval]) > 0",
       "legendFormat": "{{system}}, {{port}}"
      }
     ]
    },
    {
     "title": "System Rx PFC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 272 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "irate(system_network_rx_pause{system=~\"$system\", port=~\"$system_port\"}[$__rate_interval]) > 0",
       "legendFormat": "{{system}}, {{port}}"
      }
     ]
    },
    {
     "title": "System FEC Corrected",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 280 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "irate(system_network_rx_fec_corrected_pkts{system=~\"$system\", port=~\"$system_port\"}[$__rate_interval]) > 0",
       "legendFormat": "{{system}}, {{port}}"
      }
     ]
    },
    {
     "title": "System FEC Uncorrected",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 280 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(system_network_rx_fec_uncorrected_pkts{system=~\"$system\", port=~\"$system_port\"}[$__rate_interval]) > 0",
       "legendFormat": "{{system}}, {{port}}"
      }
     ]
    },
    {
     "title": "System Err QPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 288 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "system_network_err_qps{system=~\"$system\", port=~\"$system_port\"} > 0",
       "legendFormat": "{{system}}, {{port}}"
      }
     ]
    },
    {
     "title": "System Active QPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 288 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "system_network_active_qps{system=~\"$system\", port=~\"$system_port\"}",
       "legendFormat": "{{system}}, {{port}}"
      }
     ]
    },
    {
     "title": "System Tx SEQ Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 296 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(system_network_tx_sequence_errors{system=~\"$system\", port=~\"$system_port\"}[$__rate_interval]) > 0",
       "legendFormat": "{{system}}, {{port}}"
      }
     ]
    },
    {
     "title": "System Rx SEQ Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 296 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(system_network_rx_sequence_errors{system=~\"$system\", port=~\"$system_port\"}[$__rate_interval]) > 0",
       "legendFormat": "{{system}}, {{port}}"
      }
     ]
    },
    {
     "title": "System ACK Timeouts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 304 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(system_network_ack_timeouts{system=~\"$system\", port=~\"$system_port\"}[$__rate_interval]) > 0",
       "legendFormat": "{{system}}, {{port}}"
      }
     ]
    },
    {
     "title": "System Bad FCS Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 304 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(system_network_rx_pkt_bad_fcs{system=~\"$system\", port=~\"$system_port\"}[$__rate_interval]) > 0",
       "legendFormat": "{{system}}, {{port}}"
      }
     ]
    }
   ]
  }
 ]
}