{
 "title": "Workflow Overview",
 "description": "Overview of a workflow's jobs",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(namespace_reservation,namespace)"
    }
   },
   {
    "name": "wflow",
    "query": {
     "query": "wsjob_annotation{namespace=~\"$namespace\", start!=\"\", end=\"\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "First Job Start",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "group by (start) (wsjob_annotation{cerebras_workflow_id=~\"$wflow\", start!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum by (cerebras_workflow_id, job_type) (group by (cerebras_workflow_id, name, job_type) (last_over_time(wsjob_annotation{cerebras_workflow_id=~\"$wflow\"}[$__range])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (cerebras_workflow_id, job_type) (last_over_time(wsjob_annotation{cerebras_workflow_id=~\"$wflow\", current_status=\"Failed\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Runs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count_over_time({metric=\"auto_restart_reason\"} | json | labels_workflow_id=~\"$wflow\"[$__range]))"
    }
   ]
  },
  {
   "title": "Failed Runs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count_over_time({metric=\"auto_restart_reason\"} | json | labels_workflow_id=~\"$wflow\" | labels_status=~\".*fail.*\" [$__range]))"
    }
   ]
  },
  {
   "title": "Last Job End",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (end) (wsjob_annotation{cerebras_workflow_id=~\"$wflow\", end!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "group by (cerebras_workflow_id, name, job_type, system_count, start, end, current_status) (wsjob_annotation{cerebras_workflow_id=~\"$wflow\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "group by (cerebras_workflow_id, name, job_type, system_count, start) (last_over_time(wsjob_annotation{cerebras_workflow_id=~\"$wflow\", start!=\"\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "group by (cerebras_workflow_id, name, job_type, system_count, end) (last_over_time(wsjob_annotation{cerebras_workflow_id=~\"$wflow\", end!=\"\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "group by (cerebras_workflow_id, name, job_type, system_count, current_status) (wsjob_annotation{cerebras_workflow_id=~\"$wflow\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "{metric=\"auto_restart_job\"} | json | labels_workflow_id=~\"$wflow\" | label_format cerebras_workflow_id=labels_workflow_id,name=labels_job_id,run_number=labels_run_number"
    }
   ]
  },
  {
   "title": "Runs",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{metric=\"auto_restart_reason\"} | json | labels_workflow_id=~\"$wflow\" | label_format cerebras_workflow_id=labels_workflow_id"
    }
   ]
  }
 ]
}