apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cluster-tools-installer
  namespace: $NAMESPACE
  labels:
    app: cluster-tools-installer
spec:
  selector:
    matchLabels:
      app: cluster-tools-installer
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "34%"
  template:
    metadata:
      labels:
        app: cluster-tools-installer
    spec:
      nodeSelector:
        k8s.cerebras.com/node-role-management: ''
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/unreachable
        operator: Exists
        effect: NoSchedule
      initContainers:
      - name: init-container
        image: registry.local/alpine-containerd:$TAG
        imagePullPolicy: IfNotPresent
        command: ["bash", "/cluster-mgmt-scripts/cluster-tools-installer.sh"]
        env:
        - name: LEAD_MGMT_NODE
          value: $LEAD_MGMT_NODE
        - name: LEAD_MGMT_NODE_IP
          value: $LEAD_MGMT_NODE_IP
        - name: SYSTEM_NAMESPACE
          value: $SYSTEM_NAMESPACE
        - name: DEPLOY_NAMESPACE
          value: $DEPLOY_NAMESPACE
        - name: NAMESPACE
          value: $NAMESPACE
        - name: INITIAL_DEPLOY
          value: "$INITIAL_DEPLOY"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
          - name: host-root
            mountPath: /host-root/
          - name: scripts
            mountPath: /cluster-mgmt-scripts
          - name: sshkey-secret-volume
            readOnly: true
            mountPath: "/etc/sshkey-secret-volume"
      containers:
      - name: main
        image: registry.local/alpine-containerd:$TAG
        command: ["sleep", "infinity"]
      terminationGracePeriodSeconds: 1
      priorityClassName: system-node-critical
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory
        - name: scripts
          configMap:
            name: cluster-tools-installer-scripts
            items:
            - key: cluster-tools-installer.sh
              path: cluster-tools-installer.sh
        - name: sshkey-secret-volume
          secret:
            secretName: cerebras-sshkey-pair
            defaultMode: 384

