/*
Copyright 2022 Cerebras Systems, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "cerebras.com/job-operator/apis/namespace/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNamespaceReservations implements NamespaceReservationInterface
type FakeNamespaceReservations struct {
	Fake *FakeNamespaceV1
}

var namespacereservationsResource = v1.SchemeGroupVersion.WithResource("namespacereservations")

var namespacereservationsKind = v1.SchemeGroupVersion.WithKind("NamespaceReservation")

// Get takes name of the namespaceReservation, and returns the corresponding namespaceReservation object, and an error if there is any.
func (c *FakeNamespaceReservations) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.NamespaceReservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(namespacereservationsResource, name), &v1.NamespaceReservation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NamespaceReservation), err
}

// List takes label and field selectors, and returns the list of NamespaceReservations that match those selectors.
func (c *FakeNamespaceReservations) List(ctx context.Context, opts metav1.ListOptions) (result *v1.NamespaceReservationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(namespacereservationsResource, namespacereservationsKind, opts), &v1.NamespaceReservationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.NamespaceReservationList{ListMeta: obj.(*v1.NamespaceReservationList).ListMeta}
	for _, item := range obj.(*v1.NamespaceReservationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested namespaceReservations.
func (c *FakeNamespaceReservations) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(namespacereservationsResource, opts))
}

// Create takes the representation of a namespaceReservation and creates it.  Returns the server's representation of the namespaceReservation, and an error, if there is any.
func (c *FakeNamespaceReservations) Create(ctx context.Context, namespaceReservation *v1.NamespaceReservation, opts metav1.CreateOptions) (result *v1.NamespaceReservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(namespacereservationsResource, namespaceReservation), &v1.NamespaceReservation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NamespaceReservation), err
}

// Update takes the representation of a namespaceReservation and updates it. Returns the server's representation of the namespaceReservation, and an error, if there is any.
func (c *FakeNamespaceReservations) Update(ctx context.Context, namespaceReservation *v1.NamespaceReservation, opts metav1.UpdateOptions) (result *v1.NamespaceReservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(namespacereservationsResource, namespaceReservation), &v1.NamespaceReservation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NamespaceReservation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNamespaceReservations) UpdateStatus(ctx context.Context, namespaceReservation *v1.NamespaceReservation, opts metav1.UpdateOptions) (*v1.NamespaceReservation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(namespacereservationsResource, "status", namespaceReservation), &v1.NamespaceReservation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NamespaceReservation), err
}

// Delete takes name of the namespaceReservation and deletes it. Returns an error if one occurs.
func (c *FakeNamespaceReservations) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(namespacereservationsResource, name, opts), &v1.NamespaceReservation{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNamespaceReservations) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(namespacereservationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.NamespaceReservationList{})
	return err
}

// Patch applies the patch and returns the patched namespaceReservation.
func (c *FakeNamespaceReservations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.NamespaceReservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(namespacereservationsResource, name, pt, data, subresources...), &v1.NamespaceReservation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NamespaceReservation), err
}
