apiVersion: "jobs.cerebras.com/v1"
kind: WSJob
metadata:
  name: wsjob-fail
  namespace: job-operator
spec:
  runPolicy:
    cleanPodPolicy: Running
    ttlSecondsAfterFinished: 300
  numWafers: 3
  wsReplicaSpecs:
    Weight:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: ws
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - "sleep"
                - "10"
    Command:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: ws
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - "/bin/sh"
                - "-c"
                - "sleep 5; exit 1"
    Activation:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: ws
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - "sleep"
                - "10"
    BroadcastReduce:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: ws
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - "sleep"
                - "1"
