apiVersion: "jobs.cerebras.com/v1"
kind: WSJob
metadata:
  name: wsjob-multus
  namespace: job-operator
spec:
  runPolicy:
    cleanPodPolicy: Running
    ttlSecondsAfterFinished: 300
  numWafers: 0
  wsReplicaSpecs:
    Coordinator:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          Annotations:
            k8s.v1.cni.cncf.io/networks: job-operator/nodegroup0-memory
          containers:
            - name: ws
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - "sleep"
                - "300"
              readinessProbe:
                exec:
                  command:
                    - "ls"
                    - "."
