ARG BASE=alpine:3.16.2
FROM ${BASE}


# Add get-cerebras-token binary
COPY get-cerebras-token /usr/local/bin/
RUN chmod +x /usr/local/bin/get-cerebras-token

RUN apk update
RUN apk add \
    bash \
    jq \
    curl