# Generated by Django 2.1.15 on 2024-07-07 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentCtx',
            fields=[
                ('ctx_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('cluster_name', models.CharField(max_length=128)),
                ('deployable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('device_type', models.CharField(max_length=2)),
                ('device_role', models.CharField(default='', max_length=2)),
                ('deployment_stage', models.IntegerField(default=None, null=True)),
                ('deployment_status', models.IntegerField(default=0, null=True)),
                ('deployment_msg', models.CharField(default='', max_length=1024)),
                ('deleted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('swapped_with', models.CharField(default='', max_length=128)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='db.DeploymentProfile')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceProperty',
            fields=[
                ('prop_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=256)),
                ('property_attribute', models.CharField(max_length=64)),
                ('property_value', models.CharField(max_length=128)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='db.Device')),
            ],
        ),
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attr', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=16)),
                ('message', models.CharField(default='', max_length=256)),
                ('detail', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='db.Device')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDeploymentStage',
            fields=[
                ('stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('status', models.IntegerField(default=0)),
                ('section', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='deploymentctx',
            name='current_stage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.ProfileDeploymentStage'),
        ),
        migrations.AddField(
            model_name='deploymentctx',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.DeploymentProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceproperty',
            unique_together={('device', 'property_name', 'property_attribute')},
        ),
    ]
