# Generated by Django 4.2.13 on 2024-07-08 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_baseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src_if', models.CharField(max_length=255)),
                ('dst_name', models.CharField(max_length=255)),
                ('dst_if', models.CharField(default='', max_length=255)),
                ('speed', models.IntegerField()),
                ('dst_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dst_links', to='db.device')),
                ('src_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_links', to='db.device')),
            ],
            options={
                'unique_together': {('src_device', 'src_if')},
            },
        ),
    ]
