# Generated by Django 2.1.15 on 2024-08-28 13:45

from django.db import migrations, models


def update_origin(apps, schema_editor):
    Link = apps.get_model('db', 'Link')
    Link.objects.update(origin='import')


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='origin',
            field=models.CharField(default='import', max_length=64),
        ),
        migrations.RunPython(update_origin),
    ]

