# Generated by Django 2.1.15 on 2024-11-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_link_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='active',
        ),
        migrations.RemoveField(
            model_name='device',
            name='swapped_with',
        ),
        migrations.RemoveField(
            model_name='device',
            name='deleted',
        ),
        migrations.AddField(
            model_name='device',
            name='deployment_update_time',
            field=models.DateTimeField(null=True),
        ),
    ]
