# Generated by Django 2.1.15 on 2025-05-02 07:12

from django.db import migrations

def update_credo_device_type(apps, schema_editor):
    DeviceProperty = apps.get_model('db', 'DeviceProperty')
    for prop in DeviceProperty.objects.filter(property_name="vendor", property_attribute="name", property_value="CR"):
        prop.device.device_type = "PR"
        prop.device.save()

class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_device_deploy_updatetime'),
    ]

    operations = [
        migrations.RunPython(update_credo_device_type),
    ]
