# Generated by Django 4.2.17 on 2025-05-16 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_update_credo_devicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('dns_name', models.CharField(blank=True, max_length=128, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('management_vip', models.CharField(blank=True, max_length=128, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='db.deploymentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('controlplane', models.BooleanField(default=False)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_devices', to='db.cluster')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_device', to='db.device')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cluster',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('profile',),
                                               name='db_cluster_primary_unique'),
        ),
    ]
