# Generated by Django 4.2.17 on 2025-05-29 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0007_init_cluster_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterUpgrade",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "upgrade_pkg_path",
                    models.CharField(
                        help_text="Path to the directory or file containing upgrade packages and manifests",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "NOT_STARTED"),
                            ("DEST_CLUSTER_UPGRADED", "DEST_CLUSTER_UPGRADED"),
                            ("MIGRATING_BATCHES", "MIGRATING_BATCHES"),
                            ("SOURCE_CLUSTER_UPGRADED", "SOURCE_CLUSTER_UPGRADED"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="NOT_STARTED",
                        help_text="Current status/stage of the overall upgrade process",
                        max_length=64,
                    ),
                ),
                (
                    "data_preparation_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "NOT_STARTED"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="NOT_STARTED",
                        help_text="Status of data preparation (CephFS, registry, K8s state sync)",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dest_cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrade_dests",
                        to="db.cluster",
                    ),
                ),
                (
                    "source_cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrade_sources",
                        to="db.cluster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClusterUpgradeBatch",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "NOT_STARTED"),
                            ("TAINT_COMPLETED", "TAINT_COMPLETED"),
                            ("QUIESCE_COMPLETED", "QUIESCE_COMPLETED"),
                            ("MIGRATE_IN_PROGRESS", "MIGRATE_IN_PROGRESS"),
                            ("MIGRATE_COMPLETED", "MIGRATE_COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="NOT_STARTED",
                        help_text="Status of this batch",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "upgrade_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="db.clusterupgrade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClusterUpgradeBatchDevice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        help_text="Status of this device's processing within the batch",
                        max_length=32,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        blank=True,
                        help_text="The specific sub-step the device is in, e.g., 'removed_from_src_k8s', 'os_patched', 'added_to_dst_k8s'",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Error message or other status details for this device's step",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrade_entries_in_batches",
                        to="db.device",
                    ),
                ),
                (
                    "upgrade_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_devices",
                        to="db.clusterupgradebatch",
                    ),
                ),
            ],
            options={
                "unique_together": {("upgrade_batch", "device")},
            },
        ),
    ]
