# Generated by Django 5.2.1 on 2025-06-17 13:19

from django.db import migrations, models

def update_int_role(apps, schema_editor):
    Link = apps.get_model('db', 'Link')
    Link.objects.update(src_if_role='data')
    Link.objects.update(dst_if_role='data')

class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_clusterupgrade_clusterupgradebatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='dst_if_role',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='link',
            name='src_if_role',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RunPython(update_int_role),
    ]
