# Generated by Django 5.2.1 on 2025-08-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_pdu_to_peripheral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterupgrade',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('DEST_CLUSTER_UPGRADED', 'DEST_CLUSTER_UPGRADED'), ('MIGRATING_BATCHES', 'MIGRATING_BATCHES'), ('SOURCE_CLUSTER_UPGRADED', 'SOURCE_CLUSTER_UPGRADED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('FAILED', 'FAILED')], default='NOT_STARTED', help_text='Current status/stage of the overall upgrade process', max_length=64),
        ),
    ]
