# Generated by Django 5.2.1 on 2025-08-13 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_alter_clusterupgrade_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevationEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevations', to='db.deploymentprofile')),
            ],
            options={
                'unique_together': {('name', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='DeviceSpecEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=2)),
                ('role', models.CharField(default='', max_length=2)),
                ('count', models.PositiveIntegerField()),
                ('name_format', models.CharField(blank=True, max_length=100, null=True)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('elevation_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_specs', to='db.elevationentity')),
            ],
        ),
        migrations.CreateModel(
            name='RackEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('part_number', models.CharField(max_length=128)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('elevation_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='db.elevationentity')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='db.deploymentprofile')),
            ],
            options={
                'unique_together': {('name', 'profile')},
            },
        ),
        migrations.AlterField(
            model_name='rackentity',
            name='properties',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
