# Generated by Django 4.2.17 on 2025-09-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0012_elevationentity_devicespecentity_rackentity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clusterupgradebatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "NOT_STARTED"),
                    ("TAINT_COMPLETED", "TAINT_COMPLETED"),
                    ("QUIESCE_COMPLETED", "QUIESCE_COMPLETED"),
                    ("MIGRATE_STARTED", "MIGRATE_STARTED"),
                    (
                        "UPDATE_DEVICE_ASSOCIATION_IN_PROGRESS",
                        "UPDATE_DEVICE_ASSOCIATION_IN_PROGRESS",
                    ),
                    (
                        "UPDATE_DEVICE_ASSOCIATION_COMPLETED",
                        "UPDATE_DEVICE_ASSOCIATION_COMPLETED",
                    ),
                    (
                        "UPDATE_DEVICE_ASSOCIATION_FAILED",
                        "UPDATE_DEVICE_ASSOCIATION_FAILED",
                    ),
                    ("MIGRATE_OUT_IN_PROGRESS", "MIGRATE_OUT_IN_PROGRESS"),
                    ("MIGRATE_OUT_COMPLETED", "MIGRATE_OUT_COMPLETED"),
                    ("MIGRATE_OUT_FAILED", "MIGRATE_OUT_FAILED"),
                    (
                        "SECURITY_PATCH_SERVERS_IN_PROGRESS",
                        "SECURITY_PATCH_SERVERS_IN_PROGRESS",
                    ),
                    (
                        "SECURITY_PATCH_SERVERS_COMPLETED",
                        "SECURITY_PATCH_SERVERS_COMPLETED",
                    ),
                    ("SECURITY_PATCH_SERVERS_FAILED", "SECURITY_PATCH_SERVERS_FAILED"),
                    ("UPGRADE_SYSTEMS_IN_PROGRESS", "UPGRADE_SYSTEMS_IN_PROGRESS"),
                    ("UPGRADE_SYSTEMS_COMPLETED", "UPGRADE_SYSTEMS_COMPLETED"),
                    ("UPGRADE_SYSTEMS_FAILED", "UPGRADE_SYSTEMS_FAILED"),
                    ("MIGRATE_IN_IN_PROGRESS", "MIGRATE_IN_IN_PROGRESS"),
                    ("MIGRATE_IN_COMPLETED", "MIGRATE_IN_COMPLETED"),
                    ("MIGRATE_IN_FAILED", "MIGRATE_IN_FAILED"),
                    (
                        "COMPLETE_BATCH_MIGRATION_FAILED",
                        "COMPLETE_BATCH_MIGRATION_FAILED",
                    ),
                    ("MIGRATE_COMPLETED", "MIGRATE_COMPLETED"),
                    ("FAILED", "FAILED"),
                ],
                default="NOT_STARTED",
                help_text="Status of this batch",
                max_length=64,
            ),
        ),
    ]
