{
 "title": "Cluster Health Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "stamp",
    "query": {
     "query": "label_values(stamp_config{stamp=~\"$available_stamps\"},stamp)"
    }
   },
   {
    "name": "nodes",
    "query": {
     "query": "label_values(stamp_config{stamp=~\"$stamp\"},node)"
    }
   },
   {
    "name": "switches",
    "query": {
     "query": "label_values(stamp_config{stamp=~\"$stamp\"},switch)"
    }
   },
   {
    "name": "systems",
    "query": {
     "query": "label_values(stamp_config{stamp=~\"$stamp\"},system)"
    }
   },
   { "name": "available_stamps", "query": ".*" },
   { "name": "glitch_thresh", "query": "1" },
   { "name": "current_thresh", "query": "380" },
   { "name": "voltage_thresh", "query": "0.7" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "Summary of device health for the full cluster"
   }
  },
  {
   "title": "Systems - Full Cluster",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(system_overall_health * on (system) (stamp_config{system!=\"\", stamp=~\"$available_stamps\"})) by (system) == bool 1) + sum(max(system_overall_health * on (system) (stamp_config{system!=\"\", stamp=~\"$available_stamps\"})) by (system) == bool 2)",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(group((system_overall_health * on (system) (stamp_config{system!=\"\", stamp=~\"$available_stamps\"}) != 1) and (system_overall_health * on (system) (stamp_config{system!=\"\", stamp=~\"$available_stamps\"}) != 2) and (system_overall_health * on (system) (stamp_config{system!=\"\", stamp=~\"$available_stamps\"}) != -1)) by (system) or group by (system) (system_overall_health) != bool(1))",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "System status by stamp",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (stamp) (max(system_overall_health * on (system) group_left (stamp) (stamp_config{system!=\"\", stamp=~\"$available_stamps\"})) by (system, stamp) == bool 2) + sum by (stamp) (max(system_overall_health * on (system) group_left (stamp) (stamp_config{system!=\"\", stamp=~\"$available_stamps\"})) by (system, stamp) == bool 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (stamp) (((group((system_overall_health != 1) and (system_overall_health != 2) and (system_overall_health != -1)) by (system)) or (group by (system) (system_overall_health) != bool(1))) * on (system) group_left (stamp) (stamp_config{system!=\"\", stamp=~\"$available_stamps\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes - Full Cluster",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(stamp_config{node!=\"\", stamp=~\"$available_stamps\"})",
     "legendFormat": "total_nodes"
    },
    {
     "expr": "count(group by (node) ((kube_node_status_condition{node!=\"\", condition=~\"ClusterMgmt.*|ClusterDeploy.*|Csadm.*\", condition!~\".*NodeNIC.*\", condition!~\".*NodeSwitchPortError\", status=\"true\"} > 0) * on(node) group_left (stamp) group by (node,stamp) (stamp_config{node!=\"\", stamp=~\"$available_stamps\"}))) or vector(0)",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "Node status by stamp",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (stamp) (group by (node, stamp) ((kube_node_status_condition{node!=\"\", condition=~\"ClusterMgmt.*|ClusterDeploy.*|Csadm.*\", condition!~\".*NodeNIC.*\", condition!~\".*NodeSwitchPortError\", status=\"true\"} > 0) * on(node) group_left (stamp) group by (node,stamp) (stamp_config{node!=\"\", stamp=~\"$available_stamps\"})))",
     "legendFormat": "Unhealthy {{stamp}}"
    },
    {
     "expr": "sum by (stamp) (stamp_config{node!=\"\", stamp=~\"$available_stamps\"})",
     "legendFormat": "all {{stamp}}"
    }
   ]
  },
  {
   "title": "Switch Links - Full Cluster",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(interface_watch_list{stamp=~\"$available_stamps\"})",
     "legendFormat": "total_links"
    },
    {
     "expr": "count((group by (ifName, switch_id) (min_over_time(ifOperStatus[5m])!=1) or (group by (ifName, switch_id) (changes(ifLastChange[10m])>0) * 2) or (group by (ifName, switch_id)  (label_replace(label_replace(((min_over_time(linkmon_switch_oper_status[5m]) != 1)) or ((changes(linkmon_switch_carrier_changes[10m]) > 0) * 2) , \"ifName\", \"$1\", \"port\", \"(.*)\"), \"switch_id\", \"$1\", \"switch\", \"(.*)\")))) * on (ifName, switch_id) group_left (conn_type, node, device) (interface_watch_list{stamp=~\"$available_stamps\"} unless on (node) (kube_node_status_condition{condition=\"Ready\",status=\"true\"} == 0 or on (node) kube_node_spec_taint{job=\"kube-state-metrics\",key=\"node.kubernetes.io/unreachable\",effect=\"NoSchedule\"} == 1 or on (node) (label_replace((system_overall_health != 1 and system_overall_health != 2), \"node\", \"$1\", \"system\", \"(.*)\"))))) or vector(0)",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "Switch Status by stamp",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "count((group by (ifName, switch_id) (ifOperStatus!=1) or (group by (ifName, switch_id)  (label_replace(label_replace(((linkmon_switch_oper_status != 1)) , \"ifName\", \"$1\", \"port\", \"(.*)\"), \"switch_id\", \"$1\", \"switch\", \"(.*)\")))) * on (ifName, switch_id) group_left (conn_type, node, device, stamp) (interface_watch_list{stamp=~\"$available_stamps\"}) unless on (node) (kube_node_status_condition{condition=\"Ready\",status=\"true\", node=~\"$nodes\"} == 0 or on (node) kube_node_spec_taint{job=\"kube-state-metrics\",key=\"node.kubernetes.io/unreachable\",effect=\"NoSchedule\", node=~\"$nodes\"} == 1) ) by (stamp)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (stamp)(\n(\n((group by (ifName, switch_id) (changes(ifLastChange[10m])>0) ) or (group by (ifName, switch_id)  (label_replace(label_replace(((changes(linkmon_switch_carrier_changes[10m]) > 0) ) , \"ifName\", \"$1\", \"port\", \"(.*)\"), \"switch_id\", \"$1\", \"switch\", \"(.*)\"))))\n\nunless\n\n(group by (ifName, switch_id) (min_over_time(ifOperStatus[10m])!=1) or (group by (ifName, switch_id)  (label_replace(label_replace(((min_over_time(linkmon_switch_oper_status[10m]) != 1)) , \"ifName\", \"$1\", \"port\", \"(.*)\"), \"switch_id\", \"$1\", \"switch\", \"(.*)\"))))\n)\n\n\n* on (ifName, switch_id) group_left (conn_type, node, device, stamp) ((interface_watch_list{stamp=~\"$available_stamps\"}) unless on (node) (kube_node_status_condition{condition=\"Ready\",status=\"true\", node=~\"$nodes\"} == 0 or on (node) kube_node_spec_taint{job=\"kube-state-metrics\",key=\"node.kubernetes.io/unreachable\",effect=\"NoSchedule\", node=~\"$nodes\"} == 1))\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(interface_watch_list{stamp=~\"$available_stamps\"}) by (stamp)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Selected Stamp - Systems - Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 },
   "options": {
    "content": "Summary of system health for the selected stamp"
   }
  },
  {
   "title": "System status buckets",
   "type": "stat",
   "description": "status of all systems at the last timestamp of the selected range ",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count((system_overall_health{system=~\"$systems\"} == 1) or (system_overall_health{system=~\"$systems\"} == 2))) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(system_overall_health{system=~\"$systems\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(avg_over_time((sum((group(wsjob_system_grant{system=~\"$systems\"}) by (system)) or (sum(0*system_label) by (system))) / count(group(namespace_reserved_system{system=~\"$systems\"}) by (system)))[$__range:$__rate_interval]) *100, 100)",
     "legendFormat": "Utilized Percent"
    },
    {
     "expr": "avg_over_time((sum(group(wsjob_system_grant{system=~\"$systems\"}) by (system)) or sum(sum(system_label*0) by (system)))[$__range:$__rate_interval]) * (${__to:date:seconds}-${__from:date:seconds})/3600",
     "legendFormat": "Utilized Hours"
    }
   ]
  },
  {
   "title": "System Status over time",
   "type": "timeseries",
   "description": "status of all systems at the last timestamp of the selected range ",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(max(system_overall_health{system=~\"$systems\"}) by (system) == bool 2) + sum(max(system_overall_health{system=~\"$systems\"}) by (system) == bool 1)",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(group((system_overall_health{system=~\"$systems\"} != 1) and (system_overall_health{system=~\"$systems\"} != 2) and (system_overall_health{system=~\"$systems\"} != -1)) by (system) or group by (system) (system_overall_health{system=~\"$systems\"}) != bool(1))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Selected Stamp - Nodes - Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 45 },
   "options": {
    "content": "Summary of node health for the selected stamp"
   }
  },
  {
   "title": "Node status buckets",
   "type": "stat",
   "description": "Nodes with multiple conditions may be double counted",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (node) ((kube_node_status_condition{node=~\"$nodes\", condition=~\"ClusterMgmt.*|ClusterDeploy.*|Csadm.*\", condition!~\".*NodeNIC.*\", condition!~\".*NodeSwitchPortError\", status=\"true\"} > 0) * on(node) group_left (stamp) group by (node,stamp) (stamp_config{node=~\"$nodes\"}))) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count ((((group by (node,condition) (kube_node_status_condition{node=~\"$nodes\", condition=~\".*Node(NIC|SwitchPort)Error.*\", status=\"true\"} > 0)) or on (node) (group by (node,condition) (label_replace(\n    \n    (node_ipmi_health_status{category=\"Overall\", node=~\"$nodes\"} != 0) and on (node) ((node_ipmi_health_status{category=\"Power supply\", node=~\"$nodes\"} != 0) or on (node) (node_ipmi_health_status{category=\"CPU\", node=~\"$nodes\"} != 0 or node_ipmi_health_status{category=\"Processor\", node=~\"$nodes\"} != 0) or on (node) (node_ipmi_health_status{category=\"Fan\", node=~\"$nodes\"} != 0) or on (node) (node_ipmi_health_status{category=\"Memory\", node=~\"$nodes\"} != 0) or on (node) (node_ipmi_health_status{category=\"Temperatures\", node=~\"$nodes\"} != 0) or on (node) (node_ipmi_health_status{category=\"Storage\", node=~\"$nodes\"} != 0))\n\n\n    , \"condition\", \"IPMIUnhealthy\", \"\", \"\"))))     unless on (node)\n    group by (node) (kube_node_status_condition{node=~\"$nodes\", condition=~\"ClusterMgmt.*|ClusterDeploy.*|Csadm.*\", condition!~\".*NodeNIC.*\", condition!~\".*NodeSwitchPortError\", status=\"true\"} > 0) \n     * on(node) group_left (stamp) stamp_config{node=~\"$nodes\"})\n    \n\n    )  or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(stamp_config{node=~\"$nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node status over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 47 },
   "targets": [
    {
     "expr": "count(stamp_config{node=~\"$nodes\"}) - (count((kube_node_status_condition{node=~\"$nodes\", condition=~\"ClusterMgmt.*|ClusterDeploy.*|Csadm.*\", condition!~\".*NodeNIC.*\", condition!~\".*NodeSwitchPortError\", status=\"true\"} > 0) * on(node) group_left (stamp) stamp_config{node=~\"$nodes\"}) or vector(0)) - (count  (((group by (node,condition) (kube_node_status_condition{node=~\"$nodes\", condition=~\".*Node(NIC|SwitchPort)Error\", status=\"true\"} > 0)) or on (node) (group by (node,condition) (label_replace(((node_ipmi_health_status{category=\"Overall\", node=~\"$nodes\"} != bool 0) > 0) , \"condition\", \"IPMIUnhealthy\", \"\", \"\")))  ) * on(node) group_left (stamp) group by (node, stamp) (stamp_config{node=~\"$nodes\"})))",
     "legendFormat": "OK"
    },
    {
     "expr": "count(group by (node) ((kube_node_status_condition{node=~\"$nodes\", condition=~\"ClusterMgmt.*|ClusterDeploy.*|Csadm.*\", condition!~\".*NodeNIC.*\", condition!~\".*NodeSwitchPortError\", status=\"true\"} > 0) * on(node) group_left (stamp) group by (node,stamp) (stamp_config{node=~\"$nodes\"}))) or vector(0)",
     "legendFormat": "Error"
    },
    {
     "expr": "count  (((group by (node,condition) (kube_node_status_condition{node=~\"$nodes\", condition=~\".*Node(NIC|SwitchPort)Error\", status=\"true\"} > 0)) or on (node) (group by (node,condition) (label_replace(((node_ipmi_health_status{category=\"Overall\", node=~\"$nodes\"} != bool 0) > 0) , \"condition\", \"IPMIUnhealthy\", \"\", \"\")))  ) * on(node) group_left (stamp) group by (node, stamp) (stamp_config{node=~\"$nodes\"}))\n",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Selected Stamp - Switches - Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 60 },
   "options": {
    "content": "Status of switch stat collection services"
   }
  },
  {
   "title": "Monitoring Status",
   "type": "stat",
   "description": "Up if at least one switch is returning SNMP results and at least one SNMP query is recorded in the database",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(scalar(count(up{job=\"snmp\"}>0)) * scalar(count(ifOperStatus))) >bool 0",
     "legendFormat": "SNMP"
    },
    {
     "expr": "(scalar(up{container=\"cluster-mgmt-linkmon-switch\"}) * scalar(count(linkmon_switch_oper_status))) >bool 0",
     "legendFormat": "Linkmon (CLI)"
    }
   ]
  },
  {
   "title": "network_config.json Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent(absent(interface_watch_list)) or on () vector(0)",
     "legendFormat": "File exists"
    },
    {
     "expr": "absent(interface_watch_list_errors) or on () vector(0)",
     "legendFormat": "File is valid"
    }
   ]
  },
  {
   "title": "SNMP Switch Monitor Count",
   "type": "stat",
   "description": "Number of switches currently responding to SNMP queries and number of switches listed in network_config.json",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"snmp\", switch_id=~\"$switches\"}>0)",
     "legendFormat": "Scraped"
    },
    {
     "expr": "count(up{job=\"snmp\", switch_id=~\"$switches\"})",
     "legendFormat": "In watch list"
    }
   ]
  },
  {
   "title": "SNMP Switch - Data Timestamps",
   "type": "stat",
   "description": "Oldest and newest timestamp of the latest available switch response to a standard query",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000*max(timestamp(ifOperStatus{switch_id=~\"$switches\"}))",
     "legendFormat": "Newest"
    },
    {
     "expr": "min(timestamp(ifOperStatus{switch_id=~\"$switches\"}))*1000",
     "legendFormat": "Oldest"
    }
   ]
  },
  {
   "title": "Linkmon Switch Monitor Count",
   "type": "stat",
   "description": "Number of switches currently responding to linkmon queries and number of switches listed in network_config.json",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (switch) (linkmon_switch_oper_status{switch=~\"$switches\"}))",
     "legendFormat": "Scraped"
    },
    {
     "expr": "count(group by (switch_id) (interface_watch_list{switch_id=~\"$switches\"}))",
     "legendFormat": "In watch list"
    }
   ]
  },
  {
   "title": "Linkmon Switch - Data Timestamps",
   "type": "stat",
   "description": "Oldest and newest timestamp of the latest available switch response to a standard query",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000*max(timestamp(linkmon_switch_oper_status{switch=~\"$switches\"}))",
     "legendFormat": "Newest"
    },
    {
     "expr": "min(timestamp(linkmon_switch_oper_status{switch=~\"$switches\"}))*1000",
     "legendFormat": "Oldest"
    }
   ]
  },
  {
   "title": "network_config.json errors",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 66 },
   "targets": [
    { "expr": "interface_watch_list_errors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Selected Stamp - Systems - Action Required",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 72 },
   "options": {
    "content": "Systems requiring attention due to being in an error or down state or having failing links"
   }
  },
  {
   "title": "Unusable systems",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "(system_overall_health{system=~\"$systems\"} != 1) and (system_overall_health{system=~\"$systems\"} != 2)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Systems marked as error by csadm",
   "type": "table",
   "gridPos": { "h": 14, "w": 4, "x": 8, "y": 74 },
   "targets": [
    {
     "expr": "(system_status_condition{type=\"CsadmSystemError\", system=~\"$systems\"} > 0) unless on (system) ((system_overall_health{system=~\"$systems\"} != 1) and (system_overall_health{system=~\"$systems\"} != 2))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Down Ports",
   "type": "table",
   "gridPos": { "h": 14, "w": 5, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "(system_network_health == 0) * on (system) group_left (instance) (system_overall_health{system=~\"$systems\"} == 1 or system_overall_health{system=~\"$systems\"} == 2)",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "Flapping Ports over time range",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 74 },
   "targets": [
    {
     "expr": "sum by (system, port) (sum_over_time((idelta(system_network_flap_count{system=~\"$systems\"}[3m]) * on (system) group_left () group by (system) ((system_overall_health{system=~\"$systems\"} == 1 or (system_overall_health{system=~\"$systems\"} == 2)-1)))[$__range:])) > 0",
     "legendFormat": "flaps during query range"
    }
   ]
  },
  {
   "title": "Unreachable Ports",
   "type": "table",
   "description": "Ports that aren't responding to pings (using CPingmesh).",
   "gridPos": { "h": 14, "w": 5, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "group by (host, nic) (pingmesh:unreachable5m{host=~\"$systems\"})",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "Selected Stamp - Nodes - Action Required",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 89 },
   "options": {
    "content": "Nodes requiring attention due to being in an error or down state or having failing links, or critical overheat conditions, or other hardware problems"
   }
  },
  {
   "title": "Down",
   "type": "table",
   "description": "Unreachable, kubelet not running, or marked down by administrator",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "group by (node) ((kube_node_status_condition{node=~\"$nodes\", condition=~\"ClusterMgmt.*|ClusterDeploy.*|Csadm.*\", condition!~\".*NodeNIC.*\", condition!~\".*NodeSwitchPortError\", status=\"true\"} > 0) or on (node) kube_node_spec_taint{job=\"kube-state-metrics\",key=\"node.kubernetes.io/unreachable\",effect=\"NoSchedule\", node=~\"$nodes\"} == 1)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Down Ports",
   "type": "table",
   "gridPos": { "h": 14, "w": 4, "x": 4, "y": 91 },
   "targets": [
    {
     "expr": "(interface_watch_list:status{node=~\"$nodes\"} == 0) unless on (node) group by (node) ((kube_node_status_condition{node=~\"$nodes\", condition=~\"ClusterMgmt.*|ClusterDeploy.*|Csadm.*\", condition!~\".*NodeNIC.*\", condition!~\".*NodeSwitchPortError\", status=\"true\"} > 0) or on (node) kube_node_spec_taint{job=\"kube-state-metrics\",key=\"node.kubernetes.io/unreachable\",effect=\"NoSchedule\", node=~\"$nodes\"} == 1)",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "Flapping Ports",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 8, "y": 91 },
   "targets": [
    {
     "expr": "(increase(interface_watch_list:status_changes_total{node=~\"$nodes\"}[$__range] ) > 2) unless on (node) group by (node) ((kube_node_status_condition{node=~\"$nodes\", condition=~\"ClusterMgmt.*|ClusterDeploy.*|Csadm.*\", condition!~\".*NodeNIC.*\", condition!~\".*NodeSwitchPortError\", status=\"true\"} > 0) or on (node) kube_node_spec_taint{job=\"kube-state-metrics\",key=\"node.kubernetes.io/unreachable\",effect=\"NoSchedule\", node=~\"$nodes\"} == 1)",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "IPMI",
   "type": "table",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 91 },
   "targets": [
    {
     "expr": "node_ipmi_health_status{category=\"CPU\", node=~\"$nodes\"} == 2 or node_ipmi_health_status{category=\"Processor\", node=~\"$nodes\"} == 2",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ipmi_health_status{category=\"Fan\", node=~\"$nodes\"}  == 2",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ipmi_health_status{category=\"Memory\", node=~\"$nodes\"}  == 2",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ipmi_health_status{category=\"Temperatures\", node=~\"$nodes\"}  == 2",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ipmi_health_status{category=\"Power supply\", node=~\"$nodes\"}  == 2",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ipmi_health_status{category=\"Storage\", node=~\"$nodes\"}  == 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overheat conditions - IPMI Sensors",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_thermals_thermometer{health!=\"1\", node=~\"$nodes\"} > 0",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Overheat conditions - NIC ASIC",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 8, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_nic_stats_temperature{node=~\"$nodes\"} >= 95",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Overheat conditions - NIC Optics",
   "type": "table",
   "gridPos": { "h": 14, "w": 5, "x": 15, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_nic_stats_opt_temperature{node=~\"$nodes\"} * node_nic_stats_opt_temperature_alarm{node=~\"$nodes\"} > 0",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Unreachable Ports",
   "type": "table",
   "description": "Interfaces that aren't responding to pings (using CPingmesh).",
   "gridPos": { "h": 14, "w": 4, "x": 20, "y": 119 },
   "targets": [
    {
     "expr": "group by (host, nic) (pingmesh:unreachable5m{host=~\"$nodes\"})",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "Selected Stamp - Switches - Action Required",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 120 },
   "options": {
    "content": "Switches requiring attention due to failing links"
   }
  },
  {
   "title": "Down Ports",
   "type": "table",
   "description": "Time and duration of port issues (port is down or had one or more flaps) - only for explicitly tracked ports from the network_config.json",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "(((ifOperStatus{switch_id=~\"$switches\"})!=1) or on (switch_id, ifName)( (label_replace(label_replace((((linkmon_switch_oper_status{switch=~\"$switches\"}) != 1)) , \"ifName\", \"$1\", \"port\", \"(.*)\"), \"switch_id\", \"$1\", \"switch\", \"(.*)\")))) * on (ifName, switch_id) group_left (conn_type, node, device) (interface_watch_list{switch_id=~\"$switches\"} unless on (node) (kube_node_status_condition{condition=\"Ready\",status=\"true\", node=~\"$nodes\"} == 0 or on (node) kube_node_spec_taint{job=\"kube-state-metrics\",key=\"node.kubernetes.io/unreachable\",effect=\"NoSchedule\", node=~\"$nodes\"} == 1 or on (node) (label_replace((system_overall_health{system=~\"$systems\"} != 1 and system_overall_health{system=~\"$systems\"} != 2), \"node\", \"$1\", \"system\", \"(.*)\"))))",
     "legendFormat": "down ports"
    }
   ]
  },
  {
   "title": "Flapping Ports",
   "type": "table",
   "description": "Time and duration of port issues (port is down or had one or more flaps) - only for explicitly tracked ports from the network_config.json",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 122 },
   "targets": [
    {
     "expr": "(( (changes(ifLastChange{switch_id=~\"$switches\"}[$__range])>0) ) or on (switch_id, ifName)(  (label_replace(label_replace(((changes(linkmon_switch_carrier_changes{switch=~\"$switches\"}[$__range]) > 0) ) , \"ifName\", \"$1\", \"port\", \"(.*)\"), \"switch_id\", \"$1\", \"switch\", \"(.*)\")))) * on (ifName, switch_id) group_left (conn_type, node, device) (interface_watch_list{switch_id=~\"$switches\"} unless on (node) (kube_node_status_condition{condition=\"Ready\",status=\"true\", node=~\"$nodes\"} == 0 or on (node) kube_node_spec_taint{job=\"kube-state-metrics\",key=\"node.kubernetes.io/unreachable\",effect=\"NoSchedule\", node=~\"$nodes\"} == 1 or on (node) (label_replace((system_overall_health{system=~\"$systems\"} != 1 and system_overall_health{system=~\"$systems\"} != 2), \"node\", \"$1\", \"system\", \"(.*)\"))))",
     "legendFormat": "flapping ports"
    }
   ]
  },
  {
   "title": "Optics over error threshold temp",
   "type": "table",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(linkmon_switch_opt_temperature{switch=~\"$switches\"} > 0 , \"ifName\", \"$1\", \"port\", \"(.*)\"), \"switch_id\", \"$1\", \"switch\", \"(.*)\") * on (ifName, switch_id) group_left (conn_type, node, device) interface_watch_list{switch_id=~\".*\"} > 80",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Selected Stamp - Systems - Warnings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 144 },
   "options": {
    "content": "Systems with components that may need attention, and link conditions that do not indicate immediate issues"
   }
  },
  {
   "title": "Degraded systems",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 146 },
   "targets": [
    {
     "expr": "(system_subsystem_health{system=~\"$systems\"} != 20) * on (system) group_left () (system_overall_health{system=~\"$systems\"} == bool 2) >= 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Systems with CRC Errors",
   "type": "table",
   "gridPos": { "h": 16, "w": 5, "x": 9, "y": 146 },
   "targets": [
    {
     "expr": "increase(system_network_rx_pkt_bad_fcs{system=~\"$systems\"}[$__range]) > 0",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Systems with FEC Corrected Errors",
   "type": "table",
   "gridPos": { "h": 16, "w": 5, "x": 14, "y": 146 },
   "targets": [
    {
     "expr": "increase(system_network_rx_fec_corrected_pkts{system=~\"$systems\"}[$__range]) > 0",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Systems with FEC Uncorrected",
   "type": "table",
   "gridPos": { "h": 16, "w": 5, "x": 19, "y": 146 },
   "targets": [
    {
     "expr": "increase(system_network_rx_fec_uncorrected_pkts{system=~\"$systems\"}[$__range]) > 0",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Systems with Glitch or Power Events",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (system) (max_over_time(system_dev_stats{system=~\"$systems\", component=~\"^GLTCH_(EXCUR|TRANS).*\"}[$__range]) > $glitch_thresh)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (system) (max_over_time(system_dev_stats{system=~\"$systems\", component=~\"^VDDC.*_IOUT\"}[$__range]) > $current_thresh)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (system) (max_over_time(system_dev_stats{system=~\"$systems\", component=~\"^VDDC_ASIC.*\"}[$__range]) > $voltage_thresh)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Selected Stamp - Nodes - Warnings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 172 },
   "options": {
    "content": "Node conditions that do not indicate immediate issues"
   }
  },
  {
   "title": "IPMI",
   "type": "table",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 174 },
   "targets": [
    {
     "expr": "node_ipmi_health_status{category=\"CPU\", node=~\"$nodes\"} == 1 or node_ipmi_health_status{category=\"Processor\", node=~\"$nodes\"} == 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ipmi_health_status{category=\"Fan\", node=~\"$nodes\"}  == 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ipmi_health_status{category=\"Memory\", node=~\"$nodes\"}  == 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ipmi_health_status{category=\"Temperatures\", node=~\"$nodes\"}  == 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ipmi_health_status{category=\"Power supply\", node=~\"$nodes\"}  == 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ipmi_health_status{category=\"Storage\", node=~\"$nodes\"}  == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node FEC Corrected Errors",
   "type": "table",
   "description": "Node NIC Corrected FEC Errors",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 174 },
   "targets": [
    {
     "expr": "increase(node_nic_stats_rx_corrected_bits_phy{node=~\"$nodes\"}[$__range]) > 0",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "Node CRC Errors (Increase During Time Range)",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 174 },
   "targets": [
    {
     "expr": "increase(node_nic_stats_rx_crc_errors_phy{node=~\"$nodes\"}[$__range]) > 0",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "Node FEC Uncorrected Errors",
   "type": "table",
   "description": "Node NIC uncorrectable packet errors can cause port flaps or other network failures",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 182 },
   "targets": [
    {
     "expr": "increase(node_nic_stats_rx_pcs_symbol_err_phy{node=~\"$nodes\"}[$__range]) > 0",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "Selected Stamp - Switches - Warning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 190 }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 191 },
   "options": {
    "content": "Switch conditions that do not indicate immediate issues"
   }
  },
  {
   "title": "Optics over warning threshold temp",
   "type": "table",
   "description": "Average and top 3 warmest NICs",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(linkmon_switch_opt_temperature{switch=~\"$switches\"} > 0 , \"ifName\", \"$1\", \"port\", \"(.*)\"), \"switch_id\", \"$1\", \"switch\", \"(.*)\") * on (ifName, switch_id) group_left (conn_type, node, device) interface_watch_list{switch_id=~\".*\"} > 70",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Recently Rebooted Switches",
   "type": "table",
   "description": "Switches rebooted in the selected time range.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 184 },
   "targets": [
    {
     "expr": "group by (switch)\n    (min_over_time(linkmon_switch_uptime{switch=~\"$switches\"}[$__range]) < 3600)\n * on (switch) \n    linkmon_switch_uptime{switch=~\"$switches\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Switch CRC Errors (Increase During Time Range)",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 201 },
   "targets": [
    {
     "expr": "increase(linkmon_switch_crc_errors{switch=~\"$switches\"}[$__range]) * on (switch, port) group_left label_replace(label_replace(interface_watch_list, \"port\", \"$1\", \"ifName\", \"(.*)\"), \"switch\", \"$1\", \"switch_id\", \"(.*)\") > 0",
     "legendFormat": "{{switch}}:{{port}} ({{desc}})"
    }
   ]
  },
  {
   "title": "Switch FEC Corrected Errors",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 201 },
   "targets": [
    {
     "expr": "increase(linkmon_switch_fec_corrected_codewords{switch=~\"$switches\"}[$__range]) * on (switch, port) group_left label_replace(label_replace(interface_watch_list, \"port\", \"$1\", \"ifName\", \"(.*)\"), \"switch\", \"$1\", \"switch_id\", \"(.*)\") > 0",
     "legendFormat": "{{switch}}:{{port}} ({{desc}})"
    }
   ]
  },
  {
   "title": "Switch FEC Uncorrected Errors",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 201 },
   "targets": [
    {
     "expr": "increase(linkmon_switch_fec_uncorrected_codewords{switch=~\"$switches\"}[$__range]) * on (switch, port) group_left label_replace(label_replace(interface_watch_list, \"port\", \"$1\", \"ifName\", \"(.*)\"), \"switch\", \"$1\", \"switch_id\", \"(.*)\") > 0",
     "legendFormat": "{{switch}}:{{port}} ({{desc}})"
    }
   ]
  },
  {
   "title": "Selected Stamp - Systems - Error History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 214 }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 215 },
   "options": {
    "content": "Historical view of error events"
   }
  },
  {
   "title": "Unusable Systems - history",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 13, "x": 0, "y": 217 },
   "targets": [
    {
     "expr": "max(max_over_time(system_overall_health{system=~\"$systems\"}[10m]) != 1 and max_over_time(system_overall_health{system=~\"$systems\"}[10m]) != 2) by (system)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port Errors",
   "type": "state-timeline",
   "description": "Counts of systems with partial or total network problems",
   "gridPos": { "h": 17, "w": 11, "x": 13, "y": 217 },
   "targets": [
    {
     "expr": "((count by (system) (group by (system, port) (increase(system_network_flap_count{system=~\"$systems\"}[15m]) > 2)) < bool 12)*1 or (count by (system) (group by (system, port) (min_over_time(system_network_health{system=~\"$systems\"}[$__rate_interval]) == 0)) < bool 12)*2 or ( count by (system) (group by (system, port) (increase(system_network_flap_count{system=~\"$systems\"}[15m]) > 2)) == bool 12)*3 or (count by (system) (group by (system, port) (min_over_time(system_network_health{system=~\"$systems\"}[$__rate_interval]) * on (system) group_left () group by (system) (((system_overall_health == bool 1) or (system_overall_health == bool 2)) > 0) == 0)) == bool 12)*4) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Selected Stamp - Nodes - Error History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 234 }
  },
  {
   "title": "Node NIC Errors",
   "type": "state-timeline",
   "description": "NIC flapping or down",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(increase(interface_watch_list:status_changes_total{node=~\"$nodes\"}[15m])> bool 2) > 0",
     "legendFormat": "{{node}}:{{device}} flapping"
    },
    {
     "expr": "(min_over_time(interface_watch_list:status{node=~\"$nodes\"}[$__rate_interval]) == bool 0) > 0",
     "legendFormat": "{{node}}:{{device}} down"
    }
   ]
  },
  {
   "title": "Selected Stamp - Switches - Error History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 252 }
  },
  {
   "title": "Switch Port Errors",
   "type": "state-timeline",
   "description": "Time and duration of port issues (port is down or had one or more flaps) - only for explicitly tracked ports from the network_config.json",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 253 },
   "targets": [
    {
     "expr": "(group by (ifName, switch_id) (min_over_time(ifOperStatus{switch_id=~\"$switches\"}[$__rate_interval])!=1) or (group by (ifName, switch_id) (changes(ifLastChange[10m])>0) * 2) or (group by (ifName, switch_id)  (label_replace(label_replace(((min_over_time(linkmon_switch_oper_status[$__rate_interval]) != 1)) or ((changes(linkmon_switch_carrier_changes[10m]) > 0) * 2) , \"ifName\", \"$1\", \"port\", \"(.*)\"), \"switch_id\", \"$1\", \"switch\", \"(.*)\")))) * on (ifName, switch_id) group_left (conn_type, node, device) interface_watch_list{switch_id=~\"$switches\"}",
     "legendFormat": "{{conn_type}} {{switch_id}}:{{ifName}} ({{node}}:{{device}})"
    }
   ]
  }
 ]
}