{
 "title": "Cluster Admin Dashboard",
 "tags": [
  "cluster-mgmt",
  "deprecated"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system_filter",
    "label": "System",
    "query": {
     "query": "label_values(system_overall_health, system)"
    }
   },
   {
    "name": "subsystem_filter",
    "label": "Subsystem",
    "query": {
     "query": "label_values(system_subsystem_health, subsystem)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CS2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall CS2 Status",
   "type": "stat",
   "description": "status of all systems at the last timestamp of the selected range ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(system_overall_health{system=~\"$system_filter\"}) by (system) == bool 2)",
     "legendFormat": "DEGRADED"
    },
    {
     "expr": "sum(max(system_overall_health{system=~\"$system_filter\"}) by (system) == bool 1)",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(group((system_overall_health{system=~\"$system_filter\"} != 1) and (system_overall_health{system=~\"$system_filter\"} != 2)) by (system) or group by (system) (system_overall_health{system=~\"$system_filter\"}) != bool(1))",
     "legendFormat": "ERROR"
    },
    {
     "expr": "clamp_max(avg_over_time((\nsum((group(wsjob_system_grant{system=~\"$system_filter\"}) by (system)) or (sum(0*system_label{system=~\"$system_filter\"}) by (system))) /\ncount(group(system_label{system=~\"$system_filter\"}) by (system)) \n)[$__range:$__rate_interval]) *100, 100)\n\n",
     "legendFormat": "Utilized Percent"
    },
    {
     "expr": "avg_over_time((sum(group(wsjob_system_grant) by (system)) or sum(sum(system_label*0) by (system)))[$__range:$__rate_interval]) * (${__to:date:seconds}-${__from:date:seconds})/3600\n",
     "legendFormat": "Utilized Hours"
    }
   ]
  },
  {
   "title": "CS2 Jobs Histogram",
   "type": "timeseries",
   "description": "Number of CS2 Systems by Job",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (name, labels_k8s_cerebras_com_Model) (group by (name, system) (wsjob_system_grant{system =~\"$system_filter\"})) * on (name) group_left(labels_k8s_cerebras_com_Model) group by(name, labels_k8s_cerebras_com_Model) \n(wsjob_annotation{job_type!=\"compile\"})",
     "legendFormat": "{{labels_k8s_cerebras_com_Model}} / {{name}}"
    }
   ]
  },
  {
   "title": "CS2 Errors",
   "type": "state-timeline",
   "description": "CS2 error status timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(max_over_time(system_overall_health{system=~\"$system_filter\"}[$__rate_interval]) != 1) by (system)",
     "legendFormat": "{{system}}"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Node Warning/Errors",
   "type": "timeseries",
   "description": "K8s Nodes having error/warnings can cause scheduling failure",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(kube_node_status_condition{condition=~\"ClusterMgmt.*|ClusterDeploy.*|Csadm.*\", status=\"true\"}[$__rate_interval]) > 0",
     "legendFormat": "{{node}}/{{condition}}"
    }
   ]
  },
  {
   "title": "Root Disk Usage > 85%",
   "type": "timeseries",
   "description": "display hosts with root Disk Usage > 85%",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(label_replace(\n    (((node_filesystem_size_bytes{mountpoint=\"/\"}-node_filesystem_avail_bytes{mountpoint=\"/\"})/node_filesystem_size_bytes{mountpoint=\"/\"}) > .85),\n    \"internal_ip\", \"$1\", \"instance\", \"([^:]+):.*\"\n) * on (internal_ip) group_left (node) group(kube_node_info) by (node, internal_ip)) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "NFS Mount Errors",
   "type": "timeseries",
   "description": "Shows NFS mount errors per node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "max((max_over_time(node_nfs_server_health[$__rate_interval]) != 1) != bool 1)  by (node,volume)",
     "legendFormat": "{{node}}/{{volume}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "CS2 System Port Errors",
   "type": "timeseries",
   "description": "Breakdown of CS2 System Port Errors",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "group by (system, port) (increase(system_network_flap_count{system=~\"$system_filter\"}[$__rate_interval]) >= 2)",
     "legendFormat": "{{system}}:{{port}} flapping"
    },
    {
     "expr": "group by (system, port) (min_over_time(system_network_health{system=~\"$system_filter\"}[$__rate_interval]) == 0)",
     "legendFormat": "{{system}}:{{port}} down"
    }
   ]
  },
  {
   "title": "Node NIC Errors",
   "type": "timeseries",
   "description": "NIC flapping or down",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(increase(interface_watch_list:status_changes_total[$__rate_interval]) >= bool 2) > 0",
     "legendFormat": "{{node}}:{{device}} flapping"
    },
    {
     "expr": "(min_over_time(interface_watch_list:status[$__rate_interval]) == bool 0) > 0",
     "legendFormat": "{{node}}:{{device}} down"
    }
   ]
  },
  {
   "title": "Switch Port Problems",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "(sum (group by (ifName, switch_id) (min_over_time(ifOperStatus[10m])!=1) * on (ifName, switch_id) group_left (conn_type, node, device) interface_watch_list{switch_id!=\"\"}) by (switch_id, ifName, conn_type, node, device)> 0) or (group by (ifName, switch_id) (changes(ifLastChange[10m])>0) * on (ifName, switch_id) group_left (conn_type, node, device) interface_watch_list{switch_id!=\"\"})",
     "legendFormat": "{{conn_type}} {{switch_id}}:{{ifName}} ({{node}}/{{device}})"
    }
   ]
  }
 ]
}