{
 "title": "Cluster Control Plane Health",
 "description": "Dashboard for cluster-mgmt core components\n",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Control Plane Oncall Alerts",
     "type": "state-timeline",
     "description": "Alerts with `control_plane_oncall=\"true\"`, colored according to alertstate: <font color=\"#FF9840\">orange</font> for pending; <font color=\"#F2495C\">red</font> for firing.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "milliseconds (ms)" } },
     "targets": [
      {
       "expr": "avg without (alertstate) (ALERTS{control_plane_oncall=\"true\", alertstate=\"pending\"} or (ALERTS{control_plane_oncall=\"true\", alertstate=\"firing\"} + 1))",
       "legendFormat": "{{alertname}} {{instance}}"
      }
     ]
    },
    {
     "title": "All Other Alerts",
     "type": "state-timeline",
     "description": "Alerts with `control_plane_oncall!=\"true\"`, colored according to alertstate: <font color=\"#FF9840\">orange</font> for pending; <font color=\"#F2495C\">red</font> for firing.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "milliseconds (ms)" } },
     "targets": [
      {
       "expr": "avg without (alertstate) (ALERTS{control_plane_oncall!=\"true\", alertstate=\"pending\", alertname!=\"Watchdog\"} or (ALERTS{control_plane_oncall!=\"true\", alertstate=\"firing\", alertname!=\"Watchdog\"} + 1))",
       "legendFormat": "{{alertname}} {{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Service Pod Status", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 17 } },
  {
   "title": "API Server - Pod Status",
   "type": "table",
   "description": "API server pods status and restarts count",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"kube-apiserver.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"kube-apiserver.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Kubevip 1G - Pod Status",
   "type": "table",
   "description": "1G kube-vip pods status and restarts count",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"kube-vip-[a-zA-Z0-9]*-.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"kube-vip-[a-zA-Z0-9]*-.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Private Registry - Pod Status",
   "type": "table",
   "description": "Private registry pods status and restarts count",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"private-registry-.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"private-registry-.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Nginx - Pod Status",
   "type": "table",
   "description": "Nginx pods status and restarts count",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"ingress-nginx-controller-.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"ingress-nginx-controller-.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Etcd - Pod Status",
   "type": "table",
   "description": "Etcd pods status and restarts count",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"etcd.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"etcd.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Kubevip 100G - Pod Status",
   "type": "table",
   "description": "100G kube-vip pods status and restarts count",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"kube-vip-[a-zA-Z0-9]*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"kube-vip-[a-zA-Z0-9]*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Coredns - Pod Status",
   "type": "table",
   "description": "Coredns pods status and restarts count",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"coredns-.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"coredns-.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  { "title": "Monitoring Pod Status", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 18, "y": 36 } },
  {
   "title": "System Exporter - Pod Status",
   "type": "table",
   "description": "System exporter pods status and restarts count",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"cluster-mgmt-system-exporter-.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"cluster-mgmt-system-exporter-.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "SNMP Exporter - Pod Status",
   "type": "table",
   "description": "SNMP exporter pods status and restarts count",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"prometheus-snmp-exporter-.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"prometheus-snmp-exporter-.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Prometheus - Pod Status",
   "type": "table",
   "description": "Prometheus pods status and restarts count",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 37 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"prometheus-prometheus-prometheus-.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"prometheus-prometheus-prometheus-.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Alertmanager - Pod Status",
   "type": "table",
   "description": "Alertmanager pods status and restarts count",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"alertmanager-prometheus-alertmanager-.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"alertmanager-prometheus-alertmanager-.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Alertrouter - Pod Status",
   "type": "table",
   "description": "Alertrouter pods status and restarts count",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 49 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"alert-router-.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"alert-router-.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Grafana - Pod Status",
   "type": "table",
   "description": "Grafana pods status and restarts count",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 49 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"prometheus-grafana-.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"prometheus-grafana-.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Linkmon - Pod Status",
   "type": "table",
   "description": "Linkmon pods status and restarts count",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"cluster-mgmt-linkmon-switch-.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"cluster-mgmt-linkmon-switch-.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Loki - Pod Status",
   "type": "table",
   "description": "Loki pods status and restarts count",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 53 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"loki-.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"loki-.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Thanos Query - Pod Status",
   "type": "table",
   "description": "Thanos Query pods status and restarts count",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"thanos-query-.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"thanos-query-.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Thanos Ruler - Pod Status",
   "type": "table",
   "description": "Thanos Ruler pods status and restart counts",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"thanos-ruler-prometheus-thanos-ruler-.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"thanos-ruler-prometheus-thanos-ruler-.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Fluentbit - Pod Status",
   "type": "table",
   "description": "Fluentbit pods status and restarts count",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 57 },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{pod=~\"fluentbit-.*\"}) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Status"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{pod=~\"fluentbit-.*\"}[$__range])) by (pod) and group by (pod) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Restarts"
    }
   ]
  },
  { "title": "API Server Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 16, "y": 69 } },
  {
   "title": "API Server - Availability (30d) > 99.000%",
   "type": "stat",
   "description": "How many percent of requests (both read and write) in 30 days have been answered successfully and fast enough?",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"all\"}",
     "legendFormat": "Verbose"
    }
   ]
  },
  {
   "title": "API Server - HTTP Requests Latency by verb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "milliseconds (ms)" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_sum{job=\"apiserver\"}[$__rate_interval])) by (verb)\n/\nsum(rate(apiserver_request_duration_seconds_count{job=\"apiserver\"}[$__rate_interval])) by (verb)\n",
     "legendFormat": "{{ verb }}"
    }
   ]
  },
  {
   "title": "API Server - HTTP Requests by code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "targets": [
    {
     "expr": "sum by (code) (rate(apiserver_request_total[$__rate_interval]))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "API Server - CPU Usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"apiserver\"}[$__rate_interval]) * on(instance) group_left(node)\n  max by (node, instance) (label_replace(kube_node_info * on(node, instance) group_left(role)\n  (kube_node_role{role=\"control-plane\"}) , \"instance\", \"$1:6443\", \"internal_ip\", \"(.*)\"))\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "API Server - Memory Usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"apiserver\"} * on(instance) group_left(node)\n  max by (node, instance) (label_replace(kube_node_info * on(node) group_left(role)\n  (kube_node_role{role=\"control-plane\"}) , \"instance\", \"$1:6443\", \"internal_ip\", \"(.*)\"))\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "API Server - Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(rate(node_network_transmit_bytes_total{device!~\"lo|veth.*|docker.*|br.*|cilium.*|lxc.*\"}[$__rate_interval]) * 8 and\n  (node_network_speed_bytes == 1250000000 or node_network_speed_bytes == 125000000)) * on(instance) group_left(node)\n  max by (node, instance) (label_replace(kube_node_info * on(node) group_left(role)\n  (kube_node_role{role=\"control-plane\"}) , \"instance\", \"$1:9100\", \"internal_ip\", \"(.*)\"))\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "API Server - Network Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_bytes_total{device!~\"lo|veth.*|docker.*|br.*|cilium.*|lxc.*\"}[$__rate_interval]) * 8 and\n  (node_network_speed_bytes == 1250000000 or node_network_speed_bytes == 125000000)) * on(instance) group_left(node)\n  max by (node, instance) (label_replace(kube_node_info * on(node) group_left(role)\n  (kube_node_role{role=\"control-plane\"}) , \"instance\", \"$1:9100\", \"internal_ip\", \"(.*)\"))\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Networking - cilium + Multus + Whereabouts + RDMA",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 24, "y": 94 }
  },
  {
   "title": "Cilium",
   "type": "stat",
   "description": "Cilium pods Ready/NotReady count",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{container=\"cilium-agent\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "count(kube_node_info) - count(kube_pod_container_status_ready{container=\"cilium-agent\"})",
     "legendFormat": "NotReady"
    }
   ]
  },
  {
   "title": "Multus",
   "type": "stat",
   "description": "Multus pods Ready/NotReady count",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 95 },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{container=\"kube-multus\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "count(kube_pod_status_phase{phase=\"Pending\", pod=~\"multus-multus-ds-.*\"}) - \n  count(kube_pod_container_status_ready{container=\"kube-multus\"})\n",
     "legendFormat": "NotReady"
    }
   ]
  },
  {
   "title": "Whereabouts",
   "type": "stat",
   "description": "Whereabouts pods Ready/NotReady count",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{container=\"whereabouts\", pod!~\"whereabouts-operator-.*\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "count(kube_node_info) -\n  count(kube_pod_container_status_ready{container=\"whereabouts\", pod!~\"whereabouts-operator-.*\"})\n",
     "legendFormat": "NotReady"
    }
   ]
  },
  {
   "title": "RDMA",
   "type": "stat",
   "description": "Rdma device pods Ready/NotReady count",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 95 },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{container=\"rdma-device-plugin\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "count(kube_pod_container_state_started{container=\"rdma-device-plugin\"}) -\n  count(kube_pod_container_status_ready{container=\"rdma-device-plugin\"})\n",
     "legendFormat": "NotReady"
    }
   ]
  },
  {
   "title": "Cilium Drop Count",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "sum(increase(cilium_drop_count_total{reason=\"Missed tail call\"}[$__range])) by (node, direction, reason) > 0\n",
     "legendFormat": "{{node}}-{{direction}}-{{reason}}"
    }
   ]
  },
  {
   "title": "Unhealthy Nodes with 0 RDMA device",
   "type": "table",
   "description": "Nodes with 0 RDMA device",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 99 },
   "targets": [
    {
     "expr": "kube_node_status_capacity{resource=\"rdma_hca_devices\"} == 0",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 103 } },
  {
   "title": "Ceph - Health Status",
   "type": "stat",
   "description": "Ceph cluster health status",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 104 },
   "targets": [
    { "expr": "ceph_health_status{}", "legendFormat": "Verbose" }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 104 },
   "targets": [
    { "expr": "sum(ceph_osd_in{})", "legendFormat": "Verbose" }
   ]
  },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 104 },
   "targets": [
    { "expr": "sum(ceph_osd_out{})", "legendFormat": "Verbose" }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 104 },
   "targets": [
    { "expr": "sum(ceph_osd_up{})", "legendFormat": "Verbose" }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 104 },
   "targets": [
    { "expr": "sum(ceph_osd_down{})", "legendFormat": "Verbose" }
   ]
  },
  {
   "title": "Root Disk Usage > 85%",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(label_replace(\n  (((node_filesystem_size_bytes{mountpoint=\"/\"}-node_filesystem_avail_bytes{mountpoint=\"/\"})/node_filesystem_size_bytes{mountpoint=\"/\"}) > .85),\n  \"internal_ip\", \"$1\", \"instance\", \"([^:]+):.*\"\n) * on (internal_ip) group_left (node) group(kube_node_info) by (node, internal_ip)) by (node)\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Etcd Storage Usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{job=\"kube-etcd\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "etcd_server_quota_backend_bytes{job=\"kube-etcd\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "PVC usage by component",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (\n  kubelet_volume_stats_used_bytes{job=\"kubelet\", persistentvolumeclaim!=\"\"}\n)\n",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVC usage % by component",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  kubelet_volume_stats_capacity_bytes{job=\"kubelet\", persistentvolumeclaim!=\"\"}\n  -\n  kubelet_volume_stats_available_bytes{job=\"kubelet\", persistentvolumeclaim!=\"\"}\n)\n/ kubelet_volume_stats_capacity_bytes{job=\"kubelet\", persistentvolumeclaim!=\"\"}\n",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Ceph Pool Storage by Name",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "sum((ceph_pool_stored) *on (pool_id) group_left(name)\n  (ceph_pool_metadata{name=~\".*\"})) by (name)\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Ceph Pool Usage % by Name",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum((ceph_pool_stored) *on (pool_id) group_left(name) (ceph_pool_metadata{name=~\".*\"})) by (name) / (sum((ceph_pool_stored) *on (pool_id) group_left(name) (ceph_pool_metadata{name=~\".*\"})) by (name) + sum((ceph_pool_max_avail) *on (pool_id) group_left(name) (ceph_pool_metadata{name=~\".*\"})) by (name))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}