{
 "title": "Cluster Control Plane Summary",
 "description": "Summary dashboard for cluster control plane health signals",
 "tags": [ "cluster-mgmt" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "API Summary", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "API Server Success Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\", code=~\"2..|3..|4..\"}[5m])) / sum(rate(apiserver_request_total{job=\"apiserver\"}[5m])) * 100",
     "legendFormat": "API Server Success Rate"
    }
   ]
  },
  { "title": "Action Required", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 7 } },
  {
   "title": "Services That Are Down",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"kube-apiserver-.*\"} == 1) < 1",
     "legendFormat": "API Server"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"etcd-.*\"} == 1) < 1",
     "legendFormat": "etcd"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"coredns-.*\"} == 1) < 1",
     "legendFormat": "CoreDNS"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"rook-ceph\",pod=~\"rook-ceph-mon-.*\"} == 1) < 1",
     "legendFormat": "Rook Ceph (MON)"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"rook-ceph\",pod=~\"rook-ceph-mds-.*\"} == 1) < 1",
     "legendFormat": "Rook Ceph (MDS)"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"rook-ceph\",pod=~\"rook-ceph-osd-.*\"} == 1) < 1",
     "legendFormat": "Rook Ceph (OSD)"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"prometheus\",pod=~\"cluster-mgmt-system-exporter-*\"} == 1) < 1",
     "legendFormat": "System Exporter"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"prometheus\",pod=~\"prometheus-snmp-exporter-*\"} == 1) < 1",
     "legendFormat": "SNMP Exporter"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"prometheus\",pod=~\"prometheus-kube-state-metrics-*\"} == 1) < 1",
     "legendFormat": "Kube State Metrics"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"prometheus\",pod=~\"prometheus-prometheus-prometheus-.*\"} == 1) < 1",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"prometheus\",pod=~\"prometheus-grafana-.*\"} == 1) < 1",
     "legendFormat": "Grafana"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"loki\",pod=~\"loki-.*\"} == 1) < 1",
     "legendFormat": "Loki"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"fluent-bit\",pod=~\"fluent-bit-.*\"} == 1) < 1",
     "legendFormat": "Fluent-Bit"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"private-registry-.*\"} == 1) < 1",
     "legendFormat": "Registry"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"kube-vip-[^-]+-.+\"} == 1) < 1",
     "legendFormat": "Kube-Vip (1G)"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"kube-vip-[a-zA-Z0-9]+\"} == 1) < 1",
     "legendFormat": "Kube-Vip (100G)"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"ingress-nginx-controller-.*\"} == 1) < 1",
     "legendFormat": "Nginx"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"prometheus\",pod=~\"cluster-mgmt-linkmon-switch-.*\"} == 1) < 1",
     "legendFormat": "Linkmon"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"cilium-.*\"} == 1) < 1",
     "legendFormat": "Cilium"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"prometheus\",pod=~\"alert-router-.*\"} == 1) < 1",
     "legendFormat": "AlertRouter"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"prometheus\",pod=~\"alertmanager-.*\"} == 1) < 1",
     "legendFormat": "AlertManager"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"multus-multus-.*\"} == 1) < 1",
     "legendFormat": "Multus"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"whereabouts-.*\"} == 1) < 1",
     "legendFormat": "Whereabouts"
    }
   ]
  },
  { "title": "Warnings", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 12 } },
  {
   "title": "Failed Pods by Service",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"kube-apiserver-.*\"} == 0) > 0",
     "legendFormat": "API Server"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"etcd-.*\"} == 0) > 0",
     "legendFormat": "etcd"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"coredns-.*\"} == 0) > 0",
     "legendFormat": "CoreDNS"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"rook-ceph\",pod=~\"rook-ceph-mon-.*\"} == 0) > 0",
     "legendFormat": "Rook Ceph (MON)"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"rook-ceph\",pod=~\"rook-ceph-mds-.*\"} == 0) > 0",
     "legendFormat": "Rook Ceph (MDS)"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"rook-ceph\",pod=~\"rook-ceph-osd-.*\"} == 0) > 0",
     "legendFormat": "Rook Ceph (OSD)"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"prometheus\",pod=~\"cluster-mgmt-system-exporter-*\"} == 0) > 0",
     "legendFormat": "System Exporter"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"prometheus\",pod=~\"prometheus-snmp-exporter-*\"} == 0) > 0",
     "legendFormat": "SNMP Exporter"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"prometheus\",pod=~\"prometheus-kube-state-metrics-*\"} == 0) > 0",
     "legendFormat": "Kube State Metrics"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"prometheus\",pod=~\"prometheus-prometheus-prometheus-.*\"} == 0) > 0",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"prometheus\",pod=~\"prometheus-grafana-.*\"} == 0) > 0",
     "legendFormat": "Grafana"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"loki\",pod=~\"loki-.*\"} == 0) > 0",
     "legendFormat": "Loki"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"fluent-bit\",pod=~\"fluent-bit-.*\"} == 0) > 0",
     "legendFormat": "Fluent-Bit"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"private-registry-.*\"} == 0) > 0",
     "legendFormat": "Registry"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"kube-vip-[^-]+-.+\"} == 0) > 0",
     "legendFormat": "Kube-Vip (1G)"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"kube-vip-[a-zA-Z0-9]+\"} == 0) > 0",
     "legendFormat": "Kube-Vip (100G)"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"ingress-nginx-controller-.*\"} == 0) > 0",
     "legendFormat": "Nginx"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"prometheus\",pod=~\"cluster-mgmt-linkmon-switch-.*\"} == 0) > 0",
     "legendFormat": "Linkmon"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"cilium-.*\"} == 0) > 0",
     "legendFormat": "Cilium"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"prometheus\",pod=~\"alert-router-.*\"} == 0) > 0",
     "legendFormat": "AlertRouter"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"prometheus\",pod=~\"alertmanager-.*\"} == 0) > 0",
     "legendFormat": "AlertManager"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"multus-multus-.*\"} == 0) > 0",
     "legendFormat": "Multus"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\"whereabouts-.*\"} == 0) > 0",
     "legendFormat": "Whereabouts"
    }
   ]
  },
  { "title": "Error History", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 17 } },
  {
   "title": "Recent Restarts by Service (15m)",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"kube-system\",pod=~\"kube-apiserver-.*\"}[$__range]) > 0",
     "legendFormat": "API Server"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"kube-system\",pod=~\"etcd-.*\"}[$__range]) > 0",
     "legendFormat": "etcd"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"kube-system\",pod=~\"coredns-.*\"}[$__range]) > 0",
     "legendFormat": "CoreDNS"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"rook-ceph\",pod=~\"rook-ceph-mon-.*\"}[$__range]) > 0",
     "legendFormat": "Rook Ceph (MON)"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"rook-ceph\",pod=~\"rook-ceph-mds-.*\"}[$__range]) > 0",
     "legendFormat": "Rook Ceph (MDS)"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"rook-ceph\",pod=~\"rook-ceph-osd-.*\"}[$__range]) > 0",
     "legendFormat": "Rook Ceph (OSD)"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"prometheus\",pod=~\"cluster-mgmt-system-exporter-*\"}[$__range]) > 0",
     "legendFormat": "System Exporter"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"prometheus\",pod=~\"prometheus-snmp-exporter-*\"}[$__range]) > 0",
     "legendFormat": "SNMP Exporter"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"prometheus\",pod=~\"prometheus-kube-state-metrics-*\"}[$__range]) > 0",
     "legendFormat": "Kube State Metrics"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"prometheus\",pod=~\"prometheus-prometheus-prometheus-.*\"}[$__range]) > 0",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"prometheus\",pod=~\"prometheus-grafana-.*\"}[$__range]) > 0",
     "legendFormat": "Grafana"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"loki\",pod=~\"loki-.*\"}[$__range]) > 0",
     "legendFormat": "Loki"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"fluent-bit\",pod=~\"fluent-bit-.*\"}[$__range]) > 0",
     "legendFormat": "Fluent-Bit"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"kube-system\",pod=~\"private-registry-.*\"}[$__range]) > 0",
     "legendFormat": "Registry"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"kube-system\",pod=~\"kube-vip-[^-]+-.+\"}[$__range]) > 0",
     "legendFormat": "Kube-Vip (1G)"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"kube-system\",pod=~\"kube-vip-[a-zA-Z0-9]+\"}[$__range]) > 0",
     "legendFormat": "Kube-Vip (100G)"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"kube-system\",pod=~\"ingress-nginx-controller-.*\"}[$__range]) > 0",
     "legendFormat": "Nginx"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"prometheus\",pod=~\"cluster-mgmt-linkmon-switch-.*\"}[$__range]) > 0",
     "legendFormat": "Linkmon"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"kube-system\",pod=~\"cilium-.*\"}[$__range]) > 0",
     "legendFormat": "Cilium"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"prometheus\",pod=~\"alert-router-.*\"}[$__range]) > 0",
     "legendFormat": "AlertRouter"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"prometheus\",pod=~\"alertmanager-.*\"}[$__range]) > 0",
     "legendFormat": "AlertManager"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"kube-system\",pod=~\"multus-multus-.*\"}[$__range]) > 0",
     "legendFormat": "Multus"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"kube-system\",pod=~\"whereabouts-.*\"}[$__range]) > 0",
     "legendFormat": "Whereabouts"
    }
   ]
  }
 ]
}