/*
Copyright 2022 Cerebras Systems, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "cerebras.com/job-operator/apis/system/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSystems implements SystemInterface
type FakeSystems struct {
	Fake *FakeSystemV1
}

var systemsResource = v1.SchemeGroupVersion.WithResource("systems")

var systemsKind = v1.SchemeGroupVersion.WithKind("System")

// Get takes name of the system, and returns the corresponding system object, and an error if there is any.
func (c *FakeSystems) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.System, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(systemsResource, name), &v1.System{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.System), err
}

// List takes label and field selectors, and returns the list of Systems that match those selectors.
func (c *FakeSystems) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SystemList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(systemsResource, systemsKind, opts), &v1.SystemList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.SystemList{ListMeta: obj.(*v1.SystemList).ListMeta}
	for _, item := range obj.(*v1.SystemList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested systems.
func (c *FakeSystems) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(systemsResource, opts))
}

// Create takes the representation of a system and creates it.  Returns the server's representation of the system, and an error, if there is any.
func (c *FakeSystems) Create(ctx context.Context, system *v1.System, opts metav1.CreateOptions) (result *v1.System, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(systemsResource, system), &v1.System{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.System), err
}

// Update takes the representation of a system and updates it. Returns the server's representation of the system, and an error, if there is any.
func (c *FakeSystems) Update(ctx context.Context, system *v1.System, opts metav1.UpdateOptions) (result *v1.System, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(systemsResource, system), &v1.System{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.System), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSystems) UpdateStatus(ctx context.Context, system *v1.System, opts metav1.UpdateOptions) (*v1.System, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(systemsResource, "status", system), &v1.System{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.System), err
}

// Delete takes name of the system and deletes it. Returns an error if one occurs.
func (c *FakeSystems) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(systemsResource, name, opts), &v1.System{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSystems) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(systemsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.SystemList{})
	return err
}

// Patch applies the patch and returns the patched system.
func (c *FakeSystems) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.System, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(systemsResource, name, pt, data, subresources...), &v1.System{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.System), err
}
