apiVersion: v1
kind: Service
metadata:
  labels:
    app: private-registry
  name: private-registry
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app: private-registry
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: private-registry
  namespace: kube-system
  labels:
    app: private-registry
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: private-registry
  endpoints:
    - port: http-metrics
      interval: 30s
