apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: registry-installer
  namespace: $NAMESPACE
  labels:
    app: registry-installer
spec:
  selector:
    matchLabels:
      app: registry-installer
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "34%"
  template:
    metadata:
      labels:
        app: registry-installer
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/unreachable
        operator: Exists
        effect: NoSchedule
      - key: node.cilium.io/agent-not-ready
        operator: Exists
        effect: NoSchedule
      initContainers:
      - name: init-container
        image: registry.local/alpine-containerd:$TAG
        imagePullPolicy: IfNotPresent
        command: ["bash", "/cluster-mgmt-scripts/registry-installer.sh"]
        env:
        - name: LEAD_MGMT_NODE
          value: $LEAD_MGMT_NODE
        - name: LEAD_MGMT_NODE_IP
          value: $LEAD_MGMT_NODE_IP
        - name: CERTS_DIR
          value: $CERTS_DIR
        - name: REGISTRY_IPS
          value: $REGISTRY_IPS
        - name: MY_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
          - name: host-root
            mountPath: /host-root/
          - name: scripts
            mountPath: /cluster-mgmt-scripts
          - name: sshkey-secret-volume
            readOnly: true
            mountPath: "/etc/sshkey-secret-volume"
      containers:
      - name: main
        image: registry.local/alpine-containerd:$TAG
        command: ["sleep", "infinity"]
      terminationGracePeriodSeconds: 1
      priorityClassName: system-node-critical
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory
        - name: scripts
          configMap:
            name: registry-installer-scripts
            items:
            - key: registry-installer.sh
              path: registry-installer.sh
        - name: sshkey-secret-volume
          secret:
            secretName: cerebras-sshkey-pair
            defaultMode: 384
