# Based on os-provision/roles/common/tasks/main.yml 
- name: Set usernode hostname
  hostname:
    name: "{{ usernode_hostname }}"

- name: Extract root volume
  # Typically /dev/sda or /dev/nvme0n1
  shell: fdisk -l | grep 'Linux LVM' | awk '{print $1}' | sed 's/p\?[0-9]\+$//'
  register: root_vol

- name: Extract root partition
  # Typically 2 as in /dev/sda2, or p2 as in /dev/nvme0n1p2
  shell: fdisk -l | grep 'Linux LVM' | awk '{print $1}' | grep -Eo 'p?[0-9]+$'
  register: root_part

- name: Extract root partition number
  # Typically 2 as in /dev/sda2, or 2 as in /dev/nvme0n1p2
  shell: fdisk -l | grep 'Linux LVM' | awk '{print $1}' | grep -Eo '[0-9]+$'
  register: root_part_num

- name: Resize partition
  parted:
    device: "{{ root_vol.stdout }}"
    number: "{{ root_part_num.stdout }}"
    part_end: "100%"
    resize: yes
    state: present

- name: Resize PV
  lvg:
    vg: rl
    pvs: "{{ root_vol.stdout }}{{ root_part.stdout }}"
    pvresize: yes
    state: present

- name: Resize LVM
  lvol:
    vg: rl
    lv: root
    size: +100%FREE
    resizefs: yes
    state: present

- name: Copy RAID script
  template:
    src: create-raid.sh
    dest: /tmp/create-raid.sh
    mode: 0700

- name: Run RAID script
  shell: /tmp/create-raid.sh
  args:
    creates: "/dev/md127"

- name: Restart NetworkManager
  systemd:
    name: NetworkManager
    state: restarted

# Based on os-provision/roles/common/tasks/change-pam-limit.yml
- name: Start/enable sysstat service
  systemd:
    name: sysstat
    state: started
    enabled: yes

- name: Copy rsyslog.conf to /etc
  template:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
    mode: 0644

- name: Restart rsyslog service
  systemd:
    name: rsyslog
    state: restarted

- name: Start/enable lldpd service
  systemd:
    name: lldpd
    state: restarted
    enabled: yes

- name: Deploy chrony.conf template
  template:
    src: chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Restart chronyd
  service:
    name: chronyd
    state: restarted

- name: Change nofile hard limit to 20000
  community.general.pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: nofile
    value: 20000

- name: Change nofile soft limit to 20000
  community.general.pam_limits:
    domain: '*'
    limit_type: soft
    limit_item: nofile
    value: 20000

- name: Change nproc hard limit to 16384
  community.general.pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: nproc
    value: 16384

- name: Change nproc soft limit to 16384
  community.general.pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: nproc
    value: 16384

- name: Create python directory
  file: path=/opt/python3.8/bin state=directory

- name: Create python3.8 link
  file:
    src: /usr/bin/python3.8
    dest: /opt/python3.8/bin/python3.8
    state: link 

# Switch infiniBand to ethernet if needed
# Based on os-provision/roles/common/tasks/ib-check.yml
- name: Enable and start mst
  systemd: name=mst state=started enabled=yes

- name: Create Mellanox FW directory
  file:
    path: /opt/mlnx
    state: directory

- name: Copy MLNX FW files
  copy:
    src: /mnt/files/fw/mlxup
    dest: /opt/mlnx/
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- name: Copy change infiniband to eth script
  template:
    src: change_ib_to_eth.py
    dest: /tmp/change_ib_to_eth.py

- name: Change ib to eth
  shell: python3 /tmp/change_ib_to_eth.py >& /tmp/ib_to_eth.log
