{
 "title": "Cluster Mgmt Debug",
 "tags": [ "cluster-mgmt" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system_filter",
    "label": "System",
    "query": {
     "query": "label_values(system_overall_health, system)"
    }
   },
   {
    "name": "subsystem_filter",
    "label": "Subsystem",
    "query": {
     "query": "label_values(system_subsystem_health, subsystem)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CS2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall CS2 Status",
   "type": "stat",
   "description": "status of all systems at the last timestamp of the selected range ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(system_overall_health{system=~\"$system_filter\"}) by (system) == bool 2)",
     "legendFormat": "DEGRADED"
    },
    {
     "expr": "sum(max(system_overall_health{system=~\"$system_filter\"}) by (system) == bool 1)",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(group((system_overall_health{system=~\"$system_filter\"} != 1) and (system_overall_health{system=~\"$system_filter\"} != 2) and (system_overall_health{system=~\"$system_filter\"} != -1)) by (system) or group by (system) (system_overall_health{system=~\"$system_filter\"}) != bool(1))",
     "legendFormat": "ERROR"
    },
    {
     "expr": "clamp_max(avg_over_time((\nsum((group(wsjob_system_grant{system=~\"$system_filter\"}) by (system)) or (sum(0*system_label{system=~\"$system_filter\"}) by (system))) /\ncount(group(system_label{system=~\"$system_filter\"}) by (system)) \n)[$__range:$__rate_interval]) *100, 100)\n\n",
     "legendFormat": "Utilized Percent"
    },
    {
     "expr": "avg_over_time((sum(group(wsjob_system_grant) by (system)) or sum(sum(system_label*0) by (system)))[$__range:$__rate_interval]) * (${__to:date:seconds}-${__from:date:seconds})/3600\n",
     "legendFormat": "Utilized Hours"
    }
   ]
  },
  {
   "title": "CS2 Jobs Histogram",
   "type": "timeseries",
   "description": "(Max) Number of systems used by jobs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (name, labels_k8s_cerebras_com_Model) (group by (name, system) (wsjob_system_grant{system =~\"$system_filter\"})) * on (name) group_left(labels_k8s_cerebras_com_Model) group by(name, labels_k8s_cerebras_com_Model) \n(wsjob_annotation{job_type!=\"compile\"})",
     "legendFormat": "{{labels_k8s_cerebras_com_Model}} / {{name}}"
    }
   ]
  },
  {
   "title": "CS2 Errors",
   "type": "state-timeline",
   "description": "CS2 error status timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(max_over_time(system_overall_health{system=~\"$system_filter\"}[$__rate_interval]) != 1) by (system)",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "CS2 Subsystem Errors ($subsystem_filter)",
   "type": "state-timeline",
   "description": "CS2 Subsystem Errors. Change the Subsystem variable to view different subsystems",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max(max_over_time(system_subsystem_health{system=~\"$system_filter\", subsystem=~\"$subsystem_filter\"}[$__rate_interval]) != 1) by (system, subsystem)",
     "legendFormat": "{{system}}/{{subsystem}}"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU load",
   "type": "timeseries",
   "description": "The line represents the average CPU load of all nodes of that node type\nThe shaded area indicates the min and max CPU load% of that node type",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "role:container_cpu_usage_seconds:avg",
     "legendFormat": "{{role}}"
    },
    {
     "expr": "role:container_cpu_usage_seconds:min",
     "legendFormat": "{{role}}_min"
    },
    {
     "expr": "role:container_cpu_usage_seconds:max",
     "legendFormat": "{{role}}_max"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Line represents the average mem usage for all nodes of that node type\nShaded area of that color marks the min and max use% of that node type",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "role:node_memory_utilisation:avg_ratio",
     "legendFormat": "{{role}}"
    },
    {
     "expr": "role:node_memory_utilisation:min_ratio",
     "legendFormat": "{{role}}_min"
    },
    {
     "expr": "role:node_memory_utilisation:max_ratio",
     "legendFormat": "{{role}}_max"
    }
   ]
  },
  {
   "title": "Net BW ingress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(network_receive_bytes_including_roce[$__rate_interval])) by (role)",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Net BW egress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(network_transmit_bytes_including_roce[$__rate_interval])) by (role)",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Node Warning/Errors",
   "type": "state-timeline",
   "description": "K8s Nodes having error/warnings can cause scheduling failure",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(max_over_time(kube_node_status_condition{condition=~\"ClusterMgmt.*|ClusterDeploy.*|Csadm.*\", status=\"true\"}[$__rate_interval]) > 0) + 1",
     "legendFormat": "{{node}}/{{condition}}"
    },
    {
     "expr": "(min_over_time(node_ipmi_health_status{category=\"Overall\"} [$__rate_interval]) > 0) > 0",
     "legendFormat": "{{node}}/IPMIUnhealthy"
    }
   ]
  },
  {
   "title": "Root Disk Usage > 85%",
   "type": "timeseries",
   "description": "display hosts with root Disk Usage > 85%",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(label_replace(\n    (((node_filesystem_size_bytes{mountpoint=\"/\"}-node_filesystem_avail_bytes{mountpoint=\"/\"})/node_filesystem_size_bytes{mountpoint=\"/\"}) > .85),\n    \"internal_ip\", \"$1\", \"instance\", \"([^:]+):.*\"\n) * on (internal_ip) group_left (node) group(kube_node_info) by (node, internal_ip)) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "NFS Mount Errors",
   "type": "timeseries",
   "description": "Shows NFS mount errors per node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "max((max_over_time(node_nfs_server_health[$__rate_interval]) != 1) != bool 1)  by (node,volume)",
     "legendFormat": "{{node}}/{{volume}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "CS2 System Port Errors",
   "type": "timeseries",
   "description": "Breakdown of CS2 System Port Errors",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "group by (system, port) (increase(system_network_flap_count{system=~\"$system_filter\"}[$__rate_interval]) >= 2)",
     "legendFormat": "{{system}}:{{port}} flapping"
    },
    {
     "expr": "group by (system, port) (min_over_time(system_network_health{system=~\"$system_filter\"}[$__rate_interval]) == 0)",
     "legendFormat": "{{system}}:{{port}} down"
    }
   ]
  },
  {
   "title": "Node NIC Errors",
   "type": "timeseries",
   "description": "NIC flapping or down",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(increase(interface_watch_list:status_changes_total[$__rate_interval]) >= bool 2) > 0",
     "legendFormat": "{{node}}:{{device}} flapping"
    },
    {
     "expr": "(min_over_time(interface_watch_list:status[$__rate_interval]) == bool 0) > 0",
     "legendFormat": "{{node}}:{{device}} down"
    }
   ]
  },
  {
   "title": "Switch Port Problems",
   "type": "state-timeline",
   "description": "Time and duration of port issues (port is down or had one or more flaps) - only for explicitly tracked ports from the network_config.json",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "(group by (ifName, switch_id) (min_over_time(ifOperStatus[10m])!=1) or (group by (ifName, switch_id) (changes(ifLastChange[10m])>0) * 2) or (group by (ifName, switch_id)  (label_replace(label_replace(((min_over_time(linkmon_switch_oper_status[10m]) != 1)) or ((changes(linkmon_switch_carrier_changes[10m]) > 0) * 2) , \"ifName\", \"$1\", \"port\", \"(.*)\"), \"switch_id\", \"$1\", \"switch\", \"(.*)\")))) * on (ifName, switch_id) group_left (conn_type, node, device) interface_watch_list{switch_id!=\"\"}",
     "legendFormat": "{{conn_type}} {{switch_id}}:{{ifName}} ({{node}}:{{device}})"
    }
   ]
  },
  {
   "title": "Switch Port Flap Counter - Increase During Time Range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(linkmon_switch_carrier_changes[30m]) * on (switch, port) group_left label_replace(label_replace(interface_watch_list, \"port\", \"$1\", \"ifName\", \"(.*)\"), \"switch\", \"$1\", \"switch_id\", \"(.*)\") > 0",
     "legendFormat": "{{switch}}:{{port}} ({{desc}})"
    }
   ]
  },
  {
   "title": "Switch Port Flap Counter - Absolute Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "(linkmon_switch_carrier_changes and (increase(linkmon_switch_carrier_changes[30m]) > 0 or increase(linkmon_switch_carrier_changes[30m] offset -30m) >0) * on (switch, port) group_left label_replace(label_replace(interface_watch_list, \"port\", \"$1\", \"ifName\", \"(.*)\"), \"switch\", \"$1\", \"switch_id\", \"(.*)\"))",
     "legendFormat": "{{switch}}:{{port}} ({{desc}})"
    }
   ]
  },
  {
   "title": "CS2 CRC Errors (Increase During Time Range)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "increase(system_network_rx_pkt_bad_fcs[$__rate_interval]) > 0",
     "legendFormat": "{{system}}:{{port}}"
    }
   ]
  },
  {
   "title": "Node CRC Errors (Increase During Time Range)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 100 },
   "targets": [
    {
     "expr": "increase(node_nic_stats_rx_crc_errors_phy[$__rate_interval]) > 0",
     "legendFormat": "{{node}}:{{interface}}"
    }
   ]
  },
  {
   "title": "Switch CRC Errors (Increase During Time Range)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 100 },
   "targets": [
    {
     "expr": "increase(linkmon_switch_crc_errors[30m]) * on (switch, port) group_left label_replace(label_replace(interface_watch_list, \"port\", \"$1\", \"ifName\", \"(.*)\"), \"switch\", \"$1\", \"switch_id\", \"(.*)\") > 0",
     "legendFormat": "{{switch}}:{{port}} ({{desc}})"
    }
   ]
  },
  {
   "title": "Node NIC CQE (Increase During Time Range)",
   "type": "timeseries",
   "description": "Node Completion Queue Errors - indicates failed RDMA transactions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "increase(node_nic_stats_resp_cqe_error[$__rate_interval]) > 0",
     "legendFormat": "{{node}}:{{interface}} RX CQE Error"
    },
    {
     "expr": "increase(node_nic_stats_req_cqe_error[$__rate_interval]) > 0",
     "legendFormat": "{{node}}:{{interface}} TX CQE Error"
    }
   ]
  },
  {
   "title": "Node TX PFC Pause Duration (Increase During Time Range)",
   "type": "timeseries",
   "description": "Node Priority Flow Control pause duration - indicates network congestion",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "expr": "increase(node_nic_rx_pfc_duration[$__rate_interval]) > 0",
     "legendFormat": "{{node}}:{{interface}} Pause Duration"
    }
   ]
  },
  {
   "title": "Network Monitoring System Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 }
  },
  {
   "title": "Monitoring Status",
   "type": "stat",
   "description": "Up if at least one switch is returning SNMP results and at least one SNMP query is recorded in the database",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 117 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(scalar(count(up{job=\"snmp\"}>0)) * scalar(count(ifOperStatus))) >bool 0",
     "legendFormat": "SNMP"
    },
    {
     "expr": "(scalar(up{container=\"cluster-mgmt-linkmon-switch\"}) * scalar(count(linkmon_switch_oper_status))) >bool 0",
     "legendFormat": "Linkmon (CLI)"
    }
   ]
  },
  {
   "title": "network_config.json Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 117 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent(absent(interface_watch_list)) or on () vector(0)",
     "legendFormat": "File exists"
    },
    {
     "expr": "absent(interface_watch_list_errors) or on () vector(0)",
     "legendFormat": "File is valid"
    }
   ]
  },
  {
   "title": "SNMP Switch Monitor Count",
   "type": "stat",
   "description": "Number of switches currently responding to SNMP queries and number of switches listed in network_config.json",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 117 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"snmp\"}>0)",
     "legendFormat": "Scraped"
    },
    {
     "expr": "count(up{job=\"snmp\"})",
     "legendFormat": "In watch list"
    }
   ]
  },
  {
   "title": "SNMP Switch - Data Timestamps",
   "type": "stat",
   "description": "Oldest and newest timestamp of the latest available switch response to a standard query",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000*max(timestamp(ifOperStatus))",
     "legendFormat": "Newest"
    },
    {
     "expr": "min(timestamp(ifOperStatus))*1000",
     "legendFormat": "Oldest"
    }
   ]
  },
  {
   "title": "Linkmon Switch Monitor Count",
   "type": "stat",
   "description": "Number of switches currently responding to linkmon queries and number of switches listed in network_config.json",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 117 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (switch) (linkmon_switch_oper_status))",
     "legendFormat": "Scraped"
    },
    {
     "expr": "count(group by (switch_id) (interface_watch_list))",
     "legendFormat": "In watch list"
    }
   ]
  },
  {
   "title": "Linkmon Switch - Data Timestamps",
   "type": "stat",
   "description": "Oldest and newest timestamp of the latest available switch response to a standard query",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000*max(timestamp(linkmon_switch_oper_status))",
     "legendFormat": "Newest"
    },
    {
     "expr": "min(timestamp(linkmon_switch_oper_status))*1000",
     "legendFormat": "Oldest"
    }
   ]
  },
  {
   "title": "network_config.json errors",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 121 },
   "targets": [
    { "expr": "interface_watch_list_errors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Warning Conditions - Uncorrected Errors and Other Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
   "collapsed": true,
   "panels": [
    {
     "title": "Switch FEC Uncorrected Errors",
     "type": "timeseries",
     "description": "Switch port uncorrectable packet errors can cause port flaps or other network failures",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
     "targets": [
      {
       "expr": "increase(linkmon_switch_fec_uncorrected_codewords[10m]) > 0",
       "legendFormat": "{{switch}}:{{port}} ({{desc}})"
      }
     ]
    },
    {
     "title": "CS2 FEC/PCS Uncorrected Errors",
     "type": "timeseries",
     "description": "System uncorrectable packet errors can cause port flaps or other network failures",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
     "targets": [
      {
       "expr": "increase(system_network_rx_pkt_bad_fcs[10m]) > 0",
       "legendFormat": "{{system}}:{{port}}"
      },
      {
       "expr": "increase(system_network_rx_fec_uncorrected_pkts[10m]) > 0",
       "legendFormat": "{{system}}:{{port}}"
      }
     ]
    },
    {
     "title": "Node FEC/PCS Uncorrected Errors",
     "type": "timeseries",
     "description": "Node NIC uncorrectable packet errors can cause port flaps or other network failures",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
     "targets": [
      {
       "expr": "increase(node_nic_stats_rx_pcs_symbol_err_phy[10m]) > 0",
       "legendFormat": "{{node}}:{{interface}}"
      },
      {
       "expr": "increase(node_nic_stats_rx_crc_errors_phy[10m]) > 0",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    },
    {
     "title": "Node NIC Device/Driver Errors",
     "type": "timeseries",
     "description": "Internal NIC errors: device crash/hang and send/receive transaction failures. Generally indicates driver or NIC hardware problems, not user software or cabling.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 144 },
     "targets": [
      {
       "expr": "node_nic_stats_ethtool_error != 0",
       "legendFormat": "{{node}}:{{interface}} ethtool Driver Errors"
      },
      {
       "expr": "increase(node_nic_stats_tx_cqe_err[10m]) > 0",
       "legendFormat": "{{node}}:{{interface}} TX CQE Errors"
      },
      {
       "expr": "increase(node_nic_stats_rx_wqe_err[10m]) > 0",
       "legendFormat": "{{node}}:{{interface}} RX WQE Errors"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Info Conditions - Corrected Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 },
   "collapsed": true,
   "panels": [
    {
     "title": "Switch FEC Corrected Errors",
     "type": "timeseries",
     "description": "Correctable FEC errors do not cause flaps or other network failures",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "increase(linkmon_switch_fec_corrected_codewords[10m]) > 0",
       "legendFormat": "{{switch}}:{{port}} ({{desc}})"
      }
     ]
    },
    {
     "title": "CS2 FEC/PCS Corrected Errors",
     "type": "timeseries",
     "description": "Correctable FEC errors do not cause flaps or other network failures",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 119 },
     "targets": [
      {
       "expr": "increase(system_network_rx_fec_corrected_pkts[10m]) > 0",
       "legendFormat": "{{system}}:{{port}}"
      }
     ]
    },
    {
     "title": "Node FEC/PCS Corrected Errors",
     "type": "timeseries",
     "description": "Correctable FEC errors do not cause flaps or other network failures",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 128 },
     "targets": [
      {
       "expr": "increase(node_nic_stats_rx_corrected_bits_phy[10m]) > 0",
       "legendFormat": "{{node}}:{{interface}}"
      }
     ]
    }
   ]
  },
  { "title": "Cluster Admin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Cilium Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(((max_over_time(cilium_unreachable_health_endpoints[$__rate_interval]) + increase(cilium_unreachable_nodes[$__rate_interval])) >=bool 1),\n\"internal_ip\", \"$1\", \"instance\", \"([^:]+):.*\") * on (internal_ip) group_left (node) group(kube_node_info) by (node, internal_ip) > 0\n",
     "legendFormat": "{{node}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Multus Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "group by (namespace, pod, reason) (max_over_time(kube_pod_container_status_terminated_reason{pod=~\"multus.*|whereabouts.*\", namespace!=\"job-operator\", reason=\"Error\"}[$__rate_interval])== 1)",
     "legendFormat": "{{pod}} {{reason}}"
    },
    {
     "expr": "group by (namespace, pod, reason) (max_over_time(kube_pod_container_status_waiting_reason{pod=~\"multus.*|whereabouts.*\", namespace!=\"job-operator\", reason!~\"ContainerCreating|PodInitializing\"}[$__rate_interval])== 1)",
     "legendFormat": "{{pod}} {{reason}}"
    }
   ]
  },
  {
   "title": "Job Service Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "group by (namespace, pod, reason) (max_over_time(kube_pod_container_status_terminated_reason{pod=~\"cluster-server.*|.*controller-manager.*|ingress-nginx.*\", reason=\"Error\", namespace=~\"job-operator|ingress-nginx\"}[$__rate_interval])== 1)",
     "legendFormat": "{{namespace}}/{{pod}} {{reason}}"
    },
    {
     "expr": "group by (namespace, pod, reason) (max_over_time(kube_pod_container_status_waiting_reason{pod=~\"cluster-server.*|.*controller-manager.*|ingress-nginx.*\", reason!~\"ContainerCreating|PodInitializing\", namespace=~\"job-operator|ingress-nginx\"}[$__rate_interval])== 1)",
     "legendFormat": "{{namespace}}/{{pod}} {{reason}}"
    }
   ]
  },
  {
   "title": "Other Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "group by (namespace, pod, reason) (max_over_time(kube_pod_container_status_terminated_reason{pod!~\"cluster-server.*|ingress-nginx.*|cilium.*|wsjob.*|imgjob.*|multus.*|whereabouts.*\", namespace!=\"job-operator\", reason=\"Error\"}[$__rate_interval])== 1)",
     "legendFormat": "{{namespace}}/{{pod}} {{reason}}"
    },
    {
     "expr": "group by (namespace, pod, reason) (max_over_time(kube_pod_container_status_waiting_reason{pod!~\"cluster-server.*|ingress-nginx.*|cilium.*|wsjob.*|imgjob.*|multus.*|whereabouts.*\", namespace!=\"job-operator\", reason!~\"PodInitializing|ContainerCreating\"}[$__rate_interval])== 1)",
     "legendFormat": "{{namespace}}/{{pod}} {{reason}}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 } },
  { "title": "Current Alerts", "type": "alertlist", "gridPos": { "h": 21, "w": 24, "x": 0, "y": 146 } }
 ]
}