{
 "title": "CPingmesh Debug",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "max_rtt_thresh", "label": "max_rtt_thresh (us)", "query": "100" },
   { "name": "avg_rtt_thresh", "label": "avg_rtt_thresh (us)", "query": "100" },
   { "name": "src_delay_thresh", "label": "src_delay_thresh (ms)", "query": "68" },
   { "name": "dst_delay_thresh", "label": "dst_delay_thresh (ms)", "query": "4.4" },
   { "name": "drop_thresh", "label": "drop_thresh (drops/min)", "query": "0.5" },
   { "name": "anomalous_rtt_window", "label": "anomalous_rtt_window (s)", "query": "120" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n  <a href='https://cpingmesh.$BASE_CLUSTER_DOMAIN_NAME/?time=${__to}' target='_blank'><img src='https://cpingmesh.$BASE_CLUSTER_DOMAIN_NAME/favicon.ico' height='40px'> Matrix Viz</a>\n</center>"
   }
  },
  {
   "title": "Top src->dst with max RTT > $max_rtt_thresh us",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 15, "w": 7, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "topk(44, avg by (src_host, dst_host) (max_over_time(pingmesh_max_rtt_s[$__range]) > ($max_rtt_thresh / 1e6))) > bool 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top src->dst with avg RTT > $avg_rtt_thresh us",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 15, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "topk(44, avg by (src_host, dst_host) (max_over_time(pingmesh_avg_rtt_s[$__range]) > ($avg_rtt_thresh / 1e6))) > bool 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top src->dst with drops",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 15, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "topk(44, avg by (src_host, dst_host) (increase(pingmesh_drops_total[$__range]) > 0)) > bool 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 13, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (src_host) (pingmesh_avg_rtt_s))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(group by (dst_host) (pingmesh_avg_rtt_s))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(group by (src_host, src_nic) (pingmesh_avg_rtt_s))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(group by (dst_host, dst_nic) (pingmesh_avg_rtt_s))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kube_pod_container_status_ready{pod=~\"cping-agent-.*\"} > 0) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kube_pod_container_status_ready{pod=~\"cping-agent-.*\"} < 1) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg ((15*60)/count_over_time(pingmesh_avg_rtt_s[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anomalous max RTT (> ${max_rtt_thresh} us for ${anomalous_rtt_window} s) timeline",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min_over_time(pingmesh_max_rtt_s[${anomalous_rtt_window}s]) > (${max_rtt_thresh} / 1e6)",
     "legendFormat": "{{src_host}}:{{src_nic}} -> {{dst_host}}:{{dst_nic}}"
    }
   ]
  },
  {
   "title": "Max RTT histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pingmesh_max_rtt_s", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg RTT histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pingmesh_avg_rtt_s", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max RTT > $max_rtt_thresh us",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pingmesh_max_rtt_s > ($max_rtt_thresh / 1e6)",
     "legendFormat": "{{src_host}}:{{src_nic}} -> {{dst_host}}:{{dst_nic}}"
    }
   ]
  },
  {
   "title": "Avg RTT > $avg_rtt_thresh us",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pingmesh_avg_rtt_s > ($avg_rtt_thresh / 1e6)",
     "legendFormat": "{{src_host}}:{{src_nic}} -> {{dst_host}}:{{dst_nic}}"
    }
   ]
  },
  {
   "title": "Src Delay histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(max by (src_host, src_nic) (pingmesh_src_host_delay_s))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dst Delay histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(max by (dst_host, dst_nic) (pingmesh_dst_host_delay_s))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Src Delay > $src_delay_thresh ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(max by (src_host, src_nic) (pingmesh_src_host_delay_s)) > ($src_delay_thresh / 1000)",
     "legendFormat": "{{src_host}}:{{src_nic}}"
    }
   ]
  },
  {
   "title": "Dst Delay > $dst_delay_thresh ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(max by (dst_host, dst_nic) (pingmesh_dst_host_delay_s)) > ($dst_delay_thresh / 1000)",
     "legendFormat": "{{dst_host}}:{{dst_nic}}"
    }
   ]
  },
  {
   "title": "Drops/minute > ${drop_thresh}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "(rate(pingmesh_drops_total[$__rate_interval]) * 60) > ${drop_thresh}",
     "legendFormat": "{{src_host}}:{{src_nic}} -> {{dst_host}}:{{dst_nic}}"
    }
   ]
  },
  {
   "title": "Agents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Agent Pods",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "sum by (pod, reason) (kube_pod_container_status_restarts_total{pod=~\"cping-agent-.*\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by (pod, node) (kube_pod_info{pod=~\"cping-agent-.*\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (pod, phase) (kube_pod_status_phase{pod=~\"cping-agent-.*\"} > 0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "$__to - (avg by (pod) (kube_pod_created{pod=~\"cping-agent-.*\"}) * 1000)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}