{
 "title": "CPingmesh Health",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "query_result(pingmesh_server_pingss_total or pingmesh_server_drops_total)"
    }
   },
   {
    "name": "nic",
    "label": "NIC",
    "query": {
     "query": "query_result(pingmesh_server_pingss_total{host=~\"$host\"} or pingmesh_server_drops_total{host=~\"$host\"})"
    }
   },
   {
    "name": "rtt_spike_le",
    "label": "RTT Spike Thresh",
    "query": {
     "query": "label_values(pingmesh_client_max_rtt_hist_bucket,le)"
    }
   },
   { "name": "flaky_factor", "label": "Flaky Factor", "query": "2" }
  ]
 },
 "panels": [
  {
   "title": "Max RTT (Increase)",
   "type": "heatmap",
   "description": "In each interval, the increase of Max RTT that falls in each bucket",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (increase(pingmesh_client_max_rtt_hist_bucket{host=~\"$host\", nic=~\"$nic\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTT Spikes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(pingmesh_client_max_rtt_hist_count{host=~\"$host\", nic=~\"$nic\"}[5m]) - ignoring(le) increase(pingmesh_client_max_rtt_hist_bucket{le=\"$rtt_spike_le\", host=~\"$host\", nic=~\"$nic\"}[5m])",
     "legendFormat": "{{host}}/{{nic}}"
    }
   ]
  },
  {
   "title": "Unhealthy Clients or Servers",
   "type": "state-timeline",
   "description": "`pingmesh_client_healthy < 1` or `pingmesh_server_healthy < 1`",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "pingmesh_client_healthy{host=~\"$host\", nic=~\"$nic\"} < 1",
     "legendFormat": "Client {{host}}/{{pod}}/{{nic}}"
    },
    {
     "expr": "pingmesh_server_healthy{host=~\"$host\", nic=~\"$nic\"} < 1",
     "legendFormat": "Server {{host}}/{{pod}}/{{nic}}"
    }
   ]
  },
  {
   "title": "Unreachable Servers",
   "type": "state-timeline",
   "description": "Servers that are healthy but not responding to pings, i.e. no increase in `pingmesh_server_pings_total`",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "pingmesh:unreachable5m{host=~\"$host\", nic=~\"$nic\"}",
     "legendFormat": "{{host}}/{{nic}}"
    }
   ]
  },
  {
   "title": "Flaky Servers",
   "type": "state-timeline",
   "description": "Servers that are healthy and reachable, but dropping some pings, i.e.  increase in `pingmesh_server_drops_total`",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "((increase(pingmesh_server_drops_total{host=~\"$host\", nic=~\"$nic\"}[30m]) > scalar(pingmesh:server_drops_avg30m * $flaky_factor)) * 0)\nunless on (host, nic)\n(   # healthy but unreachable\n    (increase(pingmesh_server_pings_total{host=~\"$host\", nic=~\"$nic\"}[30m]) == 0)\n    unless on (host, nic)\n        (pingmesh_server_healthy < 1)\n)",
     "legendFormat": "{{host}}/{{nic}}"
    }
   ]
  },
  {
   "title": "Client and Server Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Ping Counts (Outgoing)",
     "type": "timeseries",
     "description": "Sum of pings for all selected hosts and NICs.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum(increase(pingmesh_client_pings_total{host=~\"$host\", nic=~\"$nic\"}[5m]))",
       "legendFormat": "Successful"
      },
      {
       "expr": "sum(increase(pingmesh_client_drops_total{host=~\"$host\", nic=~\"$nic\"}[5m]))",
       "legendFormat": "Dropped"
      }
     ]
    },
    {
     "title": "Server Ping Counts (Incoming)",
     "type": "timeseries",
     "description": "Sum of pings for all selected hosts and NICs.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum(increase(pingmesh_server_pings_total{host=~\"$host\", nic=~\"$nic\"}[5m]))",
       "legendFormat": "Successful"
      },
      {
       "expr": "sum(increase(pingmesh_server_drops_total{host=~\"$host\", nic=~\"$nic\"}[5m]))",
       "legendFormat": "Dropped"
      }
     ]
    }
   ]
  }
 ]
}