{
 "title": "Leaf-Spine Load Balancing",
 "time": { "from": "2025-04-14T18:22:46.000Z", "to": "2025-04-14T18:35:24.000Z" },
 "templating": {
  "list": [
   {
    "name": "switch",
    "label": "Leaf Switch",
    "query": {
     "query": "label_values(interface_watch_list,switch_id)"
    }
   },
   {
    "name": "agent",
    "label": "sFlow Agent",
    "query": {
     "query": "label_values(linkmon_switch_extra_labels{switch=~\"$switch\"},switch_mgmt_ip)"
    }
   },
   { "name": "sport_blacklist", "label": "sport_blacklist_re", "query": "(50000|50001|50002)" },
   { "name": "min_rate", "label": "min_rate (samples/s)", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "Uplink Flow Distribution",
   "type": "table",
   "description": "For each uplink: the number of flows traversing the uplink, and the ratio of all uplink flows traversing this uplink.\n<br>\n<b>N.B.:</b> this only includes uplinks that have been observed through sFlow packet samples; if for some reason packets aren't being sent though a link (or sampled at that link), that link won't be included.",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (switch, ifName) # we need switch for generating data link\n    ((rate(sflow_samples_per_flow_total{sport!~\"$sport_blacklist\", agent=~\"$agent\"}[$__rate_interval]) > $min_rate)\n        * on (agent, portindex) group_left(ifName, switch)\n            (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\"))\n    * on (ifName) group_left interface_watch_list{switch_id=~\"$switch\", conn_type=\"ISL\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (ifName)\n    ((rate(sflow_samples_per_flow_total{sport!~\"$sport_blacklist\", agent=~\"$agent\"}[$__rate_interval]) > $min_rate)\n        * on (agent, portindex) group_left(ifName)\n            (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\"))\n    * on (ifName) group_left interface_watch_list{switch_id=~\"$switch\", conn_type=\"ISL\"})\n/ on() group_left sum(count by (ifName)\n    ((rate(sflow_samples_per_flow_total{sport!~\"$sport_blacklist\", agent=~\"$agent\"}[$__rate_interval]) > $min_rate)\n        * on (agent, portindex) group_left(ifName)\n            (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\"))\n    * on (ifName) group_left interface_watch_list{switch_id=~\"$switch\", conn_type=\"ISL\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (ifName)\n    ((rate(sflow_samples_per_flow_total{sport!~\"$sport_blacklist\", agent=~\"$agent\"}[$__rate_interval]) > $min_rate)\n        * on (agent, portindex) group_left(ifName)\n            (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\")))\n   * on (ifName) group_left()\n   (interface_watch_list{switch_id=~\"$switch\", conn_type=\"ISL\"}))\n   * on () group_left avg(sflow_sampling_rate{agent=~\"$agent\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Uplinks in Use",
   "type": "stat",
   "description": "These are the uplinks currently being traversed by flows, as reported by sFlow packet samples.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (ifName)\n    ((rate(sflow_samples_per_flow_total{sport!~\"$sport_blacklist\", agent=~\"$agent\"}[$__rate_interval]) > $min_rate)\n        * on (agent, portindex) group_left(ifName)\n            (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\"))\n    * on (ifName) group_left interface_watch_list{switch_id=~\"$switch\", conn_type=\"ISL\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Uplink Flow Count",
   "type": "stat",
   "description": "Total number of flows traversing links to spine switches.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (ifName)\n    ((rate(sflow_samples_per_flow_total{sport!~\"$sport_blacklist\", agent=~\"$agent\"}[$__rate_interval]) > $min_rate)\n        * on (agent, portindex) group_left(ifName)\n            (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\"))\n    * on (ifName) group_left interface_watch_list{switch_id=~\"$switch\", conn_type=\"ISL\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ideal Number of Flows Per Link",
   "type": "stat",
   "description": "Essentially `NUMBER_OF_FLOWS / NUMBER_OF_LINKS`",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (ifName)\n    ((rate(sflow_samples_per_flow_total{sport!~\"$sport_blacklist\", agent=~\"$agent\"}[$__rate_interval]) > $min_rate)\n        * on (agent, portindex) group_left(ifName)\n            (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\"))\n    * on (ifName) group_left interface_watch_list{switch_id=~\"$switch\", conn_type=\"ISL\"}))\n/ on() count(count by (ifName)\n    ((rate(sflow_samples_per_flow_total{sport!~\"$sport_blacklist\", agent=~\"$agent\"}[$__rate_interval]) > $min_rate)\n        * on (agent, portindex) group_left(ifName)\n            (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\"))\n    * on (ifName) group_left interface_watch_list{switch_id=~\"$switch\", conn_type=\"ISL\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Uplink Ratio",
   "type": "stat",
   "description": "The ratio of flows that is traversing the most congested uplink.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\ncount by (ifName)\n    ((rate(sflow_samples_per_flow_total{sport!~\"$sport_blacklist\", agent=~\"$agent\"}[$__rate_interval]) > $min_rate)\n        * on (agent, portindex) group_left(ifName)\n            (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\"))\n    * on (ifName) group_left interface_watch_list{switch_id=~\"$switch\", conn_type=\"ISL\"})\n/ on() group_left sum(count by (ifName)\n    ((rate(sflow_samples_per_flow_total{sport!~\"$sport_blacklist\", agent=~\"$agent\"}[$__rate_interval]) > $min_rate)\n        * on (agent, portindex) group_left(ifName)\n            (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\"))\n    * on (ifName) group_left interface_watch_list{switch_id=~\"$switch\", conn_type=\"ISL\"}))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Uplink Rate",
   "type": "stat",
   "description": "The aggregate TX rate across all uplinks.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((rate(sflow_samples_per_flow_total{sport!~\"$sport_blacklist\", agent=~\"$agent\"}[$__rate_interval]) > $min_rate)\n        * on (agent, portindex) group_left(ifName)\n            (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\")))\n   * on (ifName) group_left()\n   (interface_watch_list{switch_id=~\"$switch\", conn_type=\"ISL\"}))\n   * on () group_left avg(sflow_sampling_rate{agent=~\"$agent\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uplink Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (ifName)\n    ((rate(sflow_samples_per_flow_total{sport!~\"$sport_blacklist\", agent=~\"$agent\"}[$__rate_interval]) > $min_rate)\n        * on (agent, portindex) group_left(ifName)\n            (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\")))\n    * on (ifName) group_left(switch_id)\n    (interface_watch_list{switch_id=~\"$switch\", conn_type=\"ISL\"})",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Uplink Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(sum by (ifName)\n    ((rate(sflow_samples_per_flow_total{sport!~\"$sport_blacklist\", agent=~\"$agent\"}[$__rate_interval]) > $min_rate)\n                * on (agent, portindex) group_left(ifName)\n            (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\")))\n    * on (ifName) group_left(switch_id)\n    (interface_watch_list{switch_id=~\"$switch\", conn_type=\"ISL\"}))\n   * on () group_left avg(sflow_sampling_rate{agent=~\"$agent\"})",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Flows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flow Rate",
     "type": "timeseries",
     "description": "The rate is inferred from the packet sample arrival rate : <code>packet sample rate * switch sampling rate * 2KB</code>. It assumes an average packet size of 2KB for all flows. The rate is averaged across the dashboard's selected time range.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "avg by (saddr, daddr, sport, dport)\n    (sum by (agent, saddr, daddr, sport, dport)\n        ((rate(sflow_samples_per_flow_total{agent=~\"$agent\", sport!~\"$sport_blacklist\"}[$__rate_interval]) > $min_rate)\n            * on (agent, portindex) group_left(ifName)\n                (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\"},\n                \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n                \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n                \"ifName\", \"$1\", \"port\", \"(.*)\"))\n             * on (ifName) group_left(switch_id)\n                (interface_watch_list{switch_id=~\"$switch\", conn_type=\"ISL\"}))\n* on () group_left avg(sflow_sampling_rate{agent=~\"$agent\"}))\n",
       "legendFormat": "{{saddr}}:{{sport}}-{{daddr}}:{{dport}}"
      }
     ]
    }
   ]
  }
 ]
}