{
 "title": "Loki Detailed",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(grafana_build_info, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(grafana_build_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Loki CPU Usage",
   "type": "timeseries",
   "description": "CPU Usage shows the percentage of a single CPU core being utilized.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"loki\", container=\"loki\", pod=~\"loki-.*\"}[1m])) by (pod)",
     "legendFormat": "Loki Usage"
    },
    {
     "expr": "machine_cpu_cores\n    * on(node)\n    group_left(pod)\n    kube_pod_info{namespace=\"loki\", pod=~\"loki-.*\"}",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Loki Pods Memory Usage",
   "type": "timeseries",
   "description": "The percentage represents Loki's memory usage relative to the total memory available on a node. It assumes all nodes have the same amount of memory. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"loki\", container=\"loki\"}) / 1024 / 1024 / 1024",
     "legendFormat": "Loki Usage"
    },
    {
     "expr": "node_memory_MemAvailable_bytes\n  * on(instance)\n  group_left(pod)\n  label_replace(\n    kube_pod_info{namespace=\"loki\", pod=~\"loki-.*\"},\n    \"instance\", \"$1:9100\", \"host_ip\", \"(.*)\"\n  )/ 1024 / 1024 / 1024",
     "legendFormat": "Free Memory"
    }
   ]
  },
  {
   "title": "Loki Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(loki_chunk_store_stored_chunk_bytes_total{cluster=\"loki\", namespace=\"loki\", service=\"loki\"})\n",
     "legendFormat": "Loki Usage"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\", fstype!~\"tmpfs|overlay\"}\n  * on(instance)\n  group_left(pod)\n  label_replace(\n    kube_pod_info{namespace=\"loki\", pod=~\"loki-.*\"},\n    \"instance\", \"$1:9100\", \"host_ip\", \"(.*)\"\n  )\n",
     "legendFormat": "Free Space"
    }
   ]
  },
  {
   "title": "Loki Ingestion RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_client_request_duration_seconds_count{namespace=\"loki\", pod=~\"loki-.*\"}[1m])) by (pod)",
     "legendFormat": "{{Processed}}"
    }
   ]
  },
  {
   "title": "Loki Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  rate(container_network_receive_bytes_total{pod=~\"loki-.*\", namespace=\"loki\", interface!=\"lo\"}[5m])\n)",
     "legendFormat": "{{pod}} Receive"
    },
    {
     "expr": "sum by(pod) (\n  rate(container_network_transmit_bytes_total{pod=~\"loki-.*\", namespace=\"loki\", interface!=\"lo\"}[5m])\n)",
     "legendFormat": "{{pod}} Transmit"
    }
   ]
  }
 ]
}