{
 "title": "Network Flows",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "switch",
    "label": "Switch",
    "query": {
     "query": "label_values(interface_watch_list,switch_id)"
    }
   },
   {
    "name": "agent",
    "query": {
     "query": "label_values(linkmon_switch_extra_labels{switch=~\"$switch\"},switch_mgmt_ip)"
    }
   },
   {
    "name": "port",
    "label": "Switch Port",
    "query": {
     "query": "label_values(linkmon_switch_extra_labels,port)"
    }
   },
   {
    "name": "saddr",
    "query": {
     "query": "label_values(sflow_samples_per_flow_total{agent=~\"$agent\"},saddr)"
    }
   },
   {
    "name": "daddr",
    "query": {
     "query": "label_values(sflow_samples_per_flow_total{agent=~\"$agent\"},daddr)"
    }
   },
   { "name": "sport_blacklist", "label": "sport_blacklist_re", "query": "(50000|50001|50002)" },
   { "name": "min_rate", "label": "min_rate (samples/s)", "query": "-1" }
  ]
 },
 "panels": [
  {
   "title": "Largest Source/Destination Pairs (Directed)",
   "type": "netsage-sankey-panel",
   "description": "These flows are grouped by their source/destination IP address, even if they have different transport protocol (e.g., TCP, UDP) ports.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Packets Sampled" } },
   "targets": [
    {
     "expr": "sum by(saddr, daddr)\n    (topk(15, sum by (saddr, daddr) (\n        increase(sflow_samples_per_flow_total{saddr=~\"$saddr\", daddr=~\"$daddr\", sport!~\"$sport_blacklist\", agent=~\"$agent\"}[$__range])\n                * on (agent, portindex) group_left(ifName)\n            (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\", port=~\"$port\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\"))\n        )))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flow Rate",
   "type": "timeseries",
   "description": "The rate is inferred from the packet sample arrival rate : <code>packet sample rate * switch sampling rate * 2KB</code>. It assumes an average packet size of 2KB for all flows. The rate is averaged across the dashboard's selected time range.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by (saddr, daddr, sport, dport) (\n    sum by (agent, saddr, daddr, sport, dport) (\n        (rate(sflow_samples_per_flow_total{agent=~\"$agent\", sport!~\"$sport_blacklist\", saddr=~\"$saddr\", daddr=~\"$daddr\"}[$__rate_interval]) > $min_rate)\n            * on (agent, portindex) group_left(ifName)\n                (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\", port=~\"$port\"},\n                    \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n                    \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n                    \"ifName\", \"$1\", \"port\", \"(.*)\"))\n))\n* on (agent) group_left avg(sflow_sampling_rate{agent=~\"$agent\"}) > 0",
     "legendFormat": "{{saddr}}:{{sport}}-{{daddr}}:{{dport}}"
    }
   ]
  },
  {
   "title": "Flow Table",
   "type": "table",
   "description": "<ul>\n<li><b>job_name:</b> the WsJob to which this flow belongs (if any).</li>\n<li><b>Hops:</b> number of switches traversed by a flow (e.g., leaf->spine->leaf counts as 3 hops).</li>\n<li><b>Rate:</b> the average rate of the flow in the selected time range.</li>\n</ul>",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by (saddr, daddr, sport, dport) (\n    sum by (agent, saddr, daddr, sport, dport) (\n        (rate(sflow_samples_per_flow_total{agent=~\"$agent\", sport!~\"$sport_blacklist\", saddr=~\"$saddr\", daddr=~\"$daddr\"}[$__range]) > $min_rate)\n            * on (agent, portindex) group_left(ifName)\n                (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\", port=~\"$port\"},\n                    \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n                    \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n                    \"ifName\", \"$1\", \"port\", \"(.*)\"))\n))\n* on (agent) group_left avg(sflow_sampling_rate{agent=~\"$agent\"}) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(leaf_switch_port_info, \"saddr\", \"$1\", \"device_ip\", \"(.*)\")\n    * on (saddr) group_right(job_name) group by (saddr, daddr, sport, dport) \n        (rate(sflow_samples_per_flow_total{agent=~\"$agent\", sport!~\"$sport_blacklist\", saddr=~\"$saddr\", daddr=~\"$daddr\"}[$__range]) > $min_rate)\n    * on (agent, portindex) group_left(ifName)\n        (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\", port=~\"$port\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (saddr, daddr, sport, dport) (\n    (rate(sflow_samples_per_flow_total{agent=~\"$agent\", sport!~\"$sport_blacklist\", saddr=~\"$saddr\", daddr=~\"$daddr\"}[$__range]) > $min_rate)\n    * on (agent, portindex) group_left(ifName)\n        (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\", port=~\"$port\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\")))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Link Table",
   "type": "table",
   "description": "Aggregate flows through each switch port.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (switch, agent, ifName) (\n    (rate(sflow_samples_per_flow_total{agent=~\"$agent\", sport!~\"$sport_blacklist\", saddr=~\"$saddr\", daddr=~\"$daddr\"}[$__range]) > $min_rate)\n    * on (agent, portindex) group_left(ifName, switch)\n        (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\", port=~\"$port\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\"))\n    ) * on (agent) group_left avg by (agent) (sflow_sampling_rate)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (agent, ifName) (\n    (rate(sflow_samples_per_flow_total{agent=~\"$agent\", sport!~\"$sport_blacklist\", saddr=~\"$saddr\", daddr=~\"$daddr\"}[$__range]) > $min_rate)\n    * on (agent, portindex) group_left(ifName)\n        (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\", port=~\"$port\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\"))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WsJobs",
   "type": "table",
   "description": "For each WsJob: the total number of flows and the sum of their rates.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (job_name) (\n    label_replace(leaf_switch_port_info, \"saddr\", \"$1\", \"device_ip\", \"(.*)\")\n    * on (saddr) group_right(job_name) count by (saddr, daddr, sport, dport) (\n        (rate(sflow_samples_per_flow_total{agent=~\"$agent\", sport!~\"$sport_blacklist\", saddr=~\"$saddr\", daddr=~\"$daddr\"}[$__range]) > $min_rate)\n        * on (agent, portindex) group_left(ifName)\n            (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\", port=~\"$port\"},\n                \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n                \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n                \"ifName\", \"$1\", \"port\", \"(.*)\"))\n    )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (job_name) (\n    label_replace(leaf_switch_port_info, \"saddr\", \"$1\", \"device_ip\", \"(.*)\")\n    * on (saddr) group_right(job_name) avg by (saddr, daddr, sport, dport) (\n        sum by (agent, saddr, daddr, sport, dport) (\n            (rate(sflow_samples_per_flow_total{agent=~\"$agent\", saddr=~\"$saddr\"}[$__range]) > $min_rate)\n            * on (agent, portindex) group_left(ifName)\n                (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\", port=~\"$port\"},\n                    \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n                    \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n                    \"ifName\", \"$1\", \"port\", \"(.*)\"))\n    ))\n    * on() group_left  avg(sflow_sampling_rate{agent=~\"$agent\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flow Link Table",
   "type": "table",
   "description": "The observed rate for each flow, for each switch port it traverses.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (switch, agent, ifName, saddr, daddr, sport, dport) (\n    (rate(sflow_samples_per_flow_total{agent=~\"$agent\", sport!~\"$sport_blacklist\", saddr=~\"$saddr\", daddr=~\"$daddr\"}[$__range]) > $min_rate)\n    * on (agent, portindex) group_left(switch, ifName)\n        (label_replace(label_replace(label_replace(linkmon_switch_extra_labels{switch=~\"$switch\", port=~\"$port\"},\n            \"portindex\", \"$1\", \"ifindex\", \"(.*)\"),\n            \"agent\", \"$1\", \"switch_mgmt_ip\", \"(.*)\"),\n            \"ifName\", \"$1\", \"port\", \"(.*)\"))\n) * on (agent) group_left avg by (agent) (sflow_sampling_rate)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}