{
 "title": "whereabouts",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "percentile", "query": "1,5,10,50,90,95,99" }
  ]
 },
 "panels": [
  { "title": "Critical Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CG Cron Errors",
   "type": "stat",
   "description": "Global process for cleaning up any IPs that failed to clean up at a host level. Failures indicate lead whereabouts pod failing to perform critical cleanup operation",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(whereabouts_cron_ip_gc_total{status=\"err\"}[$__range])) by (kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pod Errors",
   "type": "stat",
   "description": "Failures in Pod GC indicates both mechanisms for cleaning up IP reservation state at a pod level failed. Reduces number of available IPs for assignment. Global GC should clean these failures up",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(whereabouts_pod_ip_gc_total{status=\"err\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IPAM Error Rate",
   "type": "stat",
   "description": "Host CNI IP allocation error rate",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(whereabouts_operation_duration_seconds_count{status=\"err\"}[$__range])) / sum(increase(whereabouts_operation_duration_seconds_count{}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "IPAM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "IPAM Operations Rate",
   "type": "timeseries",
   "description": "CNI IP allocations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(whereabouts_operation_duration_seconds_count[$__rate_interval])) by (operation, status)",
     "legendFormat": "{{operation}}/{{status}}"
    }
   ]
  },
  {
   "title": "IPAM Error Increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(whereabouts_operation_duration_seconds_count{status=\"err\"}[$__rate_interval])) by (node, operation)",
     "legendFormat": "{{node}}/{{operation}}"
    }
   ]
  },
  {
   "title": "IPAM Duration p$percentile",
   "type": "timeseries",
   "description": "90th percentile IPAM operation durations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum(rate(whereabouts_operation_duration_seconds_bucket[$__rate_interval])) by (le, operation, status))",
     "legendFormat": "{{operation}}/{{status}}"
    }
   ]
  },
  {
   "title": "IPAM Retries p$percentile",
   "type": "timeseries",
   "description": "90th percentile optimistic retries before operation succeeds. Higher values are worse",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(rate(whereabouts_operation_retries_bucket[$__rate_interval])) by (le, operation, status))",
     "legendFormat": "{{operation}}/{{status}}"
    }
   ]
  },
  { "title": "GC Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "IP Cron GC'd",
   "type": "timeseries",
   "description": "Increase in IP or Pool entries GC'd by global cron process.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(whereabouts_cron_ip_gc_total[$__rate_interval])) by (kind, status) > 0",
     "legendFormat": "{{kind}}/{{status}}"
    }
   ]
  },
  {
   "title": "Pod IP GC'd",
   "type": "timeseries",
   "description": "Increase in pod IP GCs. Happens if kubelet fails to GC Pod IP. Increases indicate failures at kubelet level",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(whereabouts_pod_ip_gc_total[$__rate_interval])) by (status) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Overlapping IP Objects",
   "type": "timeseries",
   "description": "Total overlapping IP CRD objects. Sometimes useful in detecting IP leaks",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "avg(apiserver_storage_objects{resource=\"overlappingrangeipreservations.whereabouts.cni.cncf.io\"})",
     "legendFormat": "ips"
    },
    {
     "expr": "avg(apiserver_storage_objects{resource=\"pods\"})",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "Operator Restarts",
   "type": "timeseries",
   "description": "Increase in operator pod restarts. Restarts indicate lost leader election and possibly some issue reaching controlplane",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"whereabouts-operator.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}