apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
  labels:
    app.kubernetes.io/name: loki
spec:
  capacity:
    storage: 50Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # required
  hostPath:
    path: "/n0/cluster-mgmt/loki"
    type: DirectoryOrCreate
