#!/bin/bash
set -e

# The version for the OS image used for deploying new clusters should be 
# consistent with the version for upgrading existing clusters.
version="1.7.20"

wget https://github.com/containerd/containerd/archive/v${version}.zip
unzip v${version}.zip
rm -f v${version}.zip
cd containerd-${version}
wget https://github.com/containerd/containerd/releases/download/v${version}/containerd-${version}-linux-amd64.tar.gz
tar xvf containerd-${version}-linux-amd64.tar.gz
sudo cp ./bin/* /usr/local/bin/.
sudo mkdir -p /etc/containerd
containerd config default > config.toml
sed -i 's/pause:3.6/pause:3.7/' config.toml
sudo cp config.toml /etc/containerd/.
sudo cp containerd.service /etc/systemd/system/.
cd ..
rm -rf containerd-${version}
# enable and start containerd service
cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
overlay
br_netfilter
EOF
sudo modprobe overlay
sudo modprobe br_netfilter
# Setup required sysctl params, these persist across reboots.
cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF
# Apply sysctl params without reboot
sudo sysctl --system
sudo systemctl enable --now containerd.service
sudo systemctl start containerd
