apiVersion: batch/v1
kind: Job
metadata:
  name: ceph-sync-{job_id}
  namespace: kube-system
  labels:
    app: ceph-sync
    job-id: "{job_id}"
spec:
  activeDeadlineSeconds: 28800
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: ceph-sync
        job-id: "{job_id}"
    spec:
      restartPolicy: Never
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: ceph-sync
        image: "{sync_image}"
        command: ["/bin/bash", "-c"]
        args:
        - |
          set -euo pipefail
          echo "Starting CephFS sync at $(date)"
          
          # Install required packages
          echo "Installing required packages..."
          apt-get update -qq
          apt-get install -y -qq ceph-common rsync jq
          
          # Set up environment variables for the sync script
          export VOLUMES_TO_SYNC='{volumes_json}'
          export SRC_MNT="/mnt/src_ceph"
          export DST_MNT="/mnt/dst_ceph"
          export CLEANUP_MOUNTS="{cleanup_mounts}"
          export SRC_CEPH_CONF="/etc/ceph/src/ceph.conf"
          export SRC_KEYRING="/etc/ceph/src/keyring"
          export DST_CEPH_CONF="/etc/ceph/dst/ceph.conf"
          export DST_KEYRING="/etc/ceph/dst/keyring"
          
          # Execute the sync script
          exec /scripts/run_sync.sh
        
        securityContext:
          privileged: true
          runAsUser: 0
          capabilities:
            add: ["SYS_ADMIN"]
        
        volumeMounts:
        - name: sync-scripts
          mountPath: /scripts
        - name: src-ceph-conf
          mountPath: /etc/ceph/src
          readOnly: true
        - name: dst-ceph-conf
          mountPath: /etc/ceph/dst
          readOnly: true
        - name: sys
          mountPath: /sys
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
      volumes:
      - name: sync-scripts
        configMap:
          name: ceph-sync-scripts-{job_id}
          defaultMode: 0755
      - name: src-ceph-conf
        secret:
          secretName: ceph-src-config-{job_id}
      - name: dst-ceph-conf
        secret:
          secretName: ceph-dst-config-{job_id}
      - name: sys
        hostPath:
          path: /sys
      - name: lib-modules
        hostPath:
          path: /lib/modules
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-sync-scripts-{job_id}
  namespace: kube-system
data:
  run_sync.sh: |
{run_sync_script}
  mount_ceph.sh: |
{mount_ceph_script}
  sync_volume.sh: |
{sync_volume_script}
  unmount_ceph.sh: |
{unmount_ceph_script}
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-src-config-{job_id}
  namespace: kube-system
type: Opaque
data:
  ceph.conf: "{src_conf_b64}"
  keyring: "{src_keyring_b64}"
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-dst-config-{job_id}
  namespace: kube-system
type: Opaque
data:
  ceph.conf: "{dst_conf_b64}"
  keyring: "{dst_keyring_b64}"