- name: Remove password based SSH login for root
  hosts: root-server, nodes
  tasks:
    - name: Update SSH to prohibit root password login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'
        insertafter: EOF

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted

    - name: Change root user password
      user:
        name: root
        password: "{{ ansible_password | password_hash('sha512') }}"