# This playbook initializes the management node after a fresh install and configures its services,
# such as dnsmasq and httpd.
#
# Defaults for configurable parameters are set in `roles/mgmt-node/defaults/`, and should be
# overridden by `host_vars/mgmt-node` for site and hardware-specific values.

- hosts: root-server
  tasks:
    # common tasks
    - import_role:
        name: common
        tasks_from: root_partition
    - import_role:
        name: common
        tasks_from: hostname
    - import_role:
        name: common
        tasks_from: password
    - import_role:
        name: common
        tasks_from: raid
    - import_role:
        name: common
        tasks_from: lldp

    # root server specific tasks
    - import_role:
        name: root-server
        tasks_from: init-nic
      tags: mgmt-init-nic
      when: "setup_network == True"
    - import_role:
        name: root-server
        tasks_from: init-node
      tags: mgmt-node-init
    - import_role:
        name: root-server
        tasks_from: init-services
      tags: mgmt-node-services
    - import_role:
        name: static-ip
        tasks_from: main
    - import_role:
        name: dnsmasq
        tasks_from: main
      when: dhcp_provider == "dnsmasq"
    - import_role:
        name: kea
        tasks_from: main
      when: dhcp_provider == "kea"
