# This playbook contains provisioning common to all types of nodes in the cluster
#
# Configurable parameters are set in `group_vars/all`

- hosts: root-server, nodes
  tasks:
    - import_role:
        name: common
      tags: base
    - import_role:
        name: common
        tasks_from: ib-check
      tags: ib-check
    - import_role:
        name: common
        tasks_from: change-pam-limit.yml
      tags: usernode-config

- import_playbook: configure-wsjoblog-storage.yml
  tags: wsjoblog-storage
  
# reboot non mgmt nodes
- hosts: nodes
  tasks:
    - name: Reboot non root-server nodes
      reboot:
        reboot_timeout: 600
