# This playbook initializes the management node after a fresh install and configures its services,
# such as dnsmasq and httpd.
#
# Defaults for configurable parameters are set in `roles/mgmt-node/defaults/`, and should be
# overriden by `host_vars/mgmt-node` for site and hardware-specific values.

- hosts: mgmt-node
  tasks:
    - name: running validation tool 
      shell: /opt/cbmon/cbmon-cluster-check-master.sh
   
