- name: Change nofile hard limit to 20000
  community.general.pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: nofile
    value: 20000
  when: group_names is search("US")

- name: Change nofile soft limit to 20000
  community.general.pam_limits:
    domain: '*'
    limit_type: soft
    limit_item: nofile
    value: 20000
  when: group_names is search("US")

- name: Change nproc hard limit to 16384
  community.general.pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: nproc
    value: 16384
  when: group_names is search("US")

- name: Change nproc soft limit to 16384
  community.general.pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: nproc
    value: 16384
  when: group_names is search("US")


- name: Create python directory
  file: path=/opt/python3.8/bin state=directory

- name: Create python3.8 link
  file:
    src: /usr/bin/python3.8
    dest: /opt/python3.8/bin/python3.8
    state: link 
  when: group_names is search("US")