# configure chrony to sync to the root server

- name: Deploy chrony.conf template
  template:
    src: chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags:
    - services
    - ntp
  when:
    - inventory_hostname != management_node

- name: Restart chronyd
  service:
    name: chronyd
    state: restarted
  tags:
    - services
    - ntp
  when:
    - inventory_hostname != management_node
