- name: Reset root password to default
  user:
    name: root
    password: "{{ hostvars[inventory_hostname].ansible_password | password_hash('sha512') }}"
  when:
    - hostvars[inventory_hostname].ansible_password is defined