- name: Extract root volume
  # Typically /dev/sda or /dev/nvme0n1
  shell: fdisk -l | grep 'Linux LVM' | awk '{print $1}' | sed 's/p\?[0-9]\+$//'
  register: root_vol

- name: Extract root partition
  # Typically 2 as in /dev/sda2, or p2 as in /dev/nvme0n1p2
  shell: fdisk -l | grep 'Linux LVM' | awk '{print $1}' | grep -Eo 'p?[0-9]+$'
  register: root_part

- name: Extract root partition number
  # Typically 2 as in /dev/sda2, or 2 as in /dev/nvme0n1p2
  shell: fdisk -l | grep 'Linux LVM' | awk '{print $1}' | grep -Eo '[0-9]+$'
  register: root_part_num
  
- name: Resize partition
  parted:
    device: "{{ root_vol.stdout }}"
    number: "{{ root_part_num.stdout }}"
    part_end: "100%"
    resize: yes
    state: present
  tags: root-vol

- name: Resize PV
  lvg:
    vg: rl
    pvs: "{{ root_vol.stdout }}{{ root_part.stdout }}"
    pvresize: yes
    state: present
  tags: root-vol

- name: Resize LVM
  lvol:
    vg: rl
    lv: root
    size: +100%FREE
    resizefs: yes
    state: present
  tags: root-vol