- name: Copy rsyslog.conf to /etc
  template:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
    mode: 0644
  tags: services

- name: Restart rsyslog service
  systemd:
    name: rsyslog
    state: restarted
  tags: services