resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 500m

nodeSelector:
  storage-type: ceph

tolerations:
  - key: node-role.kubernetes.io/master 
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

pluginTolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule


csi:
  enableRbdDriver: false
  enableCephfsDriver: true
  provisionerNodeAffinity: storage-type=ceph
  provisionerTolerations:
    - key: node-role.kubernetes.io/master 
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

  pluginTolerations:
    - key: node-role.kubernetes.io/master 
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

  discover:
    tolerations:
      - key: node-role.kubernetes.io/master 
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    nodeAffinity: storage-type=ceph

  admissionController:
    tolerations:
      - key: node-role.kubernetes.io/master 
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    nodeAffinity: storage-type=ceph

monitoring:
  enabled: false
