rule_files:
  - alerts_out/test.yaml

evaluation_interval: 1m

tests:

- interval: 1m
  input_series:
  - series: 'kube_pod_container_status_terminated_reason{container="ws", namespace="temp-fence-8node", pod="wsjob-test000-coordinator-0", reason="OOMKilled"}'
    values: '0 0 0 0 0 1 1 1 1 1 1'
  alert_rule_test:
  - eval_time: 10m
    alertname: WsjobPodError
    exp_alerts:
    - exp_labels:
        pod: wsjob-test000-coordinator-0
        reason: OOMKilled
        severity: warning
      exp_annotations:
        summary: "Wsjob failed."
        description: 'wsjob-test000-coordinator-0 error: OOMKilled.'

# Verify that node:node_num_cpu:sum triggers no many-to-many errors.
#- interval: 1m
#  input_series:
#  - series: 'node_cpu_seconds_total{cpu="0",endpoint="https",instance="instance1",job="node-exporter",mode="idle",namespace="openshift-monitoring",pod="node-exporter-1",service="node-exporter"}'
#    values: '1 1'
#  - series: 'node_cpu_seconds_total{cpu="1",endpoint="https",instance="instance1",job="node-exporter",mode="idle",namespace="openshift-monitoring",pod="node-exporter-1",service="node-exporter"}'
#    values: '1 1'
#  - series: 'kube_pod_info{namespace="openshift-monitoring",node="node-1",pod="node-exporter-1",job="kube-state-metrics",instance="10.129.2.7:8443"}'
#    values: '1 1'
#  - series: 'kube_pod_info{namespace="openshift-monitoring",node="node-1",pod="alertmanager-0",job="kube-state-metrics",instance="10.129.2.7:8443"}'
#    values: '1 stale'
#  - series: 'kube_pod_info{namespace="openshift-monitoring",node="node-2",pod="alertmanager-0",job="kube-state-metrics",instance="10.129.2.7:8443"}'
#    values: '1 1'
#  promql_expr_test:
#  - eval_time: 0m
#    expr: node:node_num_cpu:sum
#    exp_samples:
#    - value: 2
#      labels: 'node:node_num_cpu:sum{node="node-1"}'
#  - eval_time: 1m
#    expr: node:node_num_cpu:sum
#    exp_samples:
#    - value: 2
#      labels: 'node:node_num_cpu:sum{node="node-1"}'
