# Set lower-than-production resource limits since KIND is resource constrained.
controller:
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 1Gi
  metrics:
    enabled: false
    service: null
    serviceMonitor: null
