# Set lower-than-production resource limits since KIND is resource constrained.
resources:
  limits:
    memory: 500Mi
  requests:
    memory: 500Mi

operator:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi

hubble:
  enabled: false
  relay:
    enabled: false
  ui:
    enabled: false
