{
 "title": "Space Capacity",
 "tags": [ "VAST" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_online,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Logical Capacity",
   "type": "stat",
   "description": "Note that the statistics here are based on current DRR, and may change accordingly.",
   "gridPos": { "h": 16, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vast_cluster_logical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Logical Space Used "
    },
    {
     "expr": "vast_cluster_logical_space{cluster=\"$cluster\"}",
     "legendFormat": "Total Logical Space "
    },
    {
     "expr": "100 * vast_cluster_logical_space_in_use{cluster=\"$cluster\"}/ vast_cluster_logical_space{cluster=\"$cluster\"}",
     "legendFormat": "Logical Space Used - Percentage"
    },
    {
     "expr": "vast_cluster_logical_space{cluster=\"$cluster\"} - vast_cluster_physical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Logical Space Remaining"
    }
   ]
  },
  {
   "title": "Physical Capacity",
   "type": "stat",
   "gridPos": { "h": 16, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vast_cluster_physical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Physical Space Used "
    },
    {
     "expr": "vast_cluster_physical_space{cluster=\"$cluster\"}",
     "legendFormat": "Total Physical Space "
    },
    {
     "expr": "100 * vast_cluster_physical_space_in_use{cluster=\"$cluster\"}/ vast_cluster_physical_space{cluster=\"$cluster\"}",
     "legendFormat": "Physical Space Used - Percentage"
    },
    {
     "expr": "vast_cluster_physical_space{cluster=\"$cluster\"} - vast_cluster_physical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Physical Space Remaining"
    }
   ]
  },
  {
   "title": "Last DRR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vast_cluster_drr{cluster=\"$cluster\"}",
     "legendFormat": "Data Reduction Ratio"
    }
   ]
  },
  {
   "title": "Capacity over Time",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "vast_cluster_logical_space_in_use{cluster=\"$cluster\", instance=\"10.131.7.61:8001\"}",
     "legendFormat": "Logical Space Used "
    },
    {
     "expr": "vast_cluster_logical_space{cluster=\"$cluster\", instance=\"10.131.7.61:8001\"}",
     "legendFormat": "Total Logical Space "
    },
    {
     "expr": "100 * vast_cluster_logical_space_in_use{cluster=\"$cluster\"}/ vast_cluster_logical_space{cluster=\"$cluster\"}",
     "legendFormat": "Logical Space Used - Percentage"
    },
    {
     "expr": "vast_cluster_physical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Physical Space Used"
    },
    {
     "expr": "vast_cluster_physical_space{cluster=\"$cluster\"}",
     "legendFormat": "Total Physical Space"
    },
    {
     "expr": "100 * vast_cluster_physical_space_in_use{cluster=\"$cluster\"}/ vast_cluster_physical_space{cluster=\"$cluster\"}",
     "legendFormat": "Physical Space Used - Percentage"
    }
   ]
  },
  {
   "title": "Auxiliary Capacity Data",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vast_cluster_auxiliary_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Auxiliary Space Used"
    },
    {
     "expr": "100 * vast_cluster_auxiliary_space_in_use{cluster=\"$cluster\"}/ vast_cluster_physical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Auxiliary Used / Physical Used"
    },
    {
     "expr": "100 * vast_cluster_auxiliary_space_in_use{cluster=\"$cluster\"} /vast_cluster_physical_space{cluster=\"$cluster\"}",
     "legendFormat": "Auxiliary Used / Total Physical Space"
    }
   ]
  }
 ]
}