{
 "title": "VAST Cluster Statistics - Main",
 "description": "Visualization VAST cluster metrics.",
 "tags": [ "VAST" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vast_cluster_online,cluster)"
    }
   },
   {
    "name": "user",
    "label": "User",
    "query": {
     "query": "label_values(vast_user_total_bw,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vast_cluster_online{cluster=\"$cluster\"}",
     "legendFormat": "Cluster State"
    }
   ]
  },
  {
   "title": "Memory RAID State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vast_memory_raid_healthy{cluster=\"$cluster\"}",
     "legendFormat": "Memory State"
    }
   ]
  },
  {
   "title": "Components",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(id) (vast_cnode_failed{cluster=\"$cluster\"}))",
     "legendFormat": "CNodes"
    },
    {
     "expr": "count(count by(id) (vast_dnode_failed{cluster=\"$cluster\"}))",
     "legendFormat": "DNodes"
    },
    {
     "expr": "count(count by(title) (vast_ssd_failed{cluster=\"$cluster\"}))",
     "legendFormat": "SSDs"
    },
    {
     "expr": "count(count by(title) (vast_nvram_failed{cluster=\"$cluster\"}))",
     "legendFormat": "SCMs"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vast_cluster_metrics_ProtoConnectionMetrics_nfs3_tcp_pool{cluster=\"$cluster\"}",
     "legendFormat": "NFSv3"
    },
    {
     "expr": "vast_cluster_metrics_ProtoConnectionMetrics_s3_conn_pool{cluster=\"$cluster\"}",
     "legendFormat": "S3"
    },
    {
     "expr": "vast_cluster_metrics_ProtoConnectionMetrics_smb_conn_pool{cluster=\"$cluster\"}",
     "legendFormat": "SMB"
    },
    {
     "expr": "vast_cluster_metrics_Nfs4Metrics_nfs4_open_connections_cnt{cluster=\"$cluster\"}",
     "legendFormat": "NFSv4"
    },
    {
     "expr": "vast_cluster_metrics_ProtoConnectionMetrics_smb_conn_pool{cluster=\"$cluster\"} + vast_cluster_metrics_ProtoConnectionMetrics_s3_conn_pool{cluster=\"$cluster\"} + vast_cluster_metrics_ProtoConnectionMetrics_nfs3_tcp_pool{cluster=\"$cluster\"} +\nvast_cluster_metrics_Nfs4Metrics_nfs4_open_connections_cnt{cluster=\"$cluster\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Capacity Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vast_cluster_logical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Logical"
    },
    {
     "expr": "vast_cluster_physical_space_in_use{cluster=\"$cluster\"}",
     "legendFormat": "Physical"
    }
   ]
  },
  {
   "title": "Alarm Counter ",
   "type": "table",
   "description": "Click to see all alarms",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(vast_vms_alarms{event_name!='NOTIFIER_EVENT'}) by (severity)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SCM RAID State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vast_nvram_raid_healthy{cluster=\"$cluster\"}",
     "legendFormat": "NVRAM State"
    }
   ]
  },
  {
   "title": "Failed Components",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vast_cnode_failed{cluster=\"$cluster\"})",
     "legendFormat": "CNodes"
    },
    {
     "expr": "sum(vast_dnode_failed{cluster=\"$cluster\"})",
     "legendFormat": "DNodes"
    },
    {
     "expr": "sum(vast_ssd_failed{cluster=\"$cluster\"})",
     "legendFormat": "SSDs"
    },
    {
     "expr": "sum(vast_nvram_failed{cluster=\"$cluster\"})",
     "legendFormat": "SCMs"
    }
   ]
  },
  {
   "title": "Physical Space usage - Percentage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * vast_cluster_physical_space_in_use{cluster=\"$cluster\"} / vast_cluster_physical_space{cluster=\"$cluster\"}",
     "legendFormat": "Physical Space usage - Percentage"
    }
   ]
  },
  {
   "title": "SSD RAID State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vast_ssd_raid_healthy{cluster=\"$cluster\"}",
     "legendFormat": "SSD State"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "<p><br></p>\n<h1 style=\"text-align: center;\">Performance Metrics - Total</h1>\n"
   }
  },
  {
   "title": "Metadata IOPs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "vast_cluster_metrics_ProtoMetrics_rd_md_iops{cluster=\"$cluster\",proto_name=\"ProtoAll\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "vast_cluster_metrics_ProtoMetrics_wr_md_iops{cluster=\"$cluster\",proto_name=\"ProtoAll\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Average Bandwidth + Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_size_sum{cluster=\"$cluster\", proto_name=\"ProtoAll\"}[2m])",
     "legendFormat": "Read BW"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_size_sum{cluster=\"$cluster\", proto_name=\"ProtoAll\"}[2m])",
     "legendFormat": "Write BW"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_latency_sum{cluster=\"$cluster\", proto_name=\"ProtoAll\"}[2m]) / rate(vast_cluster_metrics_ProtoMetrics_read_latency_count{cluster=\"$cluster\", proto_name=\"ProtoAll\"}[2m])",
     "legendFormat": "Read Latency"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_latency_sum{cluster=\"$cluster\", proto_name=\"ProtoAll\"}[2m]) / rate(vast_cluster_metrics_ProtoMetrics_write_latency_count{cluster=\"$cluster\", proto_name=\"ProtoAll\"}[2m])",
     "legendFormat": "Write Latency"
    }
   ]
  },
  {
   "title": "Read + Write IOPs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_read_size_count{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[2m])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(vast_cluster_metrics_ProtoMetrics_write_size_count{cluster=\"$cluster\",proto_name=\"ProtoAll\"}[2m])",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}